### PR TITLE
revert log2f changes due to rate loss

### PR DESCRIPTION
**Pull request by ttrigui**
move back log2f/LOG2F to EbDefinitions.h/EbUtility.h due to rate degradation caused by moving it to common_dsp_rtcd.c until further investigation

### CODE REVIEW

**Comment by tianjunwork** [comment]
Hi @mafonsoN @elintencent, we would like to include this one into the 0.8.3 tag(to address ffmpeg/gst issue, needed by other ovc project release). Hopefully we can tag is today, no later than end of tomorrow. Could you review it first? Thank you!

**Comment by tianjunwork** [comment]
So sorry that somehow I missed merging this one into 0.8.3 :(

**Comment by silverbacknet** [comment]
> So sorry that somehow I missed merging this one into 0.8.3 :(

It's still Friday where I am, could force a re-tag to it no-harm no-foul. 😉

**Comment by tianjunwork** [comment]
Thank you @silverbacknet. The tag is fixed to this commit.

**Pull request merged**
