### PR TITLE
Travis: add verbose makefile to print commands

### PR DESCRIPTION
**Pull request by 1480c1**
Prints all commands including c flags etc, might make the travis log a bit log

### CODE REVIEW

**Comment by 1480c1** [comment]
@kylophone or @hassount, should unused-variable also be added to the Werror exclusion list?

**Comment by kylophone** [comment]
> @kylophone or @hassount, should unused-variable also be added to the Werror exclusion list?

No, I don't think so. The whole point of this is to avoid committing code that causes compiler warnings.

**Comment by 1480c1** [comment]
> > @kylophone or @hassount, should unused-variable also be added to the Werror exclusion list?
> 
> No, I don't think so. The whole point of this is to avoid committing code that causes compiler warnings.

Okay, because travis found in ASM_AVX2/highbd_inv_txfm_avx2.c
``` none
In file included from /home/travis/build/OpenVisualCloud/SVT-AV1/Source/Lib/Common/ASM_AVX2/highbd_inv_txfm_avx2.c:16:0:
/home/travis/build/OpenVisualCloud/SVT-AV1/Source/Lib/Common/ASM_SSSE3/av1_inv_txfm_ssse3.h:90:20: error: ‘NewSqrt2list’ defined but not used [-Werror=unused-variable]
     static int32_t NewSqrt2list[TX_SIZES] = { 5793, 2 * 4096, 2 * 5793, 4 * 4096,
```

**Comment by hassount** [comment]
> > @kylophone or @hassount, should unused-variable also be added to the Werror exclusion list?
> 
> No, I don't think so. The whole point of this is to avoid committing code that causes compiler warnings.

If we're trying to not have compiler warnings then I believe it's best that it gets added. To disable it in the cmake lists. what we'd like to avoid is having a list of these every time we compile the code which would make it hard to distinguish which ones are unused and which ones are more severe warnings

**Comment by 1480c1** [comment]
> To disable it in the cmake lists.

What does this sentence refer to? Not exactly sure of my interpretation

**Comment by 1480c1** [comment]
Also @hassount, can you look at https://github.com/OpenVisualCloud/SVT-AV1/blob/58d8e6f2b28617a04ebee3be3a0b7146299233c4/Source/Lib/Common/Codec/EbMotionEstimationProcess.c#L153-L214 and tell me if that if the indentation of if and else is correct? gcc 7.4.0 is giving misleading-indentation warnings

**Comment by kylophone** [comment]
> and tell me if that if the indentation of if and else is correct? gcc 7.4.0 is giving misleading-indentation warnings

These blocks need brackets.

**Comment by hassount** [comment]
> > To disable it in the cmake lists.
> 
> What does this sentence refer to? Not exactly sure of my interpretation

my understanding is that you could instruct the compiler to specifically suppress a set of warnings and such could be done in the CMakeLists, unless such is not possible anymore.

**Comment by 1480c1** [comment]
It is possible, although I was referring to adding it to Travis rather than to the cmakelists since that is where werror is being set

**Comment by mafonsoN** [comment]
The travis output is indeed very long with verbose. Since that Werror is working, is this still necessary?

**Comment by 1480c1** [comment]
Unsure if it really is, since the only times we would need to see the commands would be if we need to confirm what flags are used etc

**Comment by mafonsoN** [comment]
Closing this for now. Thanks @1480c1. We can consider enabling verbose prints later.

**Pull request closed without merging**
