### PR TITLE
CMake cleanups

### PR DESCRIPTION
**Pull request by ePirat**
The CMake build definitions duplicated some code that was common to x86 and non-x86, this PR solves that.

### CODE REVIEW

**Comment by ePirat** [comment]
@1480c1 There are some cases too like

```
if(X86)
    add_library(SvtAv1Dec
        ${all_files}
        $<TARGET_OBJECTS:COMMON_CODEC>
        $<TARGET_OBJECTS:FASTFEAT>
        $<TARGET_OBJECTS:COMMON_C_DEFAULT>
        $<TARGET_OBJECTS:COMMON_ASM_SSE2>
        $<TARGET_OBJECTS:COMMON_ASM_SSSE3>
        $<TARGET_OBJECTS:COMMON_ASM_SSE4_1>
        $<TARGET_OBJECTS:COMMON_ASM_AVX2>
        $<TARGET_OBJECTS:COMMON_ASM_AVX512>)
else()
    add_library(SvtAv1Dec
        ${all_files}
        $<TARGET_OBJECTS:COMMON_CODEC>
        $<TARGET_OBJECTS:FASTFEAT>
        $<TARGET_OBJECTS:COMMON_C_DEFAULT>)
endif()
```

Do you know if it's somehow possible to only do `add_library` once and assign the objects to some variable or so?

**Comment by 1480c1** [comment]
I think [target_sources](https://cmake.org/cmake/help/v3.5/command/target_sources.html) might work

**Comment by ePirat** [comment]
@1480c1 Ok, I'll see if that works and do a follow-up PR if this is merged.

**Comment by tianjunwork** [comment]
Hi @joelsole, good to go?

**Pull request merged**
