### PR TITLE
Fix the conflict between RC modes

### PR DESCRIPTION
**Pull request by anaghdin**

### CODE REVIEW

**Comment by hassount** [comment]
@j-mas
Can you please confirm that this addressed the RC issue you were seeing ?

**Comment by j-mas** [comment]
@hassount 
Yes this works, but...!
AppVeyor build 1.0.409 works but the next build 1.0.410 not!!!

**Comment by hassount** [comment]
@j-mas 
Thank you for confirming.
That is expected, the appveyor build of 1.0.410 belongs to another PR which does not contain this fix as it is not in the master yet.

**Comment by j-mas** [comment]
Ok! I understand!

-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 28.03.19, 21:00, Hassene Tmar <notifications@github.com> schrieb:
@j-mas
Thank you for confirming.
That is expected, the appveyor build of 1.0.410 belongs to another PR which does not contain this fix as it is not in the master yet.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/OpenVisualCloud/SVT-AV1","title":"OpenVisualCloud/SVT-AV1","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/OpenVisualCloud/SVT-AV1"}},"updates":{"snippets":[{"icon":"PERSON","message":"@hassount in #204: @j-mas \r\nThank you for confirming.\r\nThat is expected, the appveyor build of 1.0.410 belongs to another PR which does not contain this fix as it is not in the master yet. "}],"action":{"name":"View Pull Request","url":"https://github.com/OpenVisualCloud/SVT-AV1/pull/204#issuecomment-477749491"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/OpenVisualCloud/SVT-AV1/pull/204#issuecomment-477749491",
"url": "https://github.com/OpenVisualCloud/SVT-AV1/pull/204#issuecomment-477749491",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Pull request merged**
