### PR TITLE
Avoid off-by-one in update_cdf()

### LINKED ISSUE #143: AddressSanitizer: stack-buffer-overflow (on any input)
Found on FreeBSD with Clang 8.0. Lines correspond to 8d75aadc3a3c snapshot.

```
$ curl -O https://media.xiph.org/video/derf/y4m/bus_cif.y4m
$ ffmpeg -i bus_cif.y4m -y bus_cif.yuv
$ SvtAv1EncApp -i bus_cif.yuv -w 352 -h 288 -b bus_cif.ivf
-------------------------------------------
SVT-AV1 Encoder
SVT [version]:  SVT-AV1 Encoder Lib v0.4.0
SVT [build]  :  GCC 4.2.1        64 bit
LIB Build date: Mar  5 2019 17:04:29
-------------------------------------------
Number of logical cores available: 8
Number of PPCS 41
-------------------------------------------
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: EncoderMode                                                       : 7
SVT [config]: EncoderBitDepth / CompressedTenBitFormat                          : 8 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 352 / 288
SVT [config]: FrameRate / Gop Size                                              : 30 / 32
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure          : 4 / 0 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 50 / 33 / 0
-------------------------------------------
Encoding          =================================================================
==903==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7fffd81bdfb4 at pc 0x000801656bdf bp 0x7fffd81bde50 sp 0x7fffd81bde48
READ of size 2 at 0x7fffd81bdfb4 thread T62
    #0 0x801656bde in update_cdf Source/Lib/Codec/EbCabacContextModel.h:657:21
    #1 0x8016312e3 in aom_write_symbol Source/Lib/Codec/EbBitstreamUnit.h:345:34
    #2 0x801656a9f in EncodePartitionAv1 Source/Lib/Codec/EbEntropyCoding.c:1025:9
    #3 0x801654a94 in write_sb Source/Lib/Codec/EbEntropyCoding.c:5535:17
    #4 0x80166a8a8 in EntropyCodingLcu Source/Lib/Codec/EbEntropyCodingProcess.c:393:5
    #5 0x801666fb4 in EntropyCodingKernel Source/Lib/Codec/EbEntropyCodingProcess.c:597:21
    #6 0x8011ac775 in thread_start /usr/src/lib/libthr/thread/thr_create.c:291:16

Address 0x7fffd81bdfb4 is located in stack of thread T62 at offset 52 in frame
    #0 0x801655fff in EncodePartitionAv1 Source/Lib/Codec/EbEntropyCoding.c:967

  This frame has 2 object(s):
    [32, 36) 'cdf' (line 1014)
    [48, 52) 'cdf99' (line 1023) <== Memory access at offset 52 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
Thread T62 created by T0 here:
    #0 0x10fdabd in __interceptor_pthread_create (/usr/local/bin/SvtAv1EncApp+0xdcabd)
    #1 0x801a59028 in eb_create_thread Source/Lib/Codec/EbThreads.c:95:13
    #2 0x8015fa392 in eb_init_encoder Source/Lib/Codec/EbEncHandle.c:1896:9
    #3 0x113c81e in InitEncoder Source/App/EbAppContext.c:615:20
    #4 0x114081b in main Source/App/EbAppMain.c:161:52
    #5 0x107411c in _start /usr/src/lib/csu/amd64/crt1.c:76:7
    #6 0x80117ffff  (<unknown module>)

SUMMARY: AddressSanitizer: stack-buffer-overflow Source/Lib/Codec/EbCabacContextModel.h:657:21 in update_cdf
Shadow bytes around the buggy address:
  0x4ffffb037ba0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x4ffffb037bb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x4ffffb037bc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x4ffffb037bd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x4ffffb037be0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x4ffffb037bf0: f1 f1 f1 f1 f8 f2[04]f3 00 00 00 00 00 00 00 00
  0x4ffffb037c00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x4ffffb037c10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x4ffffb037c20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x4ffffb037c30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x4ffffb037c40: f1 f1 f1 f1 f8 f2 f8 f2 f8 f2 f8 f2 f8 f3 f3 f3
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==903==ABORTING
```

### PR DESCRIPTION
**Pull request by jbeich**
Fixes #143

### CODE REVIEW

**Comment by jbeich** [comment]
> only the first two elements of cdf are being used. Why allocate more memory?

To avoid patching `update_cdf()` which comes from libaom. Do you really want the following?

```
--- Source/Lib/Codec/EbCabacContextModel.h.orig
+++ Source/Lib/Codec/EbCabacContextModel.h
@@ -654,8 +654,8 @@ extern "C" {
         static const int32_t nsymbs2speed[17] = { 0, 0, 1, 1, 2, 2, 2, 2, 2,
             2, 2, 2, 2, 2, 2, 2, 2 };
         assert(nsymbs < 17);
-        rate = 3 + (cdf[nsymbs] > 15) + (cdf[nsymbs] > 31) +
-            nsymbs2speed[nsymbs];  // + get_msb(nsymbs);
+        rate = 3 + (cdf[nsymbs-1] > 15) + (cdf[nsymbs-1] > 31) +
+            nsymbs2speed[nsymbs-1];  // + get_msb(nsymbs);
         tmp = AOM_ICDF(0);
 
         // Single loop (faster)
@@ -668,7 +668,7 @@ extern "C" {
                 cdf[i] += ((tmp - cdf[i]) >> rate);
             }
         }
-        cdf[nsymbs] += (cdf[nsymbs] < 32);
+        cdf[nsymbs-1] += (cdf[nsymbs-1] < 32);
     }
     /**********************************************************************************************************************/
     // entropy.h
```

**Comment by joelsole** [comment]
Current code looks fine to me. Hassane, can you have a look?

Joel

**Comment by hassount** [comment]
@chkngit 
Can you please confirm that this looks good on your side ?

**Comment by chkngit** [comment]
lib aom uses the same as current code ie [2], 
update_cdf() does not seem to be called in this particilar syntax element. so LGTM

**Pull request merged**
