### PR TITLE
Fix the R2R in M2 caused by uninitialized parameters

### PR DESCRIPTION
**Pull request by lijing0010**
Signed-off-by: Jing Li <jing.b.li@intel.com>

### CODE REVIEW

**Comment by tianjunwork** [comment]
```
Fatal Error on running test case PaletteModeTest1: EncoderMode=1, PaletteMode=1, ScreenContentMode=1, test vector: screendata.y4m
cli command: SvtAv1EncApp -i screendata.y4m -enc-mode 1 -palette 1 -scm 1 -b output.ivf -o recon.yuv
[  FAILED  ] SvtAv1/ConformanceDeathTest.DefaultSettingTest/PaletteModeTest1, where GetParam() = PaletteModeTest1: EncoderMode=1, PaletteMode=1, ScreenContentMode=1,  (150209 ms)
[----------] 4 tests from SvtAv1/ConformanceDeathTest (197899 ms total)
```
Hi @lijing0010 , there is a failed unit test. Could you take a look?
And also, what is the command line to reproduce the R2R?

**Comment by tianjunwork** [comment]
Hi @lijing0010 , what is the command line to reproduce the R2R?

**Comment by lijing0010** [comment]
> Hi @lijing0010 , what is the command line to reproduce the R2R?

run in enc-mode 2, and it will have r2r, easy to reproduce

**Comment by ccccheung** [comment]
Tested on Obj-1 8-bit and 10-bit
  | Speed Deviation  | BD-Rate   Deviation
-- | -- | --
M0-8bit | 0.26% | 0.00%
M4-8bit | 0.17% | 0.00%
M8-8bit | 0.11% | 0.00%
M0-10bit | 1.30% | 0.00%
M0-10bit | 1.27% | 0.00%
M0-10bit | 1.31% | 0.00%

**Pull request merged**
