### PR TITLE
Compound mode and Film Grain support in Decoder

### PR DESCRIPTION
**Pull request by nijilk**
Added support for compound modes (InterInter and InterIntra) in Decoder.
Added support for film grain support in Decoder.
Segregated blend functions and verified encoder for bit-match.

### CODE REVIEW

**Comment by joelsole** [comment]
@1480c1 @EwoutH  - travis is not happy about the style in this PR (https://api.travis-ci.com/v3/job/234863522/log.txt).  Do you know what is the issue there?

**Comment by joelsole** [comment]
lgtm - please, address the conflicts.

**Comment by nijilk** [comment]
> lgtm
We finished resolving the conflicts and tests are going on.
Will push the changes soon.

**Comment by hassount** [comment]
@nijilk Can this be re based for merging ?

**Comment by nijilk** [comment]
> 
> 
> @nijilk Can this be re based for merging ?

@hassount 
This branch has no conflicts with base branch, rt?
Is re basing absolutely needed?

**Comment by hassount** [comment]
> > @nijilk Can this be re based for merging ?
> 
> @hassount
> This branch has no conflicts with base branch, rt?
> Is re basing absolutely needed?

@nijilk many merges to the master over the past day, asking for a rebase to avoid the risks of breaking the code. could you at least give it a quick test on the merged version ?

**Comment by nijilk** [comment]
> aster over the past day, asking for a rebase to avoid the risks of breaking the code. could you at least give it a quick t

@hassount 
Thanks for the info.
I will do a quick decoder test on the merged version and update you.

**Comment by nijilk** [comment]
> 
> 
> > aster over the past day, asking for a rebase to avoid the risks of breaking the code. could you at least give it a quick t
> 
> @hassount
> Thanks for the info.
> I will do a quick decoder test on the merged version and update you.

@hassount 
We did quick decoder test and all the streams are passing.
Looks good to merge.

**Pull request merged**
