### PR TITLE
Remove pointers arrays  1d, to remove asm_type

### PR DESCRIPTION
**Pull request by spawlows**
Phase 1 of deprecating the asm_type usage: 1d tables only

### CODE REVIEW

**Comment by spawlows** [comment]
Conflicts have removed.

**Comment by spawlows** [comment]
Please "Rebase and merge" 2 separated commits.

**Comment by mafonsoN** [comment]
@spawlows, just for clarification, is the idea to deprecate asm_type?

Because there are still function array pointers that use it in other parts of the code (e.g. pack2d_func_ptr_array_16_bit_src in EbPictureOperators.c or compute_mean_func in EbPictureAnalyzsisProcess.c)

**Comment by hassount** [comment]
> @spawlows, just for clarification, is the idea to deprecate asm_type?
> 
> Because there are still function array pointers that use it in other parts of the code (e.g. pack2d_func_ptr_array_16_bit_src in EbPictureOperators.c or compute_mean_func in EbPictureAnalyzsisProcess.c)

@mafonsoN 
This PR is to deprecate asm_type for 1d arrays, there will be another PR to deprecate asm_type from 2d arrays which is slightly more complex

**Comment by spawlows** [comment]
Hi,

@mafonsoN  Yes, this is a part of changes to deprecate asm_type. I'm working on next changes. PR is splitted, to not introduce too many conflicts in integration at the same time.

**Comment by mafonsoN** [comment]
> > @spawlows, just for clarification, is the idea to deprecate asm_type?
> > Because there are still function array pointers that use it in other parts of the code (e.g. pack2d_func_ptr_array_16_bit_src in EbPictureOperators.c or compute_mean_func in EbPictureAnalyzsisProcess.c)
> 
> @mafonsoN
> This PR is to deprecate asm_type for 1d arrays, there will be another PR to deprecate asm_type from 2d arrays which is slightly more complex

> Hi,
> 
> @mafonsoN Yes, this is a part of changes to deprecate asm_type. I'm working on next changes. PR is splitted, to not introduce too many conflicts in integration at the same time.

Thanks for the clarification. The PR looks good. But it would be nice to have this type of context in the description for every PR.

**Pull request merged**
