### PR TITLE
MinGW: Enable MinGW support

### PR DESCRIPTION
**Pull request by 1480c1**
Since #291 hasn't been updated. Closes #291

### CODE REVIEW

**Comment by 1480c1** [comment]
@kylophone, is there any issues with this pr?

**Comment by 1480c1** [comment]
Force pushed to remove conflicts with https://github.com/OpenVisualCloud/SVT-AV1/pull/581

**Comment by hassount** [comment]
@1480c1 is this ready to be merged ? rebase ?

**Comment by 1480c1** [comment]
Ready to merge as far as I know, it's already rebased to current master

**Comment by hassount** [comment]
@kylophone merging this if not issues. 
@1480c1 I still was not able to test mingw on windows, so I trust you have done the testing and that it works. I have tested that the windows build is not broken.

**Comment by moisespr123** [comment]
This has been tested as part of the Media Autobuild Suite. It builds and
runs successfully.

**Comment by hassount** [comment]
Great, thank you both, let's merge it

**Pull request merged**
