### PR TITLE
[WIP] Fix warnings for all platforms/compilers

### PR DESCRIPTION
**Pull request by mafonsoN**
WIP for fixing warnings for all platforms and compilers tested in Travis. 

Currently, all encoder warnings using gcc and most of the warnings using clang have been addressed. 

@hassount can you check the Linux clang warnings in EbAppConfig.c? 

@nijilk can you please fix the decoder warnings (Linux gcc and Linux clang)?

Some Linux gcc warnings seem to point to an out of bounds situation in the decoder (last index = ALTREF_FRAME for an array of size ALTREF_FRAME):

```c
warning: iteration 6u invokes undefined behavior [-Waggressive-loop-optimizations]

         frame_info->global_motion_params.gm_type[ref] = type;

/home/travis/build/OpenVisualCloud/SVT-AV1/Source/Lib/Decoder/Codec/EbDecParseObu.c:1209:5: note: containing loop

     for (ref = LAST_FRAME; ref <= ALTREF_FRAME; ref++) {
```

### CODE REVIEW

**Comment by nijilk** [comment]
> 
> 
> WIP for fixing warnings for all platforms and compilers tested in Travis.
> 
> Currently, all encoder warnings using gcc and most of the warnings using clang have been addressed.
> 
> @hassount can you check the Linux clang warnings in EbAppConfig.c?
> 
> @nijilk can you please fix the decoder warnings (Linux gcc and Linux clang)?
> 
> Some Linux gcc warnings seem to point to an out of bounds situation in the decoder (last index = ALTREF_FRAME for an array of size ALTREF_FRAME):
> 
> ```c
> warning: iteration 6u invokes undefined behavior [-Waggressive-loop-optimizations]
> 
>          frame_info->global_motion_params.gm_type[ref] = type;
> 
> /home/travis/build/OpenVisualCloud/SVT-AV1/Source/Lib/Decoder/Codec/EbDecParseObu.c:1209:5: note: containing loop
> 
>      for (ref = LAST_FRAME; ref <= ALTREF_FRAME; ref++) {
> ```

Hi,
Please see attached file with the fixes.

[EbDecParseObu.zip](https://github.com/OpenVisualCloud/SVT-AV1/files/3299854/EbDecParseObu.zip)

Let me know if you face any other issue.

**Comment by 1480c1** [comment]
Although not necessary, after you are done, can you do

``` bash
git reset master
git add -p
# add the individual changes per warning using y for stage change, n for don't stage, s for split change, and q for skip the rest
git commit -m "address [warning]"
...
git push -f
```

And repeat from `git add -p` To commit per warning/bug addressed
( I recommend to push everything before doing this so you can easily do `git diff upstream/master` to check )

Not really needed but would help split the changes into what warning was addressed with the certain changes + easier to bisect in the future if there is an issue later on

**Comment by nijilk** [comment]
Hi @mafonsoN ,
Please see the patch with all fixes for decoder warnings.
[0001-Fixed-decoder-build-warnings.zip](https://github.com/OpenVisualCloud/SVT-AV1/files/3314607/0001-Fixed-decoder-build-warnings.zip)

**Comment by 1480c1** [comment]
Will this be closed?

**Comment by joelsole** [comment]
Close by #418

**Pull request closed without merging**
