### PR TITLE
fixed referenced_area sb_index boundary check for 2 pass

### PR DESCRIPTION
**Pull request by kelvinhu325**
## Description
This PR is for fixing referenced_area[sb_index] boundary error, the sb_origin_x and sb_origin_y for calculating sb_index may point out of picture boundary, for example, if sb_origin_x points out of right picture boundary(sb_origin_x>=pic_width_in_sb), then sb_index gets the first SB under current SB lines, which does not make sense for referenced_area[sb_index] calculating as below code copying from av1_encode_pass() function, my PR change gives up these SBs out of picture boundary.

uint16_t origin_x = MAX(0, (int16_t)context_ptr->cu_origin_x + (context_ptr->mv_unit.mv[REF_LI
ST_0].x >> 3));
uint16_t origin_y = MAX(0, (int16_t)context_ptr->cu_origin_y + (context_ptr->mv_unit.mv[REF_LI
ST_0].y >> 3));
uint16_t sb_origin_x = origin_x / context_ptr->sb_sz * context_ptr->sb_sz;
uint16_t sb_origin_y = origin_y / context_ptr->sb_sz * context_ptr->sb_sz;
uint16_t sb_index = sb_origin_x / context_ptr->sb_sz + pic_width_in_sb * (sb_origin_y / contex
t_ptr->sb_sz);
refObj0->stat_struct.referenced_area[sb_index] += width * height * weight;

### Author
@kelvinhu325 

### Type of change
Enhancement

### Tests and performance

  | Deviation
-- | --
BD-Rate | -0.01%
Speed |

### CODE REVIEW

**Comment by hassount** [comment]
@kelvinhu325 can we get a clear description for this PR along with an idea of its performance impacts ? you can follow https://github.com/OpenVisualCloud/SVT-AV1/pull/773

**Comment by kelvinhu325** [comment]
> @kelvinhu325 can we get a clear description for this PR along with an idea of its performance impacts ? you can follow #773

Hi @hassount,  OK, I added description.

**Comment by hassount** [comment]
> > @kelvinhu325 can we get a clear description for this PR along with an idea of its performance impacts ? you can follow #773
> 
> Hi @hassount, OK, I added description.

@kelvinhu325 thank you for the description, can you please add a section for performance impacts including any addition speed / memory impacts?

**Comment by kelvinhu325** [comment]
> > > @kelvinhu325 can we get a clear description for this PR along with an idea of its performance impacts ? you can follow #773
> > 
> > 
> > Hi @hassount, OK, I added description.
> 
> @kelvinhu325 thank you for the description, can you please add a section for performance impacts including any addition speed / memory impacts?

@hassount sure, this change is mainly for functional bug fixing and slight performance impact, I could run performance tests once get them.

**Comment by kelvinhu325** [comment]
@hassount updated my change again for more accurate change, it’s easy to understand, but quality impact is still slightly, could you double check again my PR?

**Comment by hassount** [comment]
this LGTM,
@anaghdin  is this good to go from your side ?

**Comment by anaghdin** [comment]
Looks good to me

**Pull request merged**
