### PR TITLE
Improvement for cdef_find_dir_avx2 and cdef_filter_block_avx2

### PR DESCRIPTION
**Pull request by spawlows**
cdef_find_dir_avx2 is about 2.65x faster
cdef_filter_block_avx2 is about 1.1x faster

### CODE REVIEW

**Comment by EwoutH** [comment]
@hassount @kylophone What's blocking this?

**Comment by EwoutH** [comment]
@spawlows In the meantime, could you rebase and resolve the conflicts?

**Comment by spawlows** [comment]
@EwoutH I see, that part of changes from this PR are in code, under define: "#if  CDEF_AVX_OP" included in commit:  #bef675015e3d963b5a771a9b3b0d18f7f2572d30 I need more time to investigate, is this PR is still required.

**Comment by spawlows** [comment]
All changes from this PR are included in merged PR  #235 Please abort this PR.

**Comment by hassount** [comment]
@spawlows 
Can you please rebase this PR ?

**Comment by EwoutH** [comment]
@hassount What I understood is that all the changes in this PR are already in #235.

**Comment by spawlows** [comment]
Yes, please close this PR. All the changes in this PR are already in #235.

**Comment by hassount** [comment]
Part of #235

**Pull request closed without merging**
