### PR TITLE
script: redo build.sh

### PR DESCRIPTION
**Pull request by 1480c1**
Allows for custom c,cpp, and asm compiler
Allows for custom generator

### CODE REVIEW

**Comment by EwoutH** [comment]
@1480c1 Thanks for all the build related commits so far! Could you resolve the conflicts and rebase?

**Comment by 1480c1** [comment]
Sure, going to add the unit tests too

**Comment by EwoutH** [comment]
@hassount Could you assign reviewers?

**Comment by 1480c1** [comment]
WIP status right now, I found some better ways to do stuff and working on it again

**Comment by hassount** [comment]
@1480c1 what the status of this ?

**Comment by 1480c1** [comment]
Was pushed back a little trying to figure out what jstebbins was trying to do in the mingw pr. I can work on this to see if I can polish it up a little

**Comment by hassount** [comment]
Okay, no rush, just checking.

**Comment by 1480c1** [comment]
Still working on implementing some of the new stuff added recently

**Comment by 1480c1** [comment]
Ready for review. Going to test on some other computers

**Comment by 1480c1** [comment]
Works on msys2, with the exception that mingw-w64 builds are not yet fixed

**Comment by 1480c1** [comment]
Works on macOS with default stuff

**Comment by 1480c1** [comment]
@hassount, @kylophone, and any others that are good at bash scripts please review

**Comment by hassount** [comment]
this LGTM. @kylophone  ?

**Comment by hassount** [comment]
Upgrading the priority so that we can move forward

**Comment by 1480c1** [comment]
I think the script should now be a little bit more posix compatible for os without bash (alpine).

**Comment by EwoutH** [comment]
@1480c1 Could you rebase to trigger the updated Travis config?

**Comment by 1480c1** [comment]
done

**Comment by hassount** [comment]
@1480c1 
This is up next, can you check if this is still ok after the mingw support being added, rebasing might solve it

**Comment by 1480c1** [comment]
Rebased, and testing on ubuntu and msys2 (Mingw-w64 plus shell similar to cygwin) and both worked

**Comment by PhoenixWorthVCD** [comment]
Found a 1.3% speed gain, averaged over M{1,4,8} for 360p video.  No bitstream differences were found across those modes.  No memory deviations were found.

**Pull request merged**
