### PR TITLE
Fix the stability issue caused by BRC

### PR DESCRIPTION
**Pull request by lijing0010**
Signed-off-by: Jing Li <jing.b.li@intel.com>

### CODE REVIEW

**Comment by lijing0010** [comment]
Hard to reproduce, but will crash or hang after a few million frames.
Easier to reproduce on SVT-HEVC which runs faster and has the similar mechanism :)

**Comment by lijing0010** [comment]
Yes, you are right. there are 2 more places which svt-hevc doesn't have.
updated the patch

**Comment by hassount** [comment]
@anaghdin, is this good to go now ?

**Comment by anaghdin** [comment]
@hassount Yes. looks go to me. Thanks

**Pull request merged**
