### PR TITLE
Fix symbol conflicts with libaom and libopencore-amrwb

### LINKED ISSUE #567: libsvtav1 conflicts with other libraries in ffmpeg. Does not run unless they are disabled.
Hi,

I've been trying to get `libsvtav1` to run on ffmpeg built using the `media-autobuild-suite` build script. 

While it does compiles, it turns out that `libsvtav1` conflicts with `libopencore-amrwb`, `libsvthevc` and `libaom`. Disabling these libraries makes `libsvtav1` encode a video successfully.

## Conflict with `libopencore-amrwb`:
```
H:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(EbIntraPrediction.c.obj): warning: common of `pred' overridden by definition from H:/repos/media-autobuild_suite/msys64/mingw64/lib/libopencore-amrwb.a(dec_gain2_amr_wb.o)
collect2.exe: error: ld returned 1 exit status
```

## Conflict with `libsvthevc`:
```
H:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(EbModeDecisionConfiguration.c.obj):EbModeDecisionConfiguration.c:(.text+0x0): multiple definition of `MdcRefinement'; H:/repos/media-autobuild_suite/local64/lib/libSvtHevcEnc.a(EbModeDecisionConfiguration.c.obj):EbModeDecisionConfiguration.c:(.text+0x0): first defined here
H:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(EbModeDecisionConfiguration.c.obj):EbModeDecisionConfiguration.c:(.text+0x570): multiple definition of `RefinementPredictionLoop'; H:/repos/media-autobuild_suite/local64/lib/libSvtHevcEnc.a(EbModeDecisionConfiguration.c.obj):EbModeDecisionConfiguration.c:(.text+0x7a0): first defined here
H:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(EbModeDecisionConfiguration.c.obj):EbModeDecisionConfiguration.c:(.text+0x770): multiple definition of `ForwardCuToModeDecision'; H:/repos/media-autobuild_suite/local64/lib/libSvtHevcEnc.a(EbModeDecisionConfiguration.c.obj):EbModeDecisionConfiguration.c:(.text+0xc30): first defined here
H:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(EbModeDecisionConfiguration.c.obj):EbModeDecisionConfiguration.c:(.text+0x9c0): multiple definition of `MdcInterDepthDecision'; H:/repos/media-autobuild_suite/local64/lib/libSvtHevcEnc.a(EbModeDecisionConfiguration.c.obj):EbModeDecisionConfiguration.c:(.text+0xe50): first defined here
H:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(EbModeDecisionConfiguration.c.obj):EbModeDecisionConfiguration.c:(.text+0xbd0): multiple definition of `PredictionPartitionLoop'; H:/repos/media-autobuild_suite/local64/lib/libSvtHevcEnc.a(EbModeDecisionConfiguration.c.obj):EbModeDecisionConfiguration.c:(.text+0x1110): first defined here
H:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(EbModeDecisionConfiguration.c.obj):EbModeDecisionConfiguration.c:(.rdata+0x0): multiple definition of `incrementalCount'; H:/repos/media-autobuild_suite/local64/lib/libSvtHevcEnc.a(EbModeDecisionConfiguration.c.obj):EbModeDecisionConfiguration.c:(.rdata+0x0): first defined here
H:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: H:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(EbMotionEstimationContext.c.obj):EbMotionEstimationContext.c:(.text+0x130): multiple definition of `MotionEstimetionPredUnitCtor'; H:/repos/media-autobuild_suite/local64/lib/libSvtHevcEnc.a(EbMotionEstimationContext.c.obj):EbMotionEstimationContext.c:(.text+0x0): first defined here
make: *** [/build/ffmpeg-git/Makefile:111: ffmpeg_g.exe] Error 1
```

## Conflict with `libaom`:
```
Likely error:
D:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(convolve_avx2.c.obj):convolve_avx2.c:(.text+0xc90): multiple definition of `av1_build_compound_diffwtd_mask_d16_avx2'; D:/repos/media-autobuild_suite/local64/lib/libaom.a(reconinter_avx2.c.o):reconinter_avx2.c:(.text+0x350): first defined here
D:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(convolve_avx2.c.obj):convolve_avx2.c:(.text+0x1cc0): multiple definition of `av1_wedge_sse_from_residuals_avx2'; D:/repos/media-autobuild_suite/local64/lib/libaom.a(wedge_utils_avx2.c.o):wedge_utils_avx2.c:(.text+0x0): first defined here
D:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(convolve_avx2.c.obj):convolve_avx2.c:(.text+0x1da0): multiple definition of `aom_subtract_block_avx2'; D:/repos/media-autobuild_suite/local64/lib/libaom.a(subtract_avx2.c.o):subtract_avx2.c:(.text+0x0): first defined here
D:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(convolve_avx2.c.obj):convolve_avx2.c:(.text+0x20f0): multiple definition of `aom_sse_avx2'; D:/repos/media-autobuild_suite/local64/lib/libaom.a(sse_avx2.c.o):sse_avx2.c:(.text+0x0): first defined here
D:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(convolve_avx2.c.obj):convolve_avx2.c:(.text+0x27d0): multiple definition of `aom_lowbd_blend_a64_d16_mask_avx2'; D:/repos/media-autobuild_suite/local64/lib/libaom.a(blend_a64_mask_avx2.c.o):blend_a64_mask_avx2.c:(.text+0x0): first defined here
D:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(convolve_avx2.c.obj):convolve_avx2.c:(.text+0x37a0): multiple definition of `aom_sum_squares_i16_sse2'; D:/repos/media-autobuild_suite/local64/lib/libaom.a(sum_squares_sse2.c.o):sum_squares_sse2.c:(.text+0x410): first defined here
D:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(convolve_avx2.c.obj):convolve_avx2.c:(.text+0x3810): multiple definition of `av1_wedge_sign_from_residuals_avx2'; D:/repos/media-autobuild_suite/local64/lib/libaom.a(wedge_utils_avx2.c.o):wedge_utils_avx2.c:(.text+0xe0): first defined here
D:/repos/media-autobuild_suite/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:/repos/media-autobuild_suite/local64/lib/libSvtAv1Enc.a(convolve_avx2.c.obj):convolve_avx2.c:(.text+0x3910): multiple definition of `av1_wedge_compute_delta_squares_avx2'; D:/repos/media-autobuild_suite/local64/lib/libaom.a(wedge_utils_avx2.c.o):wedge_utils_avx2.c:(.text+0x1e0): first defined here
```

### PR DESCRIPTION
**Pull request by HolyWu**
# Description
#1329 only fixed the issue for dynamic library linking, but not for static library.

Conflicting functions are declared static when applicable, otherwise a prefix **eb_** is appended.

# Issue
Fixes #567

# Author(s)

# Performance impact
- [ ] quality
- [ ] memory
- [ ] speed
- [ ] 8 bit
- [ ] 10 bit
- [x] N/A

# Test set
- [ ] obj-1-fast can be found [here](https://media.xiph.org/video/derf/objective-1-fast.tar.gz)
- [ ] other
- [x] N/A

# Merge method
- [x] Allow the maintainer to squash and merge when PR is ready to create a 1-commit to the master branch. The maintainer will be able to fix typos / combine commit messages to create a more readable 1-commit message or use whatever is stated in the 'Description' section
- [ ] I will clean up my commits and the maintainer shall use 'rebase and merge' to the master branch

### CODE REVIEW

**Comment by 1480c1** [comment]
```c
/home/runner/work/SVT-AV1/SVT-AV1/Source/Lib/Common/Codec/EbCabacContextModel.c:3209:12: error: ‘av1_get_palette_color_index_context’ defined but not used [-Werror=unused-function]
 static int av1_get_palette_color_index_context(const uint8_t *color_map, int stride, int r, int c,
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

@hassount is this function used anywhere? I only see `av1_get_palette_color_index_context_optimized` being used in palette.c, but not `av1_get_palette_color_index_context`

**Comment by 1480c1** [comment]
With this PR and https://github.com/OpenVisualCloud/SVT-VP9/pull/82 applied, the list is now shorter and no longer has any conflicts with libaom

```c
/usr/bin/ld: /usr/local/lib/libSvtAv1Enc.a(EbIntraPrediction.c.o): warning: common of `pred' overridden by definition from /usr/local/lib/libopencore-amrwb.a(dec_gain2_amr_wb.o)
/usr/bin/ld: warning: alignment 8 of symbol `pred' in /usr/local/lib/libopencore-amrwb.a(dec_gain2_amr_wb.o) is smaller than 32 in /usr/local/lib/libSvtAv1Enc.a(EbIntraPrediction.c.o)
/usr/bin/ld: /usr/local/lib/libSvtHevcEnc.a(EbMalloc.c.o): in function `hash':
/SVT-HEVC/Source/Lib/Codec/EbMalloc.c:57: multiple definition of `hash'; /usr/local/lib/libSvtAv1Enc.a(EbMalloc.c.o):/SVT-AV1/Source/Lib/Common/Codec/EbMalloc.c:47: first defined here
collect2: error: ld returned 1 exit status
make: *** [/FFmpeg/Makefile:114: ffmpeg_g] Error 1
make: *** Waiting for unfinished jobs....
/usr/bin/ld: /usr/local/lib/libSvtAv1Enc.a(EbIntraPrediction.c.o): warning: common of `pred' overridden by definition from /usr/local/lib/libopencore-amrwb.a(dec_gain2_amr_wb.o)
/usr/bin/ld: warning: alignment 8 of symbol `pred' in /usr/local/lib/libopencore-amrwb.a(dec_gain2_amr_wb.o) is smaller than 32 in /usr/local/lib/libSvtAv1Enc.a(EbIntraPrediction.c.o)
/usr/bin/ld: /usr/local/lib/libSvtHevcEnc.a(EbMalloc.c.o): in function `hash':
/SVT-HEVC/Source/Lib/Codec/EbMalloc.c:57: multiple definition of `hash'; /usr/local/lib/libSvtAv1Enc.a(EbMalloc.c.o):/SVT-AV1/Source/Lib/Common/Codec/EbMalloc.c:47: first defined here
collect2: error: ld returned 1 exit status
make: *** [/FFmpeg/Makefile:114: ffprobe_g] Error 1
```

**Comment by 1480c1** [comment]
For the hash function, I do have a commit for it in one of my branches, but for pred, that will be harder since it seems it's a global 2d table declared in EbIntraPrediction.h

**Comment by 1480c1** [comment]
https://github.com/OpenVisualCloud/SVT-AV1/pull/1373 has a fix for the hash function by marking it static, none yet for pred

**Comment by hassount** [comment]
@okhlif FYI

**Comment by ccccheung** [comment]
Tested obj-1 8 bit and obj-10 bit clips  
  | Speed Deviation  | BD-Rate   Deviation | Memory Deviation
-- | -- | -- | --
M0 - 8bit | -0.24% | 0.00% | 0.02%
M4 - 8bit | -1.42% | 0.00% | 0.00%
M8 - 8bit | -0.80% | 0.00% | 0.03%
M0 - 10bit | -0.55% | 0.16% | 0.00%
M4 - 10bit | -0.64% | 0.07% | 0.02%
M8 - 10bit | -0.74% | **0.001%** | 0.00%

This PR is lossless for 8 bit but not lossless for 10 bit

**Comment by hassount** [comment]
> Tested obj-1 8 bit and obj-10 bit clips
> 
>  	Speed Deviation	BD-Rate Deviation	Memory Deviation
> M0 - 8bit	-0.24%	0.00%	0.02%
> M4 - 8bit	-1.42%	0.00%	0.00%
> M8 - 8bit	-0.80%	0.00%	0.03%
> M0 - 10bit	-0.55%	0.16%	0.00%
> M4 - 10bit	-0.64%	0.07%	0.02%
> M8 - 10bit	-0.74%	**0.001%**	0.00%
> This PR is lossless for 8 bit but not lossless for 10 bit

than kyou @ccccheung  can you give @HolyWu a few clips showing the largest difference to work with ?

**Comment by 1480c1** [comment]
Perhaps he might need to rebase on to the latest master?

**Comment by ccccheung** [comment]
The 2 clips showing the highest deviation are niklas360p_60f_10bit with a deviation of 0.54% and red_kayak_360p_60f_10bit with a deviation of 0.46%

**Comment by HolyWu** [comment]
I guess it got affected by https://github.com/OpenVisualCloud/SVT-AV1/commit/73793b03cd9d5948b5a317e68a55879eba500044. The encoded niklas360p_60f_10bit and red_kayak_360p_60f_10bit are bit identical now in my test after rebasing on to the latest master.

**Comment by hassount** [comment]
> I guess it got affected by [73793b0](https://github.com/OpenVisualCloud/SVT-AV1/commit/73793b03cd9d5948b5a317e68a55879eba500044). The encoded niklas360p_60f_10bit and red_kayak_360p_60f_10bit are bit identical now in my test after rebasing on to the latest master.

@HolyWu thank you very much for addressing this. Question: how much effort would it be to use svt_aom instead of eb_aom ?

**Comment by HolyWu** [comment]
> Question: how much effort would it be to use svt_aom instead of eb_aom ?

I need to make some things clear first.
1. There are symbols already prefixed with `eb_aom` before this PR, like [this one](https://github.com/OpenVisualCloud/SVT-AV1/blob/73793b03cd9d5948b5a317e68a55879eba500044/Source/Lib/Common/ASM_AVX2/convolve_avx2.c#L1666). Should those existing symbols be changed as well?
2. There are symbols prefixed with `eb_av1` rather than `eb_aom`. Shoud those symbols be changed to `svt_av1`?
3. There are symbols prefixed with only `eb_`, neither `eb_aom_` nor `eb_av1_`. Should those symbols be changed to `svt_`?

**Comment by hassount** [comment]
@holywu 
Iwas mainly referring to the ones changed by this PR, that said because there’s already a variety of nomenclature we can do the unification in a later stage once we agree on what would we choose as a prefix

**Comment by HolyWu** [comment]
> Iwas mainly referring to the ones changed by this PR, that said because there’s already a variety of nomenclature we can do the unification in a later stage once we agree on what would we choose as a prefix

Okay. So for now I only have to change the prefix `eb_aom_` for symbols modified in this PR and leave symbols prefixed with `eb_av1_` and `eb_` as-is, right? If so, I can work on it in a day or two.

**Comment by hassount** [comment]
> > Iwas mainly referring to the ones changed by this PR, that said because there’s already a variety of nomenclature we can do the unification in a later stage once we agree on what would we choose as a prefix
> 
> Okay. So for now I only have to change the prefix `eb_aom_` for symbols modified in this PR and leave symbols prefixed with `eb_av1_` and `eb_` as-is, right? If so, I can work on it in a day or two.

@HolyWu 
Thank you, I think then that it's best to leave this PR as is, and do this work at a later time.

**Comment by ccccheung** [comment]
Tested obj-1 8 bit and obj-10 bit clips after the rebase
  | Speed Deviation  | BD-Rate   Deviation | Memory Deviation
-- | -- | -- | --
M0 - 8bit | 1.10% | 0.00% | 0.00%
M4 - 8bit | 1.21% | 0.00% | 0.02%
M8 - 8bit | -0.12% | 0.00% | 0.01%
M0 - 10bit | 0.98% | 0.00% | 0.00%
M4 - 10bit | 1.22% | 0.00% | 0.00%
M8 - 10bit | 0.52% | 0.00% | 0.00%

This PR is now lossless for both 8 bit and 10 bit

**Pull request merged**
