### PR TITLE
Unaligned load

### PR DESCRIPTION
**Pull request by hassount**
following assembly code changed:

_mm_load_ps,
_mm_store_ps,
_mm_store_si128
_mm256_load_si256,
_mm256_store_si256,
_mm256_load_ps,
_mm256_store_ps,

enc-mode 8 and 4 tested, no obvious fps drop.

### CODE REVIEW

**Comment by hassount** [comment]
@xuguangxin Can you help rebase this branch on the cs2 branch so that we can merge it to the cs2 branch ?

**Comment by xuguangxin** [comment]
sure, I will try.

**Comment by xuguangxin** [comment]
@hassount , even without the patch. the test will crash at motion_estimate_sb. 

```
Thread 21 "SvtAv1E2ETests" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff98900700 (LWP 10970)]
0x00007ffff3ee16c5 in motion_estimate_sb (pcs_ptr=0x7fffff430010, sb_index=2, sb_origin_x=128, sb_origin_y=0, context_ptr=0x116c39a0, input_ptr=0x104ae490)
    at /home/thomas/codec/SVT-AV1/Source/Lib/Encoder/Codec/EbMotionEstimation.c:12550
warning: Source file is more recent than executable.
12550                   pcs_ptr->me_results[sb_index]->me_candidate[pu_index][cand_index].distortion =
(gdb) bt
#0  0x00007ffff3ee16c5 in motion_estimate_sb (pcs_ptr=0x7fffff430010, sb_index=2, sb_origin_x=128, sb_origin_y=0, context_ptr=0x116c39a0, input_ptr=0x104ae490)
    at /home/thomas/codec/SVT-AV1/Source/Lib/Encoder/Codec/EbMotionEstimation.c:12550
#1  0x00007ffff3ee59ad in motion_estimation_kernel (input_ptr=0x1167f5e0) at /home/thomas/codec/SVT-AV1/Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c:884
#2  0x00007fffe7de76db in start_thread (arg=0x7fff98900700) at pthread_create.c:463
#3  0x00007fffe71b188f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by hassount** [comment]
> @hassount , even without the patch. the test will crash at motion_estimate_sb.
> 
> ```
> Thread 21 "SvtAv1E2ETests" received signal SIGSEGV, Segmentation fault.
> [Switching to Thread 0x7fff98900700 (LWP 10970)]
> 0x00007ffff3ee16c5 in motion_estimate_sb (pcs_ptr=0x7fffff430010, sb_index=2, sb_origin_x=128, sb_origin_y=0, context_ptr=0x116c39a0, input_ptr=0x104ae490)
>     at /home/thomas/codec/SVT-AV1/Source/Lib/Encoder/Codec/EbMotionEstimation.c:12550
> warning: Source file is more recent than executable.
> 12550                   pcs_ptr->me_results[sb_index]->me_candidate[pu_index][cand_index].distortion =
> (gdb) bt
> #0  0x00007ffff3ee16c5 in motion_estimate_sb (pcs_ptr=0x7fffff430010, sb_index=2, sb_origin_x=128, sb_origin_y=0, context_ptr=0x116c39a0, input_ptr=0x104ae490)
>     at /home/thomas/codec/SVT-AV1/Source/Lib/Encoder/Codec/EbMotionEstimation.c:12550
> #1  0x00007ffff3ee59ad in motion_estimation_kernel (input_ptr=0x1167f5e0) at /home/thomas/codec/SVT-AV1/Source/Lib/Encoder/Codec/EbMotionEstimationProcess.c:884
> #2  0x00007fffe7de76db in start_thread (arg=0x7fff98900700) at pthread_create.c:463
> #3  0x00007fffe71b188f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
> ```

Thank you @xuguangxin,
it's a known issue it will be fixed as soon as possible

**Pull request closed without merging**
