### PR TITLE
FFmpeg Plugin: Improve sample cmdlines in README

### PR DESCRIPTION
**Pull request by jsunintel**
"-preset 1" is slow and not recommended, so to be removed.

### CODE REVIEW

**Comment by jsunintel** [comment]
@hassount please review this and thanks.

**Comment by 1480c1** [comment]
For future reference, if the commit is related to documentation and no code is modified, you can add\
 `[ skip ci ]` somewhere in the commit message to stop travis from creating jobs.

**Comment by jsunintel** [comment]
@hassount @tianjunwork This is a minor change. Would you please review and merge it if no concern?

**Comment by jsunintel** [comment]
> [ skip ci ]

Thanks for the tip.

**Pull request merged**
