### PR TITLE
Fix assembly implementation of sad_loop_kernel_sparse

### PR DESCRIPTION
**Pull request by Cidana-Developers**
1. add c implementation
2. enable sparse loop for all the block size, currently
   the sparse loop is enabled only when width is 16 and height
   is less than or equal to 16.

### CODE REVIEW

**Comment by Cidana-Developers** [comment]
> Could you please add unit test between C and assembly?

The unit test is added in PR #412 FYI.

**Comment by hassount** [comment]
@Cidana-Developers 
seems that this is ready to be merged, can you please rebase >?

**Comment by Cidana-Developers** [comment]
> @Cidana-Developers
> seems that this is ready to be merged, can you please rebase >?
Sure, I also removed c implementation to avoid potential conflicts since its included in PR #412.

**Comment by hassount** [comment]
@ttrigui can we make sure to integrate this in m0-test

**Pull request merged**
