### PR TITLE
Fix: EbSvtAv1EncConfiguration.enable_manual_pred_struct is not set to EB_FALSE by default 

### PR DESCRIPTION
**Pull request by RidgeSTD**
#1245 issue fixed, tiny fixing by setting enable_manual_pred_struct to EB_FALSE

### CODE REVIEW

**Comment by tianjunwork** [comment]
Hi @RidgeSTD , please have a descriptive PR title to the issue itself.

**Comment by RidgeSTD** [comment]
> Hi @RidgeSTD , please have a descriptive PR title to the issue itself.

Sure, done.

**Comment by mazharaIntel** [comment]
Tested with 2 clips from each resolutions. 6 - 8bit and 6 10bit clips:

  | Speed Deviation | BD-Rate Deviation 
-- | -- | -- 
M0  (8bit) | -0.28% |  0.00% |  
M0   (10bit) | -0.85% | 0.00% |

**Comment by tianjunwork** [comment]
Hi @OmranAbdelkafi , this PR is updated. I think it will not affect the test result. Do you need to rerun the test?

**Comment by OmranAbdelkafi** [comment]
> Hi @OmranAbdelkafi , this PR is updated. I think it will not affect the test result. Do you need to rerun the test?

hi @tianjunwork ; we will run some sanity checks and let you know if everything is good to go

**Pull request merged**
