### PR TITLE
appveyor: Fix artifacts

### LINKED ISSUE #425: Appveyor artifcts
@1480c1 
starting from this commit / PR #276, Appveyor does not upload any artifacts after the build, any thoughts ?

_Originally posted by @hassount in https://github.com/OpenVisualCloud/SVT-AV1/pull/276#issuecomment-507819775_

### PR DESCRIPTION
**Pull request by 1480c1**
Fixes #425 
Not ideal, should be fixed CMake side, but due to CMake and multi config generators, I'm unable to force it  to be set properly

### CODE REVIEW

**Comment by EwoutH** [comment]
This PR does way more:

- Switches from Yasm to Nasm
- Switches from MSBuild to CMake

Do you have any idea if there is a performance impact of those changes? It would be good to do some testing before making them.

**Comment by 1480c1** [comment]
I could switch back to using task, I'm only using nasm since it's easier to maintain is it's using chocolatey (yasm is outdated on choco) 

calling cmake --build with call msbuild in the background

**Comment by hassount** [comment]
@1480c1 thank you for the work around, could you please restrict the changes to addressing the appveyor artifacts, then we can propose / evaluate the nasm changes in another PR

**Comment by 1480c1** [comment]
Sure, once I'm on a computer

**Comment by 1480c1** [comment]
Done

**Comment by hassount** [comment]
thnx @1480c1

**Pull request merged**
