### PR TITLE
Cmakelists: redo the lists.

### LINKED ISSUE #40: Add option to disable binaries
It should be possible to build the library alone without the other executable tools.

### LINKED ISSUE #74: Debug build fails on Linux with NASM
```
$ cmake -GNinja -DCMAKE_BUILD_TYPE=Debug .
$ ninja
[...]
FAILED: Source/Lib/ASM_SSE2/CMakeFiles/ASM_SSE2.dir/EbPictureOperators_SSE2.asm.o
/usr/bin/nasm -ISource/API -ISource/Lib/Codec -ISource/Lib/C_DEFAULT -ISource/Lib/ASM_SSE2 -DUNIX64 -g null -f elf64 -o Source/Lib/ASM_SSE2/CMakeFiles/ASM_SSE2.dir/EbPictureOperators_SSE2.asm.o Source/Lib/ASM_SSE2/EbPictureOperators_SSE2.asm
null: fatal: more than one input file specified: Source/Lib/ASM_SSE2/EbPictureOperators_SSE2.asm
ninja: build stopped: subcommand failed.
```

### PR DESCRIPTION
**Pull request by 1480c1**
Fixes #74. Closes #40 

Should I split this one? Most of the lists are interconnected and as such it would be hard to split this one into chunks.

### CODE REVIEW

**Comment by 1480c1** [comment]
I tried making it so that it will reproduce the same behavior as previously except on some stuff such as msvc flags only being set to `/MP` and matching system names

**Comment by 1480c1** [comment]
Warning to anyone, I probably will be force-pushing this a lot since I might need to edit a previous commit etc

**Comment by hassount** [comment]
@1480c1 
Thank you for your work here, would you say this is at a stage where it would get reviewed for adoption or do you think you'd be making more changes?

**Comment by 1480c1** [comment]
For now, I think it's ready for adoption

**Comment by 1480c1** [comment]
If there is anything that might be lacking or incorrect, please do review the changes

**Comment by 1480c1** [comment]
I'll relook into how to generate xcode files that work with assembly files

**Comment by EwoutH** [comment]
@hassount Could you assign reviewers?

**Comment by 1480c1** [comment]
Fixed problem of libSvtAv1Dec.so not appearing in the right place, added `BUILD_APPS` variable to disable including of the DecApp and EncApp CMakeLists (Disabling processing of the list and building of the Apps)

**Comment by 1480c1** [comment]
With `BUILD_APPS` on, only the libs appear in the Bin directory

**Comment by 1480c1** [comment]
I still need to confirm if its the same results as the static build commit

**Comment by 1480c1** [comment]
Consider unfinished for now

**Comment by EwoutH** [comment]
Latest commit builds (with a lot of warnings though) and encodes fine, and resolves #295!

**Comment by 1480c1** [comment]
> Latest commit builds (with a lot of warnings though) and encodes fine, and resolves #295!

That's nice, It fails for me at test/CMakeFiles/SvtAv1UnitTests.dir/BitstreamReaderMock.cc.o on both my 18.04 ubuntu and macOS with `error: ‘OD_EC_WINDOW_SIZE’ was not declared in this scope` so I need to find why

**Comment by EwoutH** [comment]
The fact that every single SIMD extension has it's own CMakeLists seems a bit excessive though.

**Comment by 1480c1** [comment]
> The fact that every single SIMD extension has it's own CMakeLists seems a bit excessive though.

I did have a version in a previous branch that combined all of them, compiling them properly and then linking them to a library, I might see if I can just do that.

**Comment by 1480c1** [comment]
Working on this in a separate branch for now, going to clean up in that branch once I'm done and move the changes to this branch

**Comment by 1480c1** [comment]
I believe it's now ready.

**Comment by 1480c1** [comment]
Actually, it's failing to link EbAppProcessCmd stuff due to external symbol to EbTime stuff

**Comment by 1480c1** [comment]
I found why... There are two EbTime.h, one in EncApp and one in Common/Codec, but the one in EncApp does not have the functions prefixed with Eb.

**Comment by 1480c1** [comment]
Nevermind, I needed to change the EbAppProcessCmd

**Comment by 1480c1** [comment]
Once the tests pass, this should be ready for review.

**Comment by 1480c1** [comment]
I still have more ideas for making the cmakelists better, but I will put those in another PR.

**Comment by 1480c1** [comment]
For some reason, msvc isn't liking the -O2 flag. Going to try /O2

**Comment by hassount** [comment]
@tianjunwork @jsunintel 
Any issues with these changes ?

**Comment by 1480c1** [comment]
Setting O2 and Od for Msvc since it fails to properly check the flag.

**Comment by EwoutH** [comment]
Can this get reviewed and merged?

**Comment by tianjunwork** [comment]
> @tianjunwork @jsunintel
> Any issues with these changes ?
ffmpeg and gst plugin build is covered by travis. I read the travis log, plugin is built successfully.

**Comment by 1480c1** [comment]
@tianjunwork, are gstreamer plugins always built shared? I haven't checked any others yet

**Comment by jsunintel** [comment]
FFmpeg gets built both shared or static, under different circumstances. Please support both.

**Comment by 1480c1** [comment]
Both should be supported since both .so and .a will be outputted as 'libSvtAv1Enc' and as long as underlying code still works

**Comment by 1480c1** [comment]
I might later add a Travis job to test static and shared ffmpeg for svt-av1

**Comment by tianjunwork** [comment]
> @tianjunwork, are gstreamer plugins always built shared? I haven't checked any others yet

Yes, gst plugin always built shared.

**Comment by 1480c1** [comment]
Fixed conflicts in test/* cmakelists

**Comment by 1480c1** [comment]
It seems appveyor is having connection problems(?)

**Comment by 1480c1** [comment]
Anymore changes, questions, or requests? If not please decide to merge or not since it's getting harder and harder to rebase/merge properly

**Comment by EwoutH** [comment]
@kylophone @hassount @joelsole Please review with some priority.

**Comment by 1480c1** [comment]
I will rebase once I'm on a computer. My mobile git client is having trouble rebasing

**Comment by 1480c1** [comment]
rebased

**Comment by 1480c1** [comment]
rebased again

**Comment by EwoutH** [comment]
@kylophone @hassount @joelsole This is getting kind of sad.

**Comment by hassount** [comment]
@tianjunwork @jsunintel

**Comment by hassount** [comment]
@1480c1 
starting from this commit / PR, Appveyor does not upload any artifacts after the build, any thoughts ?

**Comment by 1480c1** [comment]
Due to ude CMAKE_BUILD_TYPE being set to 'Release;Debug', the binaries are located in 'bin/Release/Debug' probably

**Pull request merged**
