### PR TITLE
Annex-B support in Decoder and Intrinsic Fixes

### PR DESCRIPTION
**Pull request by nijilk**
Added support for Annex-B streams in Decoder.
Changed few of the aligned stores to unaligned stores based on the buffer alignment requirement.

### CODE REVIEW

**Comment by nijilk** [comment]
@joelsole @hassount
Please review

**Comment by hassount** [comment]
@ttrigui 
are we ok with the use of unaligned instructions in this case ?

**Comment by nijilk** [comment]
> 
> 
> lgtm - I get less mismatches. Currently, the following 49 dav1d 8-bit streams are mismatching for me:
> 
> decoder_SVTAV1/dav1d-test-data/8-bit/features/rgb.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/resize/av1-1-b8-03-sizeup.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/resize/av1-1-b8-03-sizedown.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00000756.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00001138.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00001105.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00000757.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00000755.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00000754.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00001102.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00000751.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00000753.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00001101.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00000752.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00000709.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00000669.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00000641.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00000640.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00000668.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00000708.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00000642.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00000643.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00000647.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00000646.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00000644.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00000645.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00000714.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00000661.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00000715.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00000663.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00000662.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00000712.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00000706.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00000666.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00000667.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00000707.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00000713.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00000711.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00000665.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00000664.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00000670.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00000710.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00001131.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00001130.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00000760.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00001133.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00000759.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00000758.ivf
> decoder_SVTAV1/dav1d-test-data/8-bit/data/00001135.ivf

@joelsole 
We will look into these mismatches.

**Comment by ttrigui** [comment]
> @ttrigui
> are we ok with the use of unaligned instructions in this case ?

yes. lgtm

**Comment by joelsole** [comment]
> > lgtm - I get less mismatches. Currently, the following 49 dav1d 8-bit streams are mismatching for me:
> > decoder_SVTAV1/dav1d-test-data/8-bit/features/rgb.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/resize/av1-1-b8-03-sizeup.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/resize/av1-1-b8-03-sizedown.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00000756.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00001138.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00001105.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00000757.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00000755.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00000754.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00001102.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00000751.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00000753.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00001101.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00000752.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00000709.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00000669.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00000641.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00000640.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00000668.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00000708.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00000642.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00000643.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00000647.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00000646.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00000644.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00000645.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00000714.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00000661.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00000715.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00000663.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00000662.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00000712.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00000706.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00000666.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00000667.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00000707.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00000713.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00000711.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00000665.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00000664.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00000670.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00000710.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00001131.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00001130.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00000760.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00001133.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00000759.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00000758.ivf
> > decoder_SVTAV1/dav1d-test-data/8-bit/data/00001135.ivf
> 
> @joelsole
> We have tried testing these streams on our side and they are matching (on both Windows and Linux AVX2 machines).
> Can you share the machine details you used for testing?

Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
System Version: macOS 10.14.6 (18G103)
Kernel Version: Darwin 18.7.0

**Comment by joelsole** [comment]
ok, I was doing a wrong conversion. My mistake.

We can proceed to merge this PR.

**Pull request merged**
