### PR TITLE
Add AppVeyor CI/CD

### PR DESCRIPTION
**Pull request by EwoutH**
Part of #4.

This PR adds continuous integration & delivery with AppVeyor. SVT-AV1 gets build with Microsoft Visual Studio 2017 and Yasm 1.3.0. AppVeyor publishes `SvtAv1Enc.dll`, `SvtAv1Enc.exp`, `SvtAv1Enc.lib`, `SvtAv1EncApp.exe` and `SvtAv1EncSimpleApp.exe` in the Artifacts tab ([example](https://ci.appveyor.com/project/EwoutH/svt-av1/build/artifacts)).

AppVeyor needs to be enabled on the [GitHub Marketplace](https://github.com/marketplace/appveyor) or on [ci.AppVeyor.com](https://ci.appveyor.com/project/OpenVisualCloud/SVT-AV1).

When enabled, AppVeyor publishes the artifacts with each build. When tagging a new (pre)release, AppVeyor will also upload these files to GitHub, creating a release page [like this](https://github.com/EwoutH/SVT-AV1/releases/tag/0.0.1-test1).

To enable uploading to GitHub Releases, a maintainer needs to update this patch with his personal authentication token. You can generate one on https://github.com/settings/tokens/new (select `public_repo` as scope), and then encrypt it with https://ci.appveyor.com/tools/encrypt. Replace the current token on line 21 (after `secure:`) in the `appveyor.yml` file.

### CODE REVIEW

**Comment by kylophone** [comment]
Great, I'll check this out.

**Comment by EwoutH** [comment]
@kylophone Anything that blocks this PR? Otherwise you can update the token and merge.

**Comment by kylophone** [comment]
I needed some help from an admin to configure Github organization auth. That's done, so this will probably be merged today.

**Comment by EwoutH** [comment]
Resolved the conflict in Readme.md between the AppVeyor and Travis badges.

**Pull request merged**
