### PR TITLE
Performance improvement changes for AVX dr prediction

### PR DESCRIPTION
**Pull request by Zvictoria**
Performance improving changes for AVX dr prediction functions done for AOM initially and replicated for SVT. Up to 2x speedup fro z2 functions

### CODE REVIEW

**Comment by kylophone** [comment]
> This time only relevant changes committed

Thanks for the clean up!

**Comment by kylophone** [comment]
Did you copy some libaom code? If so, make sure you add the libaom header to the file.

**Comment by kodabb** [comment]
this is a good step in the right direction, but there are still a lot of cosmetic changes mixed in code changes, especially in the tables section, i'd recommend to split them out. Also what's the point of having two giant commits? just amend the changes in one IMO

**Comment by hassount** [comment]
@spawlows 
Could you please review this PR ?

**Comment by Zvictoria** [comment]
@kylophone , @kodabb the whole story is - I'm the original author of all AVX2 directional prediction code - this code has been submitted by me to AOM and reused by SVT team with all legal procedures in place. But since that time I've made some improvements into AOM code - both performance and code style related, so now it is time to merge them into SVT. 
I don't think it makes sense to split them into "cosmetic" and "speedup" parts - it takes time and there are not much cosmetic changes actually. All I could try doing is merging 2 commits into the single one somehow ...

**Comment by spawlows** [comment]
@Zvictoria : Changes looks fine. Just merge them into one commit, to keep more readable history.

**Comment by Zvictoria** [comment]
@spawlows , any hints for pull request commits merging are welcome. Is there any github ui for the purpose? Or am I supposed to do it locally and then resubmit to the same pull request? to be honest all this PR process looks totally new to me. Sorry... Probably it is possible to squash &  merge this PR into the master as a single commit as https://help.github.com/en/articles/about-pull-request-merges tells?

**Comment by spawlows** [comment]
@Zvictoria, from that I know, person who accept PR can merge this. I personally propose to do it local and push on your branch "Zvictoria:aom_dr_AVX" with --force. then this PR will be updated automatically. ('git reset HEAD^' then 'git gui', 'amend last commit' and add local changes, then 'push' and check 'Force')

**Comment by kylophone** [comment]
Squashing can also be done from the Github UI when merging.

**Comment by kodabb** [comment]
> @Zvictoria : Changes looks fine. Just merge them into one commit, to keep more readable history.
> Squashing can also be done from the Github UI when merging.

apologies if i sound like the old man yelling at clouds, but please don't do either of those things:
- "merge" makes history untidy as you need to check a whole direfferent branch tree and "merge commits" become huge code changes that are barely noticeable
- "squash" makes the commit unusable on an any platform that is not github, or even from the command line

my advise would: from your branch, `git rebase -i master`, change the second "pick" with "fixup", then `git push -f <remote> <branch>`

>  I don't think it makes sense to split them into "cosmetic" and "speedup" parts - it takes time and there are not much cosmetic changes actually. All I could try doing is merging 2 commits into the single one somehow ...

yes everybody believes that it does not make any sense until you need to debug something that is not your code and becomes impossible to bisect. Please spend that time for the sake of the community that will have to maintain your code while you will be not interested in it any more

**Comment by Zvictoria** [comment]
@kodabb, ok, I will try making it clean from the very beginning - to close this PR and open it with a new fresh cool commit. 
and as for cosmetic / meaningful changes   separation - here you are not right because cosmetic is the thing no one needs to debug by definition :) it is just about code formatting.

**Comment by kodabb** [comment]
> here you are not right because cosmetic is the thing no one needs to debug by definition :) it is just about code formatting.

...that's exactly why the cosmetic change should be a separate commit, to make the actual functional change easier to triage and debug, and not lost in a thousand whitespace changes...

**Pull request closed without merging**
