### PR TITLE
cmake: use a prefix for the common libraries

### PR DESCRIPTION
**Pull request by ihalip**
Should fix [SVT-HEVC/212](https://github.com/OpenVisualCloud/SVT-HEVC/issues/212).

### CODE REVIEW

**Comment by kylophone** [comment]
Great, thanks. I wonder if `SVT_AV1` might be a better prefix? Does anyone have a preference?

**Comment by 1480c1** [comment]
Probably better to use SVT_AV1

**Comment by tianjunwork** [comment]
Hi @ihalip, LGTM. Thank you.
Could you resolve the conflict here and change the prefix to SVT_AV1/VP9/HEVC, then I will proceed with merging.

**Comment by kylophone** [comment]
Closing this, these will be resolved by an upcoming PR.

**Pull request closed without merging**
