### PR TITLE
Fix build error

### PR DESCRIPTION
**Pull request by joelsole**
clang version 3.8.0-2ubuntu4

### CODE REVIEW

**Comment by hassount** [comment]
@tianjunwork 
Should we add an Warning or something more informative, or a simple return is fine ?

**Comment by joelsole** [comment]
Still giving errors on Travis after the modification in this PR:
https://travis-ci.com/OpenVisualCloud/SVT-AV1/jobs/181458390

Related to PR#103:

In file included from EbSequenceControlSet.h:21:
/Source/Lib/Codec/EbThreads.h:116:11: error: unknown type name 'cpu_set_t'
extern    cpu_set_t                   group_affinity;
          ^
1 error generated.

**Comment by 1480c1** [comment]
Yea, it's cause cpu_set_t does not exist on Mac, nor does the pthread stuff bellow.

**Comment by tianjunwork** [comment]
https://github.com/tianjunwork/SVT-AV1/commits/build_fix
Sorry for the inconvenience, I add a fix in my fork branch.
@joelsole do you want to continue with this PR, or I create a new one from mine?

**Comment by joelsole** [comment]
Please, go ahead with another PR fixing the MacOs issues. Thanks.

**Pull request closed without merging**
