### PR TITLE
Preset Optimization and Code Cleanup

### PR DESCRIPTION
**Pull request by hassount**
**Description of changes**
+ update preset trade-offs 1,2,3 increased speed by 2x
  + optimize interpolation filter use
  + optimize dlf
+ add infra-structure for features to be turned on/off localized per kernel depending on the processing stage (block based / picture based)  
+ cleanup extra compile macros
+ some snake_case cleanup
+ cleanup tabs / trailing spaces

**Authors:**
@NaderMahdi
@okhlif

### CODE REVIEW

**Comment by kylophone** [comment]
lgtm.

**Comment by singhkays** [comment]
@hassount Does this have any speed impact on encoder mode 0?

**Comment by hassount** [comment]
> @hassount Does this have any speed impact on encoder mode 0?
@singhkays no speed change for mode 0 yet

**Comment by singhkays** [comment]
@hassount got it, thanks!

**Pull request merged**
