### PR TITLE
packetization_kernel: fix missed last frame

### PR DESCRIPTION
**Pull request by xuguangxin**
we will miss last frame if it is a show existing frame

test command line:
-i blue_sky_360p_60f.yuv -o rec.yuv -intra-period 200 -enc-mode 8 -n 25 -q 40 -lp 1 -lad 0 -b 1.ivf -w 640 -h 360

### CODE REVIEW

**Comment by xuguangxin** [comment]
@hassount I tried 3 times to make this pass all build.
seems we have random failure for unit test.
see https://github.com/OpenVisualCloud/SVT-AV1/pull/1093/checks?check_run_id=469724506 for details.

**Comment by EricLamVCD** [comment]
A total of 12 clips at 5 qp's each were tested. They were tested with -n 25 frames and -n 49 frames for 2 random clips for each resolution at 8 bit and 10 bit. 

The encoder worked fine for -n 25 and -n 49.

**Comment by hassount** [comment]
> lgtm - maybe the two comments are not necessary and then, the braces of the two if statements with them can be removed as per the style guidelines.

@xuguangxin could you please address the above comments

**Comment by xuguangxin** [comment]
thanks joelsole and hassount for help on this

**Pull request merged**
