### PR TITLE
Fix avx512 build

### PR DESCRIPTION
**Pull request by ttrigui**
Fix build error when enabling AVX512

### CODE REVIEW

**Comment by 1480c1** [comment]
@ttrigui, do you use command line git?

**Comment by JackZhouVCD** [comment]
lgtm

**Comment by ttrigui** [comment]
> @ttrigui, do you use command line git?

no I used tortoise git. Created a different PR [https://github.com/OpenVisualCloud/SVT-AV1/pull/670](url)

**Comment by hassount** [comment]
#670

**Pull request closed without merging**
