### PR TITLE
Github Actions CI: Add build matrix

### PR DESCRIPTION
**Pull request by ePirat**
Add a build matrix to test compilation on various compilers.

Additionally set an explicit name for the build machine, so that it is clear on which OS version it runs.

### CODE REVIEW

**Comment by hassount** [comment]
@ePirat Thank you for the contribution. This LGTM

@1480c1 @EwoutH @kylophone any issues with this, the plan is to expand on github actions and hook up external instances

**Comment by 1480c1** [comment]
Looks good to me



> @1480c1 @EwoutH @kylophone any issues with this, the plan is to expand on github actions and hook up external instances

That would be great, that means we can finally control the CPU and ram and test further than just two video files

**Comment by EwoutH** [comment]
LGTM, nice work

**Comment by hassount** [comment]
@kylophone merging assuming no issues

**Comment by 1480c1** [comment]
> the plan is to expand on github actions and hook up external instances

Will this apply to the other SVT encoders or just SVT-AV1 for now?

**Comment by hassount** [comment]
> > the plan is to expand on github actions and hook up external instances
> 
> Will this apply to the other SVT encoders or just SVT-AV1 for now?

This is planned for svt-av1 for now.

**Pull request merged**
