### PR TITLE
Prep 0.7.0 tag

### PR DESCRIPTION
**Pull request by hassount**
Update CHANGELOG.md and version number for 0.7.0 tag

### CODE REVIEW

**Comment by EwoutH** [comment]
Great progress, thanks for taking the feedback in #29 in account!

Could we merge some build issues before release? That will make integration with other applications significantly easier. #558 is very important for Handbrake (see https://github.com/HandBrake/HandBrake/issues/2313) and #254 and #554 should make the build process more stable. 

Also merging #620 before release will prevent a lot of bug reports.

Furthermore, I think the bugfixes #615 and #618 should be merged before a tag, and #538 should be looked into.

I would still suggest creating a [Milestone](https://github.com/OpenVisualCloud/SVT-AV1/milestones) for 0.7.0 so that the appropriate PRs and issues can be tracked. It will help greatly in the effort for #238.

**Comment by 1480c1** [comment]
Make sure to update the cmakelists in the decoder and encoder folders

**Comment by 1480c1** [comment]
Alternatively, we can make it so that either the API header is updated from cmake or cmake reads from the header

**Comment by EwoutH** [comment]
Would also be super useful to get an Constrained Quality (CQ) rate-control mode in (see #343).

**Comment by hassount** [comment]
@EwoutH 
Thank you for the feedback, so we have:

- [ ] #558 
- [ ] #554 
- [ ] #254 
- [ ] #620 
- [ ] #615
- [ ] #618  

#538 will probably not be fixed by 0.7. Adding milestones, will be working on moving away from trello and adding milestones.

@1480c1 
my understanding is that the SVT_VERSION_MAJOR, SVT_VERSION_MINOR, SVT_VERSION_PATCHLEVEL are shared between the encoder and the decoder and so both libraries will be updated accordingly. Can you explain further what you are suggesting to be done ? or if you have some time, suggest the change so that we are on the same page.

**Comment by 1480c1** [comment]
What I meant was
``` diff
diff --git a/Source/Lib/Decoder/CMakeLists.txt b/Source/Lib/Decoder/CMakeLists.txt
index edbd830d..f94b5ec4 100644
--- a/Source/Lib/Decoder/CMakeLists.txt
+++ b/Source/Lib/Decoder/CMakeLists.txt
@@ -6,7 +6,7 @@
 
 # Shared Decoder Version
 set(DEC_VERSION_MAJOR 0)
-set(DEC_VERSION_MINOR 6)
+set(DEC_VERSION_MINOR 7)
 set(DEC_VERSION_PATCH 0)
 set(DEC_VERSION ${DEC_VERSION_MAJOR}.${DEC_VERSION_MINOR}.${DEC_VERSION_PATCH})
 
diff --git a/Source/Lib/Encoder/CMakeLists.txt b/Source/Lib/Encoder/CMakeLists.txt
index 2dc14385..6a5b58ba 100644
--- a/Source/Lib/Encoder/CMakeLists.txt
+++ b/Source/Lib/Encoder/CMakeLists.txt
@@ -6,7 +6,7 @@
 
 # Shared Encoder Version
 set(ENC_VERSION_MAJOR 0)
-set(ENC_VERSION_MINOR 6)
+set(ENC_VERSION_MINOR 7)
 set(ENC_VERSION_PATCH 0)
 set(ENC_VERSION ${ENC_VERSION_MAJOR}.${ENC_VERSION_MINOR}.${ENC_VERSION_PATCH})
 ```

to update the cmakelists and so that way the pkg-config file will be properly updated

**Comment by 1480c1** [comment]
Alternatively, I can try to see if I can make CMake to pull the version number from EbSvtAv1.h and set the version that way, or do in reverse and have CMake generate the EbSvtAv1.h with the version number set in CMakeLists

**Comment by hassount** [comment]
> Alternatively, I can try to see if I can make CMake to pull the version number from EbSvtAv1.h and set the version that way, or do in reverse and have CMake generate the EbSvtAv1.h with the version number set in CMakeLists

Thanks, that would be ideal, that said, if it takes too much time, we can change it for now and add the functionality later, what do you suggest ?

**Comment by 1480c1** [comment]
I would say go ahead and make the change, as it may take some time before I can fully make sure which way is better

**Comment by EwoutH** [comment]
@hassount List looks good, the SVT-AV1 build system is shaping up nicely! Would be nice to get #162, #634 and #635 also in.

**Comment by EwoutH** [comment]
@hassount Thanks for updating the list. GitHub has a very nice feature built in, called [Milestones](https://github.com/OpenVisualCloud/SVT-AV1/milestones), where you can assign issues and PRs you want to get fixed/implemented before a specific release. For a better overview, you could create a milestone for 0.7.0.

**Comment by joelsole** [comment]
> @joelsole
> All ready to merge, can you do a quick review ?

lgtm

**Pull request merged**
