### PR TITLE
Fix the r2r which is caused by tx search in encdec

### PR DESCRIPTION
**Pull request by lijing0010**
Signed-off-by: Jing Li <jing.b.li@intel.com>

### CODE REVIEW

**Comment by lijing0010** [comment]
it will cause r2r in M5

**Comment by JackZhouVCD** [comment]
I just checked through all of the clips from the objective-fast-1 test set running M5 and the existing r2r issue is addressed by this PR. Thanks for adding this fix!

**Comment by lijing0010** [comment]
add macro protection and rebase to latest

**Comment by joelsole** [comment]
@lijing0010 could you squash the two commits and we can push this fix to master. Thanks.

**Comment by lijing0010** [comment]
@joelsole , rebased to the latest and squash into one commit

**Pull request merged**
