### PR TITLE
Fix R2R in non-8 aligned resolution streams

### PR DESCRIPTION
**Pull request by lijing0010**
Signed-off-by: Jing Li <jing.b.li@intel.com>

### CODE REVIEW

**Comment by tianjunwork** [comment]
Hi @lijing0010 , if it is to fix a bug, why use Macro around the fix? Is it related to dev process?

**Comment by lijing0010** [comment]
> Hi @lijing0010 , if it is to fix a bug, why use Macro around the fix? Is it related to dev process?

yeah, I put all my changes into a macro in case someone want to debug on regression related issues.
Also helps to cherry-pick between branches. 
But will make the code a bit hard to read. anyway I think we may clean up those macros when achieve some stable version or a release

**Comment by tianjunwork** [comment]
I see, thank you Jing.

**Comment by EricLamVCD** [comment]
Tested 12 random clips with mixed resolutions of 6 - 8bit and 6 10bit clips: 
  | Speed Deviation  | BD-Rate   Deviation
-- | -- | --
Tested | -0.39% | 0.00%

**Comment by lijing0010** [comment]
> can you please explain the problem ?

@chkngit . It's caused by padding. 
For non-8 aligned bitstreams, we need to:
1) first padding to 8-aligned
2) then padding around(128+32 pixels).
However in previous implementations, some part forgot to do padding 1), or did 2) before 1).

**Comment by tianjunwork** [comment]
Hi @chkngit , is this PR good to go?

**Comment by chkngit** [comment]
@lijing0010  could you please review related PR #1263 as it seems related to this, and port this fix to svt-01 and svt_av1_2020_04_25 branch?

**Pull request merged**
