### PR TITLE
Adding unit testing framework

### PR DESCRIPTION
**Pull request by andrey-norkin**
1. Added Google Test framework
2. Added a unit test example

### CODE REVIEW

**Comment by kylophone** [comment]
@hassount, Does the VS error message in the appveyor build look familiar to you? We don't have any Windows machines to reproduce.

**Comment by hassount** [comment]
@kylophone 
The windows error message is due to warnings in the test project and for that file all warnings are considered errors. so we should probably try to address all warnings and enable the -Werror flag every where.

**Comment by andrey-norkin** [comment]
@hassount Yes, there are warnings on Windows on the test project and in a couple of other places. The Mac build also seems to generate warnings in various places unrelated to the patch (but warnings are not considered errors there).

**Comment by hassount** [comment]
@andrey-norkin 
The build is now broken for Windows, is that intended ?

**Pull request merged**
