### PR TITLE
Bug fix in common inv_transform sse3 functions and decoder LF-MT

### PR DESCRIPTION
**Pull request by nijilk**
- Bug fixes in inv_transform sse3 functions related to identity transform case
- Bug fix in decoder LF MT path

### CODE REVIEW

**Comment by nijilk** [comment]
> 
> 
> Is this applicable to master ?

**Comment by nijilk** [comment]
> 
> 
> Is this applicable to master ?

Yes. I will submit a separate PR for master as well.

**Comment by nijilk** [comment]
> 
> 
> > Is this applicable to master ?
> 
> Yes. I will submit a separate PR for master as well.

@hassount Please see PR [https://github.com/OpenVisualCloud/SVT-AV1/pull/1126](url)

**Comment by hassount** [comment]
@OmranAbdelkafi 
Can you please port this fix the the beyond-cs2 branch?

**Comment by OmranAbdelkafi** [comment]
Ported to beyond-cs2 branch

**Pull request closed without merging**
