### PR TITLE
actions: Upgrade to ubuntu 20.04

### PR DESCRIPTION
**Pull request by 1480c1**
# Description

Upgrades action linux jobs to ubuntu 20.04

# Issue

#873

# Author(s)
@1480c1

# Performance impact

- [ ] quality
- [ ] memory
- [ ] speed
- [ ] 8 bit
- [ ] 10 bit
- [x] N/A

# Test set
- [ ] obj-1-fast can be found [here](https://media.xiph.org/video/derf/objective-1-fast.tar.gz)
- [ ] other
- [x] N/A

# Merge method
- [x] Allow the maintainer to squash and merge when PR is ready to create a 1-commit to the master branch. The maintainer will be able to fix typos / combine commit messages to create a more readable 1-commit message or use whatever is stated in the 'Description' section
- [ ] I will clean up my commits and the maintainer shall use 'rebase and merge' to the master branch

### CODE REVIEW

**Comment by hassount** [comment]
can we wait on this until at least major cloud providers would offer Ubuntu 20.04?

**Comment by 1480c1** [comment]
> can we wait on this until at least major cloud providers would offer Ubuntu 20.04?

Sure, do you have any specific in mind?

Cloud providers that currently support 20.04:

- AWS
- Azure (Github Actions is based on Azure pipeline)
- DigitalOcean
- IBM cloud computing
- Google Cloud Platform
- Oracle Cloud

**Comment by hassount** [comment]
I do not see Ubuntu 20.04 as an option for C5 instances on AWS, latest ubuntu version is 18.04

**Comment by 1480c1** [comment]
Can you recheck? I see multiple instance types that start with c5 under ubuntu server 20.04 lts

image

**Comment by hassount** [comment]
I just did, our accounts might have different permissions ?

**Comment by 1480c1** [comment]
> I just did, our accounts might have different permissions ?

Perhaps, I checked under a personal account

**Pull request closed without merging**
