### PR TITLE
Update table Subsampled_Size

### PR DESCRIPTION
**Pull request by lijing0010**
Signed-off-by: Jing Li <jing.b.li@intel.com>

### CODE REVIEW

**Comment by hassount** [comment]
@NaderMahdi 
Can you please review this PR?

**Comment by EwoutH** [comment]
@hassount @NaderMahdi What's blocking this?

**Comment by hassount** [comment]
@NaderMahdi or @chkngit can one of you please take a look and make sure this is inline with the latest changes ?

**Comment by lijing0010** [comment]
This is a "fixed" table to indicate the subsampling size, it should be the same as AOM

**Comment by NaderMahdi** [comment]
I don't see any issue with this PR.

**Pull request merged**
