### PR TITLE
Bug fixes in decoder related to segment id, delta lf, film grain, etc

### PR DESCRIPTION
**Pull request by nijilk**
Following are the changes:

    Bug Fixes related to film_grain: chroma_scaling_from_luma, odd resolution supprt
    Fixes related to Storing of qindex for each segment id & segment_id from prev frame
    Bug Fixes related to parsing of DeltaFrameIdLength & delta_lf
    LF bug_fixes related to odd resolution & lossless mode
    MT bug fix related to a hang at the end
    Bug fix related to early exit in Motion field projection
    Super_res bug fixes related to smaller frame dim.( less than 16)

### CODE REVIEW

**Comment by nijilk** [comment]
@hassount @andrey-norkin 
Please review

**Comment by andrey-norkin** [comment]
> @hassount @andrey-norkin
> Please review

It looks like some linux builds are failing. Please have a look what the problem is.

**Comment by nijilk** [comment]
> 
> 
> > @hassount @andrey-norkin
> > Please review
> 
> It looks like some linux builds are failing. Please have a look what the problem is.

@andrey-norkin 
The issue is present in the previous commit as well.

**Comment by hassount** [comment]
@nijilk can you please rebase and fix the conflicts ?

**Comment by nijilk** [comment]
@hassount @andrey-norkin 
I've created a new PR [https://github.com/OpenVisualCloud/SVT-AV1/pull/1102](url) with the same changes, but rebased to latest version.

I'm closing this PR now.

**Pull request closed without merging**
