### PR TITLE
Optimization kernel av1_cost_coeffs_txb()

### PR DESCRIPTION
**Pull request by spawlows**
Kernel work ~1.3 times faster, for Debug, and RelWithDebInfo builds.

### CODE REVIEW

**Comment by ttrigui** [comment]
@spawlows what is the speed impact for release?

**Comment by hassount** [comment]
@ttrigui is this good to go ?

**Comment by ttrigui** [comment]
> @ttrigui is this good to go ?

yes.

**Comment by spawlows** [comment]
@ttrigui Sorry but I missed your question: "what is the speed impact for release?"

For mode 8 I see performance gain around 1,5%, for the rest modes differences are under measurement error.

**Pull request merged**
