### PR TITLE
build: rename "linux" directory to "posix"

### PR DESCRIPTION
**Pull request by tmatth**
Rationale: there are already some Darwin specifics here.

### CODE REVIEW

**Comment by tmatth** [comment]
If accepted, this should probably not be merged until #67 and/or #254 are merged.

**Comment by kylophone** [comment]
Not arguing against it, but another thing to consider is this will probably break everyone's automatic builds.

**Comment by hassount** [comment]
I agree with @kylophone this is going to impact all of our automated testing scripts. Is there a reason why we can't keep it as linux

**Comment by tmatth** [comment]
> I agree with @kylophone this is going to impact all of our automated testing scripts. Is there a reason why we can't keep it as linux

I added a symlink to maintain compatibility (although it would not be my first choice).

**Pull request closed without merging**
