### PR TITLE
Fix the r2r case

### PR DESCRIPTION
**Pull request by lijing0010**
cand_buff_indices[CAND_CLASS_0] may not be initialized in certain case

Signed-off-by: Jing Li <jing.b.li@intel.com>

### CODE REVIEW

**Comment by JackZhouVCD** [comment]
@lijing0010 thanks for adding this fix! Do you know which cases of r2r you are targeting with this fix?

**Comment by lijing0010** [comment]
@JackZhouVCD You can reproduce it in M2 with clip "vidyo1"

**Comment by JackZhouVCD** [comment]
> @JackZhouVCD You can reproduce it in M2 with clip "vidyo1"

Thanks! I tested your changes and found that there are no more r2r's seen when encoding the clip in M2

**Comment by hguermaz** [comment]
This piece of code will be very soon removed from the code, and replaced by a mechanism that checks all CLASSES @ the output of md-stage-0. Therefore, to avoid conflicts and save time, there is no need to merge this PR now.

**Comment by lijing0010** [comment]
close this one since it will be useless

**Comment by hguermaz** [comment]
Useless after PR 783 (already merged)

**Pull request closed without merging**
