### PR TITLE
Update, Modify, Fix actions/travis

### PR DESCRIPTION
**Pull request by luigi311**
**Actions:**
1. Add always to style check on every step so developers will not need to commit multiple times to fix through each error one at a time. This will instead go to the next step even if any of the other steps fail so they can get a complete list of what they need to fix.  
2. Update checkout to v2 on the style check.  
3. Add -10 to clang repo so it can successfully find the clang-10 package.
4. Disable fail-fast on svt-av1 so if a single matrix build fails it will still continue to build the others allowing developers to see if there is just an issue with a specific compiler build or if they are all failing.

**Travis:**
1. Add clang-10 repo so it can successfully find the clang-10 package.
2. Move travis packages to matrix. This makes viewing which packages are actually required for each matrix without having to guess. Removes unnecessary packages from matrix runs that do not require them.

### CODE REVIEW

**Comment by 1480c1** [comment]
Could you run
```bash
git rebase upstream/master -i
git push -f
```
and mark `Testing style check always` and `Revert style check test` as drop?

**Comment by luigi311** [comment]
> mark `Testing style check always` and `Revert style check test` as drop?
Is there an easy way to do this?

**Comment by 1480c1** [comment]
How do you usually edit file? Do you have access to a git command line?

**Comment by luigi311** [comment]
I usually edit via command line and upload through the git command but these were made via web. I can run the commands via command line if need be I've just never dropped a xommit so I'm not sure how to do it.

**Comment by 1480c1** [comment]
on your local repo run the commands
```bash
git fetch --all 
git fetch -i https://github.com/OpenVisualCloud/SVT-AV1.git master # In case upstream is not set 
git rebase upstream/master FETCH_HEAD
git push -f
```
On the rebase command, a screen with your default editor will pop up will something like
```git
pick d6b5b659 Style check actions: Add always()
pick 9bdb18ab Style check action:Update to checkout v2
pick fdecbc08 Svt-Av1 action:Checkout v2, add -10 to clang repo
pick b7e1bf3c Testing style check always
pick 5d480b68 Revert style check test
```

You just need to change it to
```git
pick d6b5b659 Style check actions: Add always()
pick 9bdb18ab Style check action:Update to checkout v2
pick fdecbc08 Svt-Av1 action:Checkout v2, add -10 to clang repo
drop b7e1bf3c Testing style check always
drop 5d480b68 Revert style check test
```

**Comment by luigi311** [comment]
@1480c1 Wow that's nice to know. I was first trying it and wasn't seeing anything until I noticed I was not in the right branch lol. Alright I think I got it done thanks.

**Comment by 1480c1** [comment]
Rip, sorry, ment to change upstream/master to FETCH_HEAD

**Comment by luigi311** [comment]
It looks like it still worked. The last 2 commits were dropped and are no longer in the commit list for the pull request.

**Comment by luigi311** [comment]
It seems the build scripts failed due to Microsoft updating the repo when they ran and i am unable to relaunch them. If you can relaunch the svt-av1 check and it should complete all the process as long as the same issue does not appear again.

**Comment by hassount** [comment]
> It seems the build scripts failed due to Microsoft updating the repo when they ran and i am unable to relaunch them. I reran them in my copy of the repo and they successfully finished. If you can relaunch the svt-av1 check it should complete all the steps for all builds as long as the same issue does not appear again.

seems like clang is failing on all PRs now because it can't add clang.

**Comment by luigi311** [comment]
> seems like clang is failing on all PRs now because it can't add clang.

That is correct, this will fix it. The issue was the repo was missing the -10 at the end of the repo to allow the clang-10 build to work. I can try and see if i can get the build to work even if the clang-10 fails which would be something good to implement.

**Comment by hassount** [comment]
> > seems like clang is failing on all PRs now because it can't add clang.
> 
> That is correct, this will fix it. The issue was the repo was missing the -10 at the end of the repo to allow the clang-10 build to work. I can try and see if i can get the other builds to work even if the clang-10 fails which would be something good to implement.

Cool, why is travis still failing though ?

**Comment by 1480c1** [comment]
```bash
  case "$CC" in
  gcc-7) sudo apt-get install -qq gcc-7 g++-7 ;;
  gcc-8) sudo apt-get install -qq gcc-8 g++-8 ;;
  gcc-9) sudo apt-get install -qq gcc-9 g++-9 ;;
  clang-6.0) sudo apt-get install -qq clang-6.0 ;;
  clang-10) sudo apt-get install -qq clang-10 ;;
  esac
  if [ "$TRAVIS_OS_NAME" != "osx" ]; then
    test -f "/usr/lib/ccache/${CC##*/}" || sudo ln -s /usr/bin/ccache /usr/lib/ccache/${CC##*/}
    test -f "/usr/lib/ccache/${CXX##*/}" || sudo ln -s /usr/bin/ccache /usr/lib/ccache/${CXX##*/}
  fi
  
E: Unable to locate package clang-10
```
it seems travis also can't find clang-10

**Comment by luigi311** [comment]
> > > seems like clang is failing on all PRs now because it can't add clang.
> > 
> > 
> > That is correct, this will fix it. The issue was the repo was missing the -10 at the end of the repo to allow the clang-10 build to work. I can try and see if i can get the other builds to work even if the clang-10 fails which would be something good to implement.
> 
> Cool, why is travis still failing though ?
I only updated github actions. I can try fixing travis too while i am at it

**Comment by luigi311** [comment]
@1480c1 @EwoutH 
Do you guys want me to move the matrix dependencies over to the actual matrix instead of in the before_install script? It will add a few more lines but i think it will be easier to follow and see what is getting installed for each matrix.

```
case "$CC" in
  gcc-7) sudo apt-get install -qq gcc-7 g++-7 ;;
  gcc-8) sudo apt-get install -qq gcc-8 g++-8 ;;
  gcc-9) sudo apt-get install -qq gcc-9 g++-9 ;;
  clang-6.0) sudo apt-get install -qq clang-6.0 ;;
  clang-10) sudo apt-get install -qq clang-10 ;;
  esac
```

**Comment by 1480c1** [comment]
Go ahead, I'll give my opinion after I see if there's any impact

**Comment by luigi311** [comment]
@1480c1 
Is ppa:ubuntu-toolchain-r/test only being used for gcc-9?

**Comment by luigi311** [comment]
@1480c1 
I implemented the move over from before_install to matrix

**Comment by 1480c1** [comment]
> @1480c1
> I implemented the move over from before_install to matrix

Nice. You might want to also do that for valgrind, gstreamer packages with gstreamer job, and python only really needing to be on the coveralls job

**Comment by luigi311** [comment]
> Nice. You might want to also do that for valgrind, gstreamer packages with gstreamer job, and python only really needing to be on the coveralls job

All set

**Comment by hassount** [comment]
@luigi311 @1480c1 Thank you guys for addressing this.

**Pull request merged**
