### PR TITLE
Weiner filter avx2 bug fix

### PR DESCRIPTION
**Pull request by lzhangnj**
Fix segfaults in Wiener Filter AVX2

Issue #346 on MAC is caused by large stack usage. Moved the buffer to heap.

Related to PR #333

### CODE REVIEW

**Comment by hassount** [comment]
@lzhangnj 
Does this change the bitstream for windows / linux?

**Comment by lzhangnj** [comment]
@hassount  No. Should be bit-exact for all platforms.

**Comment by mafonsoN** [comment]
I did some quick tests and the bug seems to be solved for Mac. Are there any speed implications of these changes?

**Comment by hassount** [comment]
@mafonsoN 
thank you for confirming, I don't see a speed difference on my end. @lzhangnj do you expect any speed loss with the change ?

**Comment by lzhangnj** [comment]
@hassount It's called in the size of 256x256 blocks, so the impact on speed would be very trivial.

**Pull request merged**
