### PR TITLE
Reduced malloc times to make eb_init_encoder faster

### PR DESCRIPTION
**Pull request by zhonghongcheng**
There are too many malloc times when initiate SvtAv1EncApp. It makes initiation too slow on server and this can be relieved by reduce malloc times in block way.

Vtune show that `mode_decision_context_ctor` takes 30.4% cpu time of eb_init_encoder's 83.5%; and `eb_object_wrapper_ctor` takes 28.2% cpu time of eb_init_encoder's 83.5%. I tried block way to reduce malloc times in this two functions.

Tested by:
```
SvtAv1EncApp -enc-mode 8 -w 1920 -h 1080 -fps 60 irefresh-type 2  -i 1920x1080.yuv 
-q 32 -b output.bin -bit-depth 8 -stat-report  -n 300 
```
Here are some result comparation:

|        | build_type | init_time | malloc_times |
| ------ | ---------- | --------- | ------------ |
| after  | Debug      | 6.4660s   | 331625       |
|        | Release    | 5.6350s   | 331625       |
| before | Debug      | 7.9340s   | 1964126      |
|        | Release    | 6.6300s   | 1964126      |

```
-------------------------------------------                      
SVT-AV1 Encoder                                                  
SVT [version]:  SVT-AV1 Encoder Lib v0.7.5                       
SVT [build]  :  GCC 7.4.0        64 bit                          
LIB Build date: Dec 13 2019 16:09:22                             
-------------------------------------------                      
Number of logical cores available: 112                           
Number of PPCS 159                                               
-------------------------------------------                      
SVT [config]: Main Profile      Tier (auto)     Level (auto)     
SVT [config]: EncoderMode                                       : 8                                                               
SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat      : 8 / 1 / 0                                      
SVT [config]: SourceWidth / SourceHeight                        : 1920 / 1080                                                     
SVT [config]: FrameRate / Gop Size                              : 60 / 64                                                         
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure           : 4 / 0 / 2                                      
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange  : CQP / 32 / 33 / 0            
SVT Memory Usage:                                                
    total allocated memory:       35.18 GB 1964126 times         
        malloced memory:          24.15 GB 1346516 times         
        callocated memory:        1.39 GB 266584 times           
        allocated aligned memory: 9.64 GB 351026 times           
    mutex count: 2865                                            
    semaphore count: 2008                                        
    thread count: 536                                            
    hash table fulless: 0.469574, hash bucket is too full
-----------------------------------------------------------
After optimization:
SVT Memory Usage:                                                
    total allocated memory:       35.39 GB 331625 times          
        malloced memory:          24.31 GB 125424 times          
        callocated memory:        1.39 GB 178961 times           
        allocated aligned memory: 9.69 GB 27240 times            
    mutex count: 2865                                            
    semaphore count: 2008                                        
    thread count: 536                                            
    hash table fulless: 0.080355, hash bucket is healthy
```

### CODE REVIEW

**Comment by zhonghongcheng** [comment]
It seems that test failed on macOS clang build:
```
/Users/travis/.travis/functions: line 109:  7128 Segmentation fault: 11  SvtAv1EncApp -enc-mode 8 -i akiyo_cif.y4m -n 150 -b test1.ivf
The command "SvtAv1EncApp -enc-mode 8 -i akiyo_cif.y4m -n 150 -b test1.ivf" exited with 139.
```
I do not know how to fix this. Can anyone help to tell me what to do?
I am a rookie and this is my first PR:)

**Comment by mafonsoN** [comment]
> It seems that test failed on macOS clang build:
> 
> ```
> /Users/travis/.travis/functions: line 109:  7128 Segmentation fault: 11  SvtAv1EncApp -enc-mode 8 -i akiyo_cif.y4m -n 150 -b test1.ivf
> The command "SvtAv1EncApp -enc-mode 8 -i akiyo_cif.y4m -n 150 -b test1.ivf" exited with 139.
> ```
> 
> I do not know how to fix this. Can anyone help to tell me what to do?
> I am a rookie and this is my first PR:)

You need to reproduce this error and fix the bug. Do you have access to a macOS machine?

**Comment by zhonghongcheng** [comment]
> > It seems that test failed on macOS clang build:
> > ```
> > /Users/travis/.travis/functions: line 109:  7128 Segmentation fault: 11  SvtAv1EncApp -enc-mode 8 -i akiyo_cif.y4m -n 150 -b test1.ivf
> > The command "SvtAv1EncApp -enc-mode 8 -i akiyo_cif.y4m -n 150 -b test1.ivf" exited with 139.
> > ```
> > 
> > 
> > I do not know how to fix this. Can anyone help to tell me what to do?
> > I am a rookie and this is my first PR:)
> 
> You need to reproduce this error and fix the bug. Do you have access to a macOS machine?

The problem is that I do not have access to a macOC machine...

**Comment by zhonghongcheng** [comment]
I tested on `macOS 10.15.2 Catalina with Apple LLVM 11.0.0 (clang-1100.0.33.8)` and `macOS 10.14.4 Mojave with Apple LLVM 10.0.1 (clang 1001.0.46.4)`, and both passed. Can not reproduce the error in CI. What should I do then?

**Comment by 1480c1** [comment]
@zhonghongcheng, can you rebase on latest master to make sure you have an update travis-ci yaml configuration file?

**Comment by zhonghongcheng** [comment]
Thanks @1480c1 ! It seems macOS compile is alright after rebase on master.

**Comment by zhonghongcheng** [comment]
I would like to ask that in function `EbEncHandle.c: allocate_frame_buffer`. There is a hardcoded line [`input_picture_buffer_desc_init_data.buffer_enable_mask = PICTURE_BUFFER_DESC_FULL_MASK;`](https://github.com/OpenVisualCloud/SVT-AV1/blob/master/Source/Lib/Encoder/Codec/EbEncHandle.c#L3691) , which makes options on `buffer_enable_mask` above useless. I am confused about this.

**Pull request closed without merging**
