### PR TITLE
CI: Update AppVeyor to Visual Studio 2019

### PR DESCRIPTION
**Pull request by EwoutH**
Updates AppVeyor to Visual Studio 2019 (version 16.1).

### CODE REVIEW

**Comment by kylophone** [comment]
@hassount, any issue with this?

**Comment by hassount** [comment]
> @hassount, any issue with this?

@kylophone the concern is that we would have a mismatch with the version that we are using locally (vs 17) which might make it a little tough to duplicate issues. We have to wait for IT to push VS19 for us to be able to use it. 
I guess we can go ahead as long as there's someone who can duplicate and fix specific VS19 issues,

**Comment by 1480c1** [comment]
@EwoutH , could you see if the vs2019 image has vs2017 also? if so we could make two jobs with one running vs2019 and the other vs2017

**Comment by 1480c1** [comment]
It seems that their image does not include 2017.

**Comment by hassount** [comment]
ok, let's merge this and see how it goes, if we face major issues, we can revert back

**Pull request merged**
