### PR TITLE
Coding style updates to ASM folders and ~25% of Codec folder header files

### PR DESCRIPTION
**Pull request by adixonn**

### CODE REVIEW

**Comment by hassount** [comment]
@adixonn, please make sure the changes are applied to the ffmpeg plugin too

**Comment by hassount** [comment]
@joelsole @kylophone @andrey-norkin @mafonsoN 
Please let us know if we can proceed with this.

**Comment by mafonsoN** [comment]
Lgtm

**Comment by kylophone** [comment]
lgtm, merge away.

**Comment by andrey-norkin** [comment]
Looks good

**Pull request merged**
