### PR TITLE
CI: Error on warnings

### PR DESCRIPTION
**Pull request by luigi311**
This adds werror to all builds and wno-error=array-bounds for clang to match up with Travis.

### CODE REVIEW

**Comment by 1480c1** [comment]
@luigi311 you might want to "reset" the `CFLAGS` before configuring FFmpeg since FFmpeg is failing right now.

Also, are you familiar with how to use git locally on a machine instead of using the github editing tool? I'm not sure if there's a way to rebase using github's editing tool

**Comment by luigi311** [comment]
@1480c1 
ohh your right looks like the FFMPEG patch ci was changed a lot to include macos building. Ill get that working and do a rebase.

**Comment by luigi311** [comment]
Rebased to master

**Comment by ePirat** [comment]
Not really specific to this PR as it existed before but why is the `wno-error=array-bounds` there?

**Comment by 1480c1** [comment]
Clang had some warnings about arrays a long time ago, I'm not sure if it still applies now though

**Comment by 1480c1** [comment]
@luigi311 can you try deleting the `-Wno-error=*` one from clang?

**Comment by luigi311** [comment]
Sure

**Comment by luigi311** [comment]
@1480c1
https://github.com/luigi311/SVT-AV1/runs/676265419?check_suite_focus=true

**Comment by 1480c1** [comment]
Seems we no longer need it anymore

**Comment by luigi311** [comment]
Want me to go ahead and remove it?

**Comment by 1480c1** [comment]
Yeah

**Comment by luigi311** [comment]
All set

**Pull request merged**
