### PR TITLE
remove testing on IBMZ architecture

### PR DESCRIPTION
**Pull request by ttrigui**
# Description
Remove testing on IBMZ architecture in travis

# Author(s)
@ttrigui 

# Performance impact
- [ ] quality
- [ ] memory
- [ ] speed
- [ ] 8 bit
- [ ] 10 bit
- [X] N/A

# Test set
- [ ] obj-1-fast can be found [here](https://media.xiph.org/video/derf/objective-1-fast.tar.gz)
- [ ] other
- [X] N/A

# Merge method
- [X] Allow the maintainer to squash and merge when PR is ready to create a 1-commit to the master branch. The maintainer will be able to fix typos / combine commit messages to create a more readable 1-commit message or use whatever is stated in the 'Description' section
- [ ] I will clean up my commits and the maintainer shall use 'rebase and merge' to the master branch

### CODE REVIEW

**Comment by 1480c1** [comment]
Could you perhaps expand more on why we are removing it? it will help for posterity on trying to find out why this is being committed.

**Comment by ttrigui** [comment]
> Could you perhaps expand more on why we are removing it? it will help for posterity on trying to find out why this is being committed.

Because this has triggered a random issue that we are not able to reproduce within our system. Also we already have tests run on ARM architecture which covers testing our code using an ARM processor.

**Comment by 1480c1** [comment]
I was mainly thinking about inside the commit and inside the pr main message, but that works I guess

**Comment by hassount** [comment]
closing for #1395

**Pull request closed without merging**
