### PR TITLE
Improve help menu:

### PR DESCRIPTION
**Pull request by OmranAbdelkafi**
## Description
Format and add more details to help menu
Update encoder user guide 

## Performance 
No impact

## Related issues
#779
#945

### CODE REVIEW

**Comment by hassount** [comment]
Usage: SvtAv1EncApp.exe <options> -o dst_filename -i src_filename

-o should be -b

**Comment by OmranAbdelkafi** [comment]
> Usage: SvtAv1EncApp.exe -o dst_filename -i src_filename
> 
> -o should be -b

fixed

**Comment by zyue128** [comment]
So is the -latency-mode still supported?

**Comment by hassount** [comment]
> So is the -latency-mode still supported?

-latency-mode is not supported anymore, do you see it anywhere currently ?

**Comment by zyue128** [comment]
I found it in the code EbAppConfig.c while I was looking for low latency setting. No wonder there is no doc for it then! Thank you.

**Comment by hassount** [comment]
Thank you for bringing this up, @OmranAbdelkafi can we schedule a quick cleanup on EbAppConfig.c ?

**Comment by zyue128** [comment]
One more question, what should I use for a low latency mode?

**Pull request merged**
