### PR TITLE
cleanup: add a bash script

### PR DESCRIPTION
**Pull request by 1480c1**
add a cleanup script to auto remove trailing whitespace and remove multiple newlines in a row.

Currently WIP

### CODE REVIEW

**Comment by kylophone** [comment]
Would it be better to use a `.clangformat` file to do this?

**Comment by 1480c1** [comment]
I was thinking so too but there are a couple of problems with the clang-format, 
1. It requires clang-format
2. Only works on c and h files
3. Inconsistent ATM

**Comment by 1480c1** [comment]
So if you wanted to clean up white space in cmakelists or MD files, clang-format would not be able to do it

**Comment by ttrigui** [comment]
@1480c1 is this still a WIP?

**Comment by 1480c1** [comment]
Yes for now since I can't come up with a better way. I would prefer to set it up with clang format, however the style guide lines are very vague

**Comment by EwoutH** [comment]
@1480c1 Are you still working on this?

**Comment by 1480c1** [comment]
Currently waiting to see if a clangformat can be added, I could add it as is, but it won't really be a cleanup script then

**Comment by EwoutH** [comment]
So blocked by #574?

**Comment by 1480c1** [comment]
Somewhat yes

**Comment by hassount** [comment]
@1480c1 should we close this and make another one after the cleanup ?

**Comment by 1480c1** [comment]
Sure

**Pull request closed without merging**
