### PR TITLE
Me sub_pel refinement optimization

### PR DESCRIPTION
**Pull request by NaderMahdi**
Restructure the Sub_pel refinement to be done in an NxM window around the best integer-pel and where NxM is set to 3x3 by default.

The recorded data on the 360p clips is 11% speedup in encoding time for 0.1% bdrate gain and no impact on the memory.

Please note that this PR replaces the #464 one.

### CODE REVIEW

**Comment by JackZhouVCD** [comment]
lgtm

**Comment by NaderMahdi** [comment]
@joelsole - Can #566 be merged?

**Comment by joelsole** [comment]
@andrey-norkin ?

**Comment by joelsole** [comment]
Is this last commit intended?

**Comment by JackZhouVCD** [comment]
> Is this last commit intended?
Yes, it was to resolve the merge conflict

**Comment by andrey-norkin** [comment]
Ok, let us approve then.

**Comment by andrey-norkin** [comment]
It also looks like you are completely removing several Unit Tests.

**Comment by JackZhouVCD** [comment]
> It also looks like you are completely removing several Unit Tests.

That is my fault, I thought that I only changed one line with the latest commit. I will redo and then squash the commits for fixing the merge conflicts so the history will be clean

**Comment by JackZhouVCD** [comment]
> > It also looks like you are completely removing several Unit Tests.
> 
> That is my fault, I thought that I only changed one line with the latest commit. I will redo and then squash the commits for fixing the merge conflicts so the history will be clean

@joelsole @andrey-norkin I believe I fixed the issue, please have another look. Sorry about the inconvenience.

**Comment by NaderMahdi** [comment]
@ joelsole - Can we merge this PR?

**Pull request merged**
