### PR TITLE
Add protection for out of boundary

### LINKED ISSUE #1262: This small video crashes SVT 0.8.3, 0.8.2 and 0.8.1
This short 8 MB snippet from a DVB-S documentation recording is enough:
https://joumxyzptlk.de/tmp/svt-av1/Die_Planeten_4_Saturn_20200322_2033.SVT-0.8.2_crash_snippet_v2.mkv

Machine: Ryzen 9 3900x / 64 GB ECC RAM (see https://github.com/OpenVisualCloud/SVT-AV1/issues/1159 which was IMHO closed too soon, test if that anime-source video still crashes SVT 0.8.3 too is currently running).

Exact command line and output for 0.8.3 downloaded right now (aka v0.8.2-7-g487f83cc-dirty, version bump forgotten?):
```
c:\prog\ffmpeg\bin\ffmpeg.exe -hide_banner -loglevel quiet -i X:\tmp\video-in\Die_Planeten_4_Saturn_20200322_2033.SVT-0.8.2_crash_snippet_v2.mkv -an  -pix_fmt yuv420p -f yuv4mpegpipe -   | c:\prog\svt-av1\SvtAv1EncApp.exe --input stdin --frames 484 --rc 0 --qp 36 --lp 24 --preset 1 --tile-rows 1 --tile-columns 2 --lookahead 80 --output X:\tmp\video-in\Die_Planeten_4_Saturn_20200322_2033.SVT-0.8.2_crash_snippet_v2.mkv.pr1.qp36.svt-av1.083.ivf
-------------------------------------------
SVT-AV1 Encoder
SVT [version]:  SVT-AV1 Encoder Lib v0.8.2-7-g487f83cc-dirty
SVT [build]  :  Visual Studio 2019 64 bit
LIB Build date: Apr 24 2020 21:15:07
-------------------------------------------
Number of logical cores available: 24
Number of PPCS 114
[asm level on system : up to avx2]
[asm level selected : up to avx2]
-------------------------------------------
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: EncoderMode                                                       : 1
SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat     : 8 / 1 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 1280 / 720
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType     : 50 / 1 / 48 / 1
SVT [config]: HierarchicalLevels  / PredStructure               : 4 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 36 / 33 / 0
-------------------------------------------
Encoding       289

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2020-04-24T23:03:50.337001400Z" /> 
  <EventRecordID>21041</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>PC-JOU</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>SvtAv1EncApp.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>5ea35716</Data> 
  <Data>SvtAv1Enc.dll</Data> 
  <Data>0.0.0.0</Data> 
  <Data>5ea356e6</Data> 
  <Data>c0000005</Data> 
  <Data>00000000000b4135</Data> 
  <Data>3850</Data> 
  <Data>01d61a8bdb22633a</Data> 
  <Data>c:\prog\svt-av1\SvtAv1EncApp.exe</Data> 
  <Data>c:\prog\svt-av1\SvtAv1Enc.dll</Data> 
  <Data>d52214d0-d334-4b42-a32d-1950cf50cf01</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
```

Version 0.8.2:
```
c:\prog\ffmpeg\bin\ffmpeg.exe -hide_banner -loglevel quiet -i X:\tmp\video-in\Die_Planeten_4_Saturn_20200322_2033.SVT-0.8.2_crash_snippet_v2.mkv -an  -pix_fmt yuv420p -f yuv4mpegpipe -   | c:\prog\svt-av1\SvtAv1EncApp.exe --input stdin --frames 484 --rc 0 --qp 36 --lp 24 --preset 1 --tile-rows 1 --tile-columns 2 --lookahead 80 --output X:\tmp\video-in\Die_Planeten_4_Saturn_20200322_2033.SVT-0.8.2_crash_snippet_v2.mkv.pr1.qp36.svt-av1.082.ivf
-------------------------------------------
SVT-AV1 Encoder
SVT [version]:  SVT-AV1 Encoder Lib v0.8.2-dirty
SVT [build]  :  Visual Studio 2019 64 bit
LIB Build date: Apr 20 2020 02:13:50
-------------------------------------------
Number of logical cores available: 24
Number of PPCS 114
[asm level on system : up to avx2]
[asm level selected : up to avx2]
-------------------------------------------
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: EncoderMode                                                       : 1
SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat     : 8 / 1 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 1280 / 720
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType     : 50 / 1 / 48 / 1
SVT [config]: HierarchicalLevels  / PredStructure               : 4 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 36 / 33 / 0
-------------------------------------------
Encoding       190

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2020-04-24T22:47:46.779098000Z" /> 
  <EventRecordID>21035</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>PC-JOU</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>SvtAv1EncApp.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>5e9d0597</Data> 
  <Data>SvtAv1Enc.dll</Data> 
  <Data>0.0.0.0</Data> 
  <Data>5e9d0568</Data> 
  <Data>c0000005</Data> 
  <Data>00000000000b4275</Data> 
  <Data>bc</Data> 
  <Data>01d61a89f41465d2</Data> 
  <Data>c:\prog\svt-av1\SvtAv1EncApp.exe</Data> 
  <Data>c:\prog\svt-av1\SvtAv1Enc.dll</Data> 
  <Data>5959f452-2d1d-41f8-92d8-4198a17ac4d4</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
```

Version 0.8.1:
```
c:\prog\ffmpeg\bin\ffmpeg.exe -hide_banner -loglevel quiet -i X:\tmp\video-in\Die_Planeten_4_Saturn_20200322_2033.SVT-0.8.2_crash_snippet_v2.mkv -an  -pix_fmt yuv420p -f yuv4mpegpipe -   | c:\prog\svt-av1\SvtAv1EncApp.exe -i stdin -n 484 -rc 0 -q 42 -lp 24 -enc-mode 1 -tile-rows 1 -tile-columns 2 -lad 80 -b X:\tmp\video-in\Die_Planeten_4_Saturn_20200322_2033.SVT-0.8.2_crash_snippet_v2.mkv.em1.q42.svt-av1.081.ivf
-------------------------------------------
SVT-AV1 Encoder
SVT [version]:  SVT-AV1 Encoder Lib v0.8.1
SVT [build]  :  Visual Studio 2017 64 bit
LIB Build date: Jan 29 2020 14:56:28
-------------------------------------------
Number of logical cores available: 24
Number of PPCS 114
[asm level on system : up to avx2]
[asm level selected : up to avx2]
-------------------------------------------
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: EncoderMode                                                       : 1
SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat     : 8 / 1 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 1280 / 720
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType     : 50 / 1 / 48 / 1
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure          : 4 / 0 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 42 / 33 / 0
-------------------------------------------
Encoding       194

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2020-04-24T22:54:38.852406400Z" /> 
  <EventRecordID>21039</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>PC-JOU</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>SvtAv1EncApp.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>5e319d54</Data> 
  <Data>SvtAv1Enc.dll</Data> 
  <Data>0.0.0.0</Data> 
  <Data>5e319d25</Data> 
  <Data>c0000005</Data> 
  <Data>000000000005baf5</Data> 
  <Data>18a4</Data> 
  <Data>01d61a8ad2679a1f</Data> 
  <Data>c:\prog\svt-av1\SvtAv1EncApp.exe</Data> 
  <Data>c:\prog\svt-av1\SvtAv1Enc.dll</Data> 
  <Data>a0c3066b-7fe0-4d76-9bc2-ac1f737d7135</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
```

### PR DESCRIPTION
**Pull request by lijing0010**
should also fix #1262

Signed-off-by: Jing Li <jing.b.li@intel.com>

### CODE REVIEW

**Comment by EricLamVCD** [comment]
Tested obj-1 fast 8bit clips: 
  | Speed Deviation  | BD-Rate   Deviation
-- | -- | --
M0 | 0.34% | 0.00%
M4 | 0.35% | 0.00%
M8 | 0.17% | 0.00%

Also, tested for #1262 on windows and this PR does not crash for #1262

**Comment by JouMxyzptlk** [comment]
Testing with https://ci.appveyor.com/project/tianjunwork/svt-av1/builds/32641951/job/vn9l2yrvd0awtpqp/artifacts
Seems to finally fix https://github.com/OpenVisualCloud/SVT-AV1/issues/1280 and https://github.com/OpenVisualCloud/SVT-AV1/issues/1159
Finally I can go on with mass-encoding-testing until the next reproducible bug comes along :).

**Comment by tianjunwork** [comment]
Thank you @JouMxyzptlk testing the issue. Maybe run several times. If #1280 is fixed, could you close it?
Sure. Thanks reporting bugs:)

**Comment by JouMxyzptlk** [comment]
> Thank you @JouMxyzptlk testing the issue. Maybe run several times. If #1280 is fixed, could you close it?

I will, but takes a bit time, around 0,3 frames per second - maybe it should switch to seconds per frame at that speed ;). Using faster encode settings doesn't offer enough compression win.

> Sure. Thanks reporting bugs:)

Worth it, 30% to 50% better compression vs x264 at about the same quality (with a few exceptions). Wins against the disappointing h265 which offered at average only 10% better compression over h264 if you run with --no-strong-intra to compensate over-filtering, i.e. prevent making faces 10 to 20 years younger.
Where can I report samples which show weaknesses i.e. too much detail loss (compared to x264), as mentioned in https://github.com/OpenVisualCloud/SVT-AV1/issues/1280 ?

**Pull request merged**
