### PR TITLE
Add eb_cdef_filter_block_8x8_16_avx512() and search_one_dual_avx512()

### PR DESCRIPTION
**Pull request by lzhangnj**
Add eb_cdef_filter_block_8x8_16_avx512().
About 20% faster than avx2.

Add search_one_dual_avx512().
About 86% - 113% faster than avx2.

### CODE REVIEW

**Comment by JackZhouVCD** [comment]
Thanks for adding the kernels! When I apply the pr and enable AVX512, I see a segmentation fault with the following command:
```bash
./SvtAv1EncApp -i  ~/stream/speed_360p.yuv -w 640 -h 360 -fps 60 -enc-mode 1 -q 43 -b speed_360p_q43_enc_1.ivf
```
---
I ran the encoder through gdb and I found the following error:

```css
Thread 273 "SvtAv1EncApp" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffea6435700 (LWP 14879)]
0x00007fffec240259 in _mm512_load_si512 (__P=0x7ffea642cae0)
    at /usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h:490
490	  return *(__m512i *) __P;
```

Can you look into this?

**Comment by lzhangnj** [comment]
> Can you look into this?
I checked in the fix. I cannot reproduce the fault on Windows which allows unaligned memory access. Please help verify on your machine. Thanks!

**Comment by JackZhouVCD** [comment]
> > Can you look into this?
> 
> I checked in the fix. I cannot reproduce the fault on Windows which allows unaligned memory access. Please help verify on your machine. Thanks!

Yes! The fix works! I'm seeing ~ 0.13% speed gain averaged over M{1,4,8} after applying the PR.

**Comment by ttrigui** [comment]
@joelsole and @mafonsoN can you please look into this PR?

**Pull request merged**
