### PR TITLE
Support stdout for output

### LINKED ISSUE #701: Support output to stdout for improved pipe support {feature request}
Currently, when using ffmpeg with SvtAv1EncApp with pipes, one does

`ffmpeg -i input.mkv -an -s 424x240 -f yuv4mpegpipe -pix_fmt yuv420p  - | SvtAv1EncApp -i stdin -n 10 -w 424 -h 240  -fps 24 -rc 3 -tbr 75000 -enc-mode 5  test.webm`

for producing output to a file test.webm
The problem here is that one cannot encode audio simultaneously. If Svt could output to stdout, one could do 

`ffmpeg -i input.mkv -an -s 424x240 -f yuv4mpegpipe -pix_fmt yuv420p  - | SvtAv1EncApp -i stdin -n 10 -w 424 -h 240  -fps 24 -rc 3 -tbr 75000 -enc-mode 5  - | ffmpeg -i - -i input.mkv -map 0:v -c:v copy -map 1:a -c:a libopus output.webm`

and in this case, output.webm would have both audio and video.
I know that there is a ffmpeg plugin (libsvt), but I cant get that to compile, so I have to use SvtAv1EncApp via pipes. 

It would be nice if svt could output to stdout (like rav1e and aomenc can)

### PR DESCRIPTION
**Pull request by sandersaares**
Closes #701

### CODE REVIEW

**Comment by silverbacknet** [comment]
The usual convention for stdout/stdin is a single dash "-", not "stdout" though. Linux has /dev/stdout to explicitly name it, although Windows doesn't natively have an equivalent.

**Comment by 1480c1** [comment]
I think this is to match the `-i stdin` we are currently using

**Comment by sandersaares** [comment]
Yeah, exactly. Oh, that reminds me I should also update docs to mention this.

**Comment by tianjunwork** [comment]
Tested on both Linux and Windows with:
 `SvtAv1EncApp -i ../../yuv/akiyo_cif.y4m -b stdout | ffmpeg -i - -c:v copy out.mkv`
It works on both with newer ffmpeg version. But it has nothing to do with the implementation of this PR. Just to share this info in case anyone runs into issue.

**Pull request merged**
