### PR TITLE
Svt-01 branch rebase and performance update

### PR DESCRIPTION
**Pull request by okhlif**
# Description
Manual rebase of svt-01 branch on top of master
Quality, speed and memory improvement

- PR split it into coherent commits

- All intermediate commits build just fine

- #def macros are all enabled and turning them one by one in chronological order (top to bottom)  will compile (allow bisecting within the commits)

# Issue
#1389 

# Author(s)
 @hguermaz 
 @kelvinhu325 
 @anaghdin 
 @PhoenixWorthVCD
 @lijing0010 
 @NaderMahdi 
 @chkngit 
 @okhlif 

# Performance impact

- [x] quality
- [x] memory
- [x] speed
- [x] 8 bit
- [x] 10 bit
- [ ] N/A

# Test set
- [x] obj-1-fast can be found [here](https://media.xiph.org/video/derf/objective-1-fast.tar.gz)
- [ ] other
- [ ] N/A

# Merge method
- [ ] Allow the maintainer to squash and merge when PR is ready to create a 1-commit to the master branch. The maintainer will be able to fix typos / combine commit messages to create a more readable 1-commit message or use whatever is stated in the 'Description' section
- [x] I will clean up my commits and the maintainer shall use 'rebase and merge' to the master branch

### CODE REVIEW

**Comment by ttrigui** [comment]
No luck with reproducing the IBMZ error. I changed the gcc version to 10.1, I used --lp 4 I also compiled c only code. The encoder runs fine on the AWS instance I'm using.
-------------------------------------------
SVT [version]:  SVT-AV1 Encoder Lib v0.8.4-42-g422bec98-dirty
SVT [build]  :  GCC 10.1.0       64 bit
LIB Build date: Jul 23 2020 23:35:56
-------------------------------------------
Number of logical cores available: 4
Number of PPCS 78
[asm level on system : up to c]
[asm level selected : up to c]

@EwoutH any thoughts about this?

**Comment by 1480c1** [comment]
@okhlif you will need to rebase to add the changes from the symbol change

**Comment by okhlif** [comment]
> @okhlif you will need to rebase to add the changes from the symbol change

Yes Thank you, we are waiting for other PRs to get merged to rebase once for all.

**Comment by ttrigui** [comment]
Valgrind is actually failing https://travis-ci.com/github/OpenVisualCloud/SVT-AV1/jobs/364409634 . anyone working on it?

**Comment by OmranAbdelkafi** [comment]
Tested obj-1 8bit and 10bit clips:



Obj-1-fast |   | 8bit | Bdrate Deviation | Speed Deviation | Max Memory Deviation
-- | -- | -- | -- | -- | --
PR1393_422bec9_M0 | vs. | master_73793b0_M0 | -6.19% | -12.78% | -9.44%
PR1393_422bec9_M1 | vs. | master_73793b0_M1 | -5.69% | 11.82% | -9.20%
PR1393_422bec9_M2 | vs. | master_73793b0_M2 | -11.88% | -37.77% | -8.48%
PR1393_422bec9_M3 | vs. | master_73793b0_M3 | -18.39% | -73.87% | -7.32%
PR1393_422bec9_M4 | vs. | master_73793b0_M4 | -16.06% | -57.95% | -9.53%
PR1393_422bec9_M5 | vs. | master_73793b0_M5 | -19.51% | -48.45% | -7.79%
PR1393_422bec9_M6 | vs. | master_73793b0_M6 | -22.03% | -41.16% | 4.50%
PR1393_422bec9_M7 | vs. | master_73793b0_M7 | -16.47% | -9.52% | 2.83%





Obj-1-fast |   | 10bit | Bdrate Deviation | Speed Deviation | Max Memory Deviation
-- | -- | -- | -- | -- | --
PR1393_422bec9_M0 | vs. | master_73793b0_M0 | -6.10% | -15.19% | -20.41%
PR1393_422bec9_M1 | vs. | master_73793b0_M1 | -5.56% | 17.70% | -20.43%
PR1393_422bec9_M2 | vs. | master_73793b0_M2 | -11.05% | -37.29% | -20.09%
PR1393_422bec9_M3 | vs. | master_73793b0_M3 | -17.90% | -73.10% | -19.13%
PR1393_422bec9_M4 | vs. | master_73793b0_M4 | -15.84% | -58.78% | -20.02%
PR1393_422bec9_M5 | vs. | master_73793b0_M5 | -18.32% | -49.57% | -18.02%
PR1393_422bec9_M6 | vs. | master_73793b0_M6 | -21.92% | -41.35% | -15.51%
PR1393_422bec9_M7 | vs. | master_73793b0_M7 | -17.08% | -11.44% | -19.52%

**Comment by okhlif** [comment]
> Valgrind is actually failing https://travis-ci.com/github/OpenVisualCloud/SVT-AV1/jobs/364409634 . anyone working on it?

I believe it is fixed now with the latest commit.

**Comment by 1480c1** [comment]
> > Valgrind is actually failing https://travis-ci.com/github/OpenVisualCloud/SVT-AV1/jobs/364409634 . anyone working on it?
> 
> I believe it is fixed now with the latest commit.

```none
==9126== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```
seems so

btw, the mingw-w64 error is due to the fact that the patch was upstream last night https://github.com/FFmpeg/FFmpeg/commit/0e20dee5c21a40f23ecfe7af2c360493a169c0f0 so the patch no longer applies onto the master branch anymore

**Comment by okhlif** [comment]
I believe all stability issues are now addresses 
 Patch FFmpeg and IBMZ  failures are expected.
Please let me know if anything else is needed.

**Comment by hassount** [comment]
> > > Valgrind is actually failing https://travis-ci.com/github/OpenVisualCloud/SVT-AV1/jobs/364409634 . anyone working on it?
> > 
> > 
> > I believe it is fixed now with the latest commit.
> 
> ```
> ==9126== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
> ```
> 
> seems so
> 
> btw, the mingw-w64 error is due to the fact that the patch was upstream last night [FFmpeg/FFmpeg@0e20dee](https://github.com/FFmpeg/FFmpeg/commit/0e20dee5c21a40f23ecfe7af2c360493a169c0f0) so the patch no longer applies onto the master branch anymore

what can we do about this, should we remove the patch ?

**Comment by 1480c1** [comment]
> > > > Valgrind is actually failing https://travis-ci.com/github/OpenVisualCloud/SVT-AV1/jobs/364409634 . anyone working on it?
> > > 
> > > 
> > > I believe it is fixed now with the latest commit.
> > 
> > 
> > ```
> > ==9126== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
> > ```
> > 
> > 
> > seems so
> > btw, the mingw-w64 error is due to the fact that the patch was upstream last night [FFmpeg/FFmpeg@0e20dee](https://github.com/FFmpeg/FFmpeg/commit/0e20dee5c21a40f23ecfe7af2c360493a169c0f0) so the patch no longer applies onto the master branch anymore
> 
> what can we do about this, should we remove the patch ?

I am currently working with @ccccheung to fix github actions, but in the meanwhile, it is best to just go ahead and remove it from our repo since it doesn't really work as a patch anymore and would also prevent people from modifying it in tree, since any more changes should go to upstream and perhaps be properly versioned as well.

For non-master branch ffmpeg builds, it would be best for them to be redirected to a git tag and use the patch file from there

**Comment by okhlif** [comment]
> > > > Valgrind is actually failing https://travis-ci.com/github/OpenVisualCloud/SVT-AV1/jobs/364409634 . anyone working on it?
> > > 
> > > 
> > > I believe it is fixed now with the latest commit.
> > 
> > 
> > ```
> > ==9126== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
> > ```
> > 
> > 
> > seems so
> > btw, the mingw-w64 error is due to the fact that the patch was upstream last night [FFmpeg/FFmpeg@0e20dee](https://github.com/FFmpeg/FFmpeg/commit/0e20dee5c21a40f23ecfe7af2c360493a169c0f0) so the patch no longer applies onto the master branch anymore
> 
> what can we do about this, should we remove the patch ?

I can remove it with this PR or have separate PR  to remove.

**Comment by ttrigui** [comment]
@spawlows is expected to commit his sad fix soon.

**Comment by hassount** [comment]
> > > > > Valgrind is actually failing https://travis-ci.com/github/OpenVisualCloud/SVT-AV1/jobs/364409634 . anyone working on it?
> > > > 
> > > > 
> > > > I believe it is fixed now with the latest commit.
> > > 
> > > 
> > > ```
> > > ==9126== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
> > > ```
> > > 
> > > 
> > > seems so
> > > btw, the mingw-w64 error is due to the fact that the patch was upstream last night [FFmpeg/FFmpeg@0e20dee](https://github.com/FFmpeg/FFmpeg/commit/0e20dee5c21a40f23ecfe7af2c360493a169c0f0) so the patch no longer applies onto the master branch anymore
> > 
> > 
> > what can we do about this, should we remove the patch ?
> 
> I can remove it with this PR or have separate PR to remove.

maybe best to have it removed in a separate PR, @1480c1 , are we building the master ffmpeg now / tag?

**Comment by 1480c1** [comment]
> > > > > > Valgrind is actually failing https://travis-ci.com/github/OpenVisualCloud/SVT-AV1/jobs/364409634 . anyone working on it?
> > > > > 
> > > > > 
> > > > > I believe it is fixed now with the latest commit.
> > > > 
> > > > 
> > > > ```
> > > > ==9126== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
> > > > ```
> > > > 
> > > > 
> > > > seems so
> > > > btw, the mingw-w64 error is due to the fact that the patch was upstream last night [FFmpeg/FFmpeg@0e20dee](https://github.com/FFmpeg/FFmpeg/commit/0e20dee5c21a40f23ecfe7af2c360493a169c0f0) so the patch no longer applies onto the master branch anymore
> > > 
> > > 
> > > what can we do about this, should we remove the patch ?
> > 
> > 
> > I can remove it with this PR or have separate PR to remove.
> 
> maybe best to have it removed in a separate PR, @1480c1 , are we building the master ffmpeg now / tag?

Currently, we are building master for mingw-w64 job to make sure there's no symbol conflicts with the master branch and to make sure the patch would apply on the master branch there, but we were testing the 4.2 tag with the Linux and macOS jobs to make sure it still works there as well. I am planning to make it both use the master branch with the mainlined changes

**Comment by hassount** [comment]
> > > > > > > Valgrind is actually failing https://travis-ci.com/github/OpenVisualCloud/SVT-AV1/jobs/364409634 . anyone working on it?
> > > > > > 
> > > > > > 
> > > > > > I believe it is fixed now with the latest commit.
> > > > > 
> > > > > 
> > > > > ```
> > > > > ==9126== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
> > > > > ```
> > > > > 
> > > > > 
> > > > > seems so
> > > > > btw, the mingw-w64 error is due to the fact that the patch was upstream last night [FFmpeg/FFmpeg@0e20dee](https://github.com/FFmpeg/FFmpeg/commit/0e20dee5c21a40f23ecfe7af2c360493a169c0f0) so the patch no longer applies onto the master branch anymore
> > > > 
> > > > 
> > > > what can we do about this, should we remove the patch ?
> > > 
> > > 
> > > I can remove it with this PR or have separate PR to remove.
> > 
> > 
> > maybe best to have it removed in a separate PR, @1480c1 , are we building the master ffmpeg now / tag?
> 
> Currently, we are building master for mingw-w64 job to make sure there's no symbol conflicts with the master branch and to make sure the patch would apply on the master branch there, but we were testing the 4.2 tag with the Linux and macOS jobs to make sure it still works there as well. I am planning to make it both use the master branch with the mainlined changes



> > > > > > > Valgrind is actually failing https://travis-ci.com/github/OpenVisualCloud/SVT-AV1/jobs/364409634 . anyone working on it?
> > > > > > 
> > > > > > 
> > > > > > I believe it is fixed now with the latest commit.
> > > > > 
> > > > > 
> > > > > ```
> > > > > ==9126== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
> > > > > ```
> > > > > 
> > > > > 
> > > > > seems so
> > > > > btw, the mingw-w64 error is due to the fact that the patch was upstream last night [FFmpeg/FFmpeg@0e20dee](https://github.com/FFmpeg/FFmpeg/commit/0e20dee5c21a40f23ecfe7af2c360493a169c0f0) so the patch no longer applies onto the master branch anymore
> > > > 
> > > > 
> > > > what can we do about this, should we remove the patch ?
> > > 
> > > 
> > > I can remove it with this PR or have separate PR to remove.
> > 
> > 
> > maybe best to have it removed in a separate PR, @1480c1 , are we building the master ffmpeg now / tag?
> 
> Currently, we are building master for mingw-w64 job to make sure there's no symbol conflicts with the master branch and to make sure the patch would apply on the master branch there, but we were testing the 4.2 tag with the Linux and macOS jobs to make sure it still works there as well. I am planning to make it both use the master branch with the mainlined changes

thnx, can we then make something common with #1383 to get this done ?

**Comment by 1480c1** [comment]
> > > > > > > > Valgrind is actually failing https://travis-ci.com/github/OpenVisualCloud/SVT-AV1/jobs/364409634 . anyone working on it?
> > > > > > > 
> > > > > > > 
> > > > > > > I believe it is fixed now with the latest commit.
> > > > > > 
> > > > > > 
> > > > > > ```
> > > > > > ==9126== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > seems so
> > > > > > btw, the mingw-w64 error is due to the fact that the patch was upstream last night [FFmpeg/FFmpeg@0e20dee](https://github.com/FFmpeg/FFmpeg/commit/0e20dee5c21a40f23ecfe7af2c360493a169c0f0) so the patch no longer applies onto the master branch anymore
> > > > > 
> > > > > 
> > > > > what can we do about this, should we remove the patch ?
> > > > 
> > > > 
> > > > I can remove it with this PR or have separate PR to remove.
> > > 
> > > 
> > > maybe best to have it removed in a separate PR, @1480c1 , are we building the master ffmpeg now / tag?
> > 
> > 
> > Currently, we are building master for mingw-w64 job to make sure there's no symbol conflicts with the master branch and to make sure the patch would apply on the master branch there, but we were testing the 4.2 tag with the Linux and macOS jobs to make sure it still works there as well. I am planning to make it both use the master branch with the mainlined changes
> 
> > > > > > > > Valgrind is actually failing https://travis-ci.com/github/OpenVisualCloud/SVT-AV1/jobs/364409634 . anyone working on it?
> > > > > > > 
> > > > > > > 
> > > > > > > I believe it is fixed now with the latest commit.
> > > > > > 
> > > > > > 
> > > > > > ```
> > > > > > ==9126== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > seems so
> > > > > > btw, the mingw-w64 error is due to the fact that the patch was upstream last night [FFmpeg/FFmpeg@0e20dee](https://github.com/FFmpeg/FFmpeg/commit/0e20dee5c21a40f23ecfe7af2c360493a169c0f0) so the patch no longer applies onto the master branch anymore
> > > > > 
> > > > > 
> > > > > what can we do about this, should we remove the patch ?
> > > > 
> > > > 
> > > > I can remove it with this PR or have separate PR to remove.
> > > 
> > > 
> > > maybe best to have it removed in a separate PR, @1480c1 , are we building the master ffmpeg now / tag?
> > 
> > 
> > Currently, we are building master for mingw-w64 job to make sure there's no symbol conflicts with the master branch and to make sure the patch would apply on the master branch there, but we were testing the 4.2 tag with the Linux and macOS jobs to make sure it still works there as well. I am planning to make it both use the master branch with the mainlined changes
> 
> thnx, can we then make something common with #1383 to get this done ?

Yep, that's the plan

**Pull request merged**
