### PR TITLE
Decoder: Added support for Tiles and 10bit

### PR DESCRIPTION
**Pull request by nijilk**
Decoder: Added support for Tiles and 10bit
Bug fixes related to incomplete SB access at frame boundary

### CODE REVIEW

**Comment by EwoutH** [comment]
Could you also update the [svt-av1_decoder_user_guide.md](https://github.com/OpenVisualCloud/SVT-AV1/blob/master/Docs/svt-av1_decoder_user_guide.md) with the new capabilities?

**Comment by nijilk** [comment]
> Could you also update the [svt-av1_decoder_user_guide.md](https://github.com/OpenVisualCloud/SVT-AV1/blob/master/Docs/svt-av1_decoder_user_guide.md) with the new capabilities?

I will modify the user guide.

**Comment by kylophone** [comment]
Add a line to the changelog too

**Comment by nijilk** [comment]
> Add a line to the changelog too

Please review the changes below. Is this convention fine?

## [upcoming]
- Static library support  
- Alt-ref pictures - temporal filtering

## [0.5.0] - 2019-05-17

- 8 bit / 10 bit 4:2:0 up to 4k60p resolutions
- Presets 0-8
- New API, FFmpeg, GStreamer plugins
- Rate control support  (VBR, CVBR)
- Block sizes from 4x4 to 128x128
- Non-square blocks
- Tiles
- Deblocking / CDEF / Restoration filters
- Film Grain
- Warped motion estimation
- Intra block copy
- Trellis quantized coefficient optimization
- Support for 4 and 5 layers prediction structures
- Chroma search in MD
- Multi-reference picture support

## Decoder [0.5.0] - 2019-05-29

- 8 bit / 10 bit 4:2:0
- Tiles
- Intra only, without screen content tools

**Comment by kylophone** [comment]
> > Add a line to the changelog too
> 
> Please review the changes below. Is this convention fine?

Add these things to the upcoming section at the top. Thanks!

**Comment by nijilk** [comment]
> > > Add a line to the changelog too
> > 
> > 
> > Please review the changes below. Is this convention fine?
> 
> Add these things to the upcoming section at the top. Thanks!

Hi,
Please review and confirm the changes.

## [upcoming]
- Static library support  
- Alt-ref pictures - temporal filtering
- Decoder - Added support for Tiles and 10bit

## [0.5.0] - 2019-05-17

- 8 bit / 10 bit 4:2:0 up to 4k60p resolutions
- Presets 0-8
- New API, FFmpeg, GStreamer plugins
- Rate control support  (VBR, CVBR)
- Block sizes from 4x4 to 128x128
- Non-square blocks
- Tiles
- Deblocking / CDEF / Restoration filters
- Film Grain
- Warped motion estimation
- Intra block copy
- Trellis quantized coefficient optimization
- Support for 4 and 5 layers prediction structures
- Chroma search in MD
- Multi-reference picture support

**Comment by kylophone** [comment]
Looks good.

**Comment by nijilk** [comment]
> Looks good.

Thanks

**Pull request merged**
