### PR TITLE
1080p60

### PR DESCRIPTION
**Pull request by okhlif**
Update M0 to M8 ( 1080p60)

### CODE REVIEW

**Comment by 1480c1** [comment]
> Warning on MacOS:
> 
> [ 83%] Building C object Source/Lib/Codec/CMakeFiles/SvtAv1Enc.dir/EbUtility.c.o
> /code/SVTAV1/ovc_SVT-AV1/Source/Lib/Codec/EbUtility.c:34:16: warning: unknown attribute 'optimize' ignored
> [-Wunknown-attributes]
> **attribute**((optimize("unroll-loops")))
> ^
> 1 warning generated.

Maybe just surround it with `#ifndef __clang__` since clang doesn't support `__attribute__((optimize("unroll-loops")))`.

Addition after seeing the commit: Maybe still better to use ifndef clang so that way it doesn't produce the error even if linux+clang

**Comment by hassount** [comment]
> Warning on MacOS:
> 
> [ 83%] Building C object Source/Lib/Codec/CMakeFiles/SvtAv1Enc.dir/EbUtility.c.o
> /code/SVTAV1/ovc_SVT-AV1/Source/Lib/Codec/EbUtility.c:34:16: warning: unknown attribute 'optimize' ignored
> [-Wunknown-attributes]
> **attribute**((optimize("unroll-loops")))
> ^
> 1 warning generated.

Done, restricted to linux only as mac os seems to not associate that attribute with static functions anyways.

**Comment by 1480c1** [comment]
https://godbolt.org/z/R2l5tL

**Comment by hassount** [comment]
is __clang defined under __gnuc ? because it was `#ifdef __GNUC__` and the warning still popped up.

**Comment by 1480c1** [comment]
clang defines __GNUC__

**Comment by 1480c1** [comment]
```
ccom-macpro:~ ccom1$ clang -dM -E -x c /dev/null | grep -i gnuc
#define __GNUC_MINOR__ 2
#define __GNUC_PATCHLEVEL__ 1
#define __GNUC_STDC_INLINE__ 1
#define __GNUC__ 4
```

**Comment by hassount** [comment]
@okhlif 
Can you please fix the linux warning due to the 6ef3410 commit ?

**Pull request merged**
