### PR TITLE
eb_av1_highbd_quantize_fp_avx2: fix stack overwrite

### PR DESCRIPTION
**Pull request by xuguangxin**
it's introduced by https://github.com/OpenVisualCloud/SVT-AV1/commit/f29b8124c938c370c1ed0036be48776209becee1

### CODE REVIEW

**Comment by xuguangxin** [comment]
this issue cased ci fail like this https://travis-ci.com/OpenVisualCloud/SVT-AV1/jobs/268437309#L570

test:
SvtAv1EncApp -enc-mode 0 -i Chimera-Aerial_480x264_2997fps_10bit_420_150frames.y4m -n 3

crashed as:
Thread 353 "SvtAv1EncApp" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffd48aba700 (LWP 219719)]
0x00007fffebdfb0f0 in eb_av1_highbd_quantize_fp_avx2 (coeff_ptr=0x0, n_coeffs=0, zbin_ptr=0x100000001, round_ptr=0x1000100010000, quant_ptr=0x0, quant_shift_ptr=0x0, qcoeff_ptr=0x100000001, dqcoeff_ptr=0x1000100010001, dequant_ptr=0x0, eob_ptr=0x0, scan=0x0, iscan=0x0, log_scale=0)
    at /home/thomas/codec/SVT-AV1/Source/Lib/Common/ASM_AVX2/highbd_quantize_intrin_avx2.c:936

**Comment by xuguangxin** [comment]
hmm, the issue fixed on linux but it still fail on mac, need some one has mac to help on this

**Comment by joelsole** [comment]
I was working on the same issue - you can check my suggested changes at:
https://github.com/OpenVisualCloud/SVT-AV1/tree/fix_10b_crash_macos
Please, test if that one works for you.

**Comment by joelsole** [comment]
Note that there are other issues, since travis is running the C code:
[asm level selected : up to c]
while this fix is for avx2.

**Comment by xuguangxin** [comment]
@joelsole , thanks for explain. 
close this for https://github.com/OpenVisualCloud/SVT-AV1/pull/911

**Pull request closed without merging**
