### PR TITLE
Cherry pick bug fixes in SVT-HEVC

### PR DESCRIPTION
**Pull request by lzhangnj**
commit 1c3369bd:
Author: cabirdme
SadLoopKernel(AVX2) and SadLoopKernelHme0(AVX2/AVX512)

commit 0e43ee38:
Author: lzhangnj
Fix a bug in SadLoopKernel_AVX2_HmeL0_INTRIN() and SadLoopKernel_AVX512_HmeL0_INTRIN()

### CODE REVIEW

**Comment by hassount** [comment]
Performed some BD-rate tests on this PR and it seems that it's hurting quality significantly, @lzhangnj  any thoughts ? maybe a missing fix in another function? 

Reference:   301_OFF_M5 |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
fullset | PSNR | SSIM | AVG   PSNR/SSIM
svt-av1 |   | libaom | Y | U | V | YUV | Y | U | V | YUV | YUV
301_M5 | vs. | aomlib-2Pass_M0 | -0.2% | 2.9% | 2.9% | 0.7% | 2.2% | 4.4% | 4.3% | 2.6% | 1.6%
  |   |   |   |   |   |   |   |   |   |   |  
Reference:   06-04_master_M0 |   |   |   |   |   |   |   |   |  
fullset (excl. wiki) | PSNR | SSIM | AVG   PSNR/SSIM
svt-av1 |   | libaom | Y | U | V | YUV | Y | U | V | YUV | YUV
301_M0 | vs. | aomlib-2Pass_M0 | 8.2% | 12.6% | 13.1% | 9.3% | 8.1% | 13.9% | 14.3% | 9.0% | 9.1%

**Comment by lzhangnj** [comment]
Sorry that I couldn't reproduce the large quality drop. I always got bit-exact encoding results. Anyway, I reverted the 2nd bug fix to narrow down potential issues.

There is definitely another bug in calling sad_loop_kernel_avx2_hme_l0_intrin() which passes in wrong str_stride when it's not FULL_SAD_SEARCH. However, the passed in wrong str_stride is always 16 and hence the 2nd bug fix has no influence to the final encoding result in current code base.

Similarly, the bug fix accidentally pushed to OpenVisualCloud/SVT-HEVC:master (0e43ee38) should also not change any encoding results in any speed mode.

**Comment by hassount** [comment]
@lzhangnj 
Thank you for looking into this, unfortunately we're still seeing a loss even after the last commit. 
@tianjunwork 
can we test this in SVT-HEVC and check if it's giving the same loss ? if so we'd need to revert that commit  from master (assuming it's in) until we address this item

**Comment by tianjunwork** [comment]
@hassount you want BD-rate tests on HEVC with or without the changes of this PR, not the original PR (https://github.com/OpenVisualCloud/SVT-HEVC/commit/22e327d32decf24b4622a8b3f46c8d245c74cc6e), right?

**Comment by hassount** [comment]
I was referring to this, https://github.com/OpenVisualCloud/SVT-HEVC/pull/195 so if we test the PR on and off do we get the same effect ?

**Comment by tianjunwork** [comment]
@hassount  I run ffmpeg PSNR comparison with OpenVisualCloud/SVT-HEVC#195 on and off. The two psnr are the same.

**Comment by hassount** [comment]
> @hassount I run ffmpeg PSNR comparison with [OpenVisualCloud/SVT-HEVC#195](https://github.com/OpenVisualCloud/SVT-HEVC/pull/195) on and off. The two psnr are the same.

Cool, thank you Jun, let's hope then that this is a bug specific to SVT-AV1 that we can address. @lzhangnj  Would you please be able to check if the calling functions are the same in svt-hevc and svt-av1 ?

**Comment by lzhangnj** [comment]
The calling functions are different, and both have potential bugs in different places by passing in wrong src_stride in down-sampling SAD search case, which should be doubled.

@tianjunwork Could you please tell me the settings of the OS, compiler version, speed mode and other encoding settings, input video sequence etc? Sorry that I cannot reproduce the performance drop in my side. Thanks!

**Comment by tianjunwork** [comment]
Hi @lzhangnj I didn't see performance drop with OpenVisualCloud/SVT-HEVC#195.

**Comment by lzhangnj** [comment]
Hi @tianjunwork I mean the reported huge performance drop of this PR in SVT-AV1. Thanks.

**Comment by tianjunwork** [comment]
> Hi @tianjunwork I mean the reported huge performance drop of this PR in SVT-AV1. Thanks.

Hi @lzhangnj, it is not me reported the performance drop. Sorry that I can't help on that:)

**Pull request merged**
