### PR TITLE
Cppcheck-point 3

### PR DESCRIPTION
**Pull request by 1480c1**
# Description

Resolves even more cppcheck issues.

I can either roll this into #1335, or keep it separate depending on if it would be easier to review that way.

# Issue

None

# Author(s)
@1480c1

# Performance impact

- [ ] quality
- [ ] memory
- [ ] speed
- [ ] 8 bit
- [ ] 10 bit
- [x] N/A

# Test set
- [x] obj-1-fast can be found [here](https://media.xiph.org/video/derf/objective-1-fast.tar.gz)
- [ ] other
- [ ] N/A

# Merge method
- [x] Allow the maintainer to squash and merge when PR is ready to create a 1-commit to the master branch. The maintainer will be able to fix typos / combine commit messages to create a more readable 1-commit message or use whatever is stated in the 'Description' section
- [ ] I will clean up my commits and the maintainer shall use 'rebase and merge' to the master branch

### CODE REVIEW

**Comment by EricLamVCD** [comment]
Tested commit ac5c5c7 obj-1 8bit and 10bit clips: 
  | Speed Deviation  | BD-Rate   Deviation | Memory   Deviation
-- | -- | -- | --
M0 - 8bit | -1.43% | 0.04% | 0.00%
M4 - 8bit | -1.43% | 0.00% | 0.00%
M8 - 8bit | -1.43% | 0.00% | 0.00%
M0 - 10bit | -1.43% | 0.03% | 0.00%
M4 - 10bit | -1.43% | -0.02% | 0.00%
M8 - 10bit | -1.43% | 0.00% | 0.00%

Results are lossy

**Comment by 1480c1** [comment]
After retesting with objective-1-fast, it seems the lossy issues went away

**Comment by hassount** [comment]
Ok let’s rebase this and give it another try with testing.

**Comment by 1480c1** [comment]
Testing with object-2-slow, other than the clips mentioned in https://github.com/OpenVisualCloud/SVT-AV1/issues/1312, all of them passed, rerunning again just to make sure, but opening the PR for review

**Comment by hassount** [comment]
alright @OmranAbdelkafi let's get another validation round into this.

**Comment by EricLamVCD** [comment]
Tested obj-1 8bit clips for commit b0e718f : 
  | Speed Deviation  | BD-Rate   Deviation | Memory   Deviation
-- | -- | -- | --
M0 - 8bit | 0.81% | 0.00% | 0.00%
M4 - 8bit | -0.34% | 0.00% | 0.01%
M8 - 8bit | -0.44% | 0.00% | 0.00%

**Pull request merged**
