### PR TITLE
[RFC] consistent namespacing for public API functions

### PR DESCRIPTION
**Pull request by elenril**
sending this PR primarily for gathering feedback on API namespacing, I do not
actually expect it to be merged in its current form.

SVT-AV1 currently uses `eb_` as the prefix for public functions, but I see
multiple problems with it:
-    it is used across several separate projects, causing symbol conflicts
-    it is used for both public and private functions, making it harder to
     distinguish between them
-    as far as I can tell, it's used mainly for historical reasons and it does
     not carry much meaning for the API users

Since the library API is not stable yet, these problems can still be addressed
without breaking compatibility. It thus seems reasonable to pick a prefix that
would be
-    meaningful for the end-users
-    unique for SVT-AV1
-    used for public functions only (it would also be good to pick a consistent
     prefix to be used for non-static private functions, to avoid conflicts with
     static linking, but that's a separate question)
-    ideally short, so it's easy to write
and officially document it as the reserved namespace for this library.

I am proposing `svt_av1_` in this PR. It satisfies all the points above, except
possibly the last one. `svtav1_` is also possible, but starts looking like
character soup, which is IMO not worth it for saving one character.

Thoughts? Opinions? Bikeshed colorscheme preferenes? Do you even see this as
a worthwhile issue to address?

### CODE REVIEW

**Comment by hassount** [comment]
@elenril 
Thank you for the PR and the detailed explanation. 
I agree that changing the prefixes and standardizing them would definitely be beneficial. and doing so now is definitely the best time. 
A few things to keep in mind:
- we probably need to define a prefix for the functions coming from libaom.
- we also need to keep in mind the other svt libraries and work with the maintaining teams with this get done to port the same logic over. 

Now, there will be a major PR moving files to the enc / dec / common directories we can get this work moving soon afterwards.

**Comment by jbkempf** [comment]
> A few things to keep in mind:
>     * we probably need to define a prefix for the functions coming from libaom.

They should not be exposed in the API, and should be hidden from the SO.

**Comment by hassount** [comment]
> > A few things to keep in mind:
> > * we probably need to define a prefix for the functions coming from libaom.
> 
> They should not be exposed in the API, and should be hidden from the SO.

Agreed, that said, when we build a static build and link it to ffmpeg then we get the symbol conflict. do you know another way of solving this apart from re-naming (assuming we can not declare them all as static) ?

**Comment by jbkempf** [comment]
> Agreed, that said, when we build a static build and link it to ffmpeg then we get the symbol conflict.

Conflict with what?

**Comment by 1480c1** [comment]
There are currently conflicts with libaom and one other library iirc https://github.com/OpenVisualCloud/SVT-AV1/issues/567

**Comment by elenril** [comment]
Quoting Hassene Tmar (2020-01-13 00:21:59)
> @elenril 
> Thank you for the PR and the detailed explanation. 
> I agree that changing the prefixes and standardizing them would
> definitely be beneficial. and doing so now is definitely the best
> time. 
> A few things to keep in mind:
> - we probably need to define a prefix for the functions coming from libaom.

I imagine those should be treated as any other non-static private
functions and
- not exported from dynamic libraries (as JB already said)
- converted to used some unified private prefix - however that would be a
  separate PR

> - we also need to keep in mind the other svt libraries and work with
> the maintaining teams with this get done to port the same logic over. 

Certainly. I intend to file analogous PRs there as well.

> 
> Now, there will be a major PR moving files to the enc / dec / common
> directories we can get this work moving soon afterwards.

Is there any timeline for that. I would rather not postpone this too
much, especially since it's just a simple rename.

**Comment by elenril** [comment]
Updated PR:
- rebased against current master
- covers both encoder and decoder

-- 
Anton Khirnov

**Comment by hassount** [comment]
@joelsole @kylophone @mafonsoN @andrey-norkin any issues with this PR ?

**Comment by ibex-are-goats** [comment]
Hello, I'm just observing you work, and I hope everyone is staying safe! 

The only thing I will add here is grammatical. In the official documentation and websites that I've seen, whether at Intel.com or Github.com, the name of this project/codebase/tool is SVT-AV1 with a hyphen, not a space. Same with SVT-HEVC. And in programming convention I think the underscore "_" is synonymous with a space " ", not a hyphen.

So I think technically we would be looking at "svt-av1_dec_set_parameter", etc. 

Have a great weekend and keep pushing the state of the art, everyone!

**Comment by hassount** [comment]
> Hello, I'm just observing you work, and I hope everyone is staying safe!
> 
> The only thing I will add here is grammatical. In the official documentation and websites that I've seen, whether at Intel.com or Github.com, the name of this project/codebase/tool is SVT-AV1 with a hyphen, not a space. Same with SVT-HEVC. And in programming convention I think the underscore "_" is synonymous with a space " ", not a hyphen.
> 
> So I think technically we would be looking at "svt-av1_dec_set_parameter", etc.
> 
> Have a great weekend and keep pushing the state of the art, everyone!

@ibex-are-goats 
thank you for your comment. while it is agreeable that such would be more grammatical, in C / Cpp and presumable other languages, the dash is considered a minus sign so we can not use it in variable / function names

**Comment by hassount** [comment]
> @joelsole @kylophone @mafonsoN @andrey-norkin any issues with this PR ?

@joelsole @kylophone @mafonsoN @andrey-norkin any issues with this PR ?

**Comment by jbkempf** [comment]
Yay \o/

**Comment by EwoutH** [comment]
Seems that the CI broke after merging this PR

**Comment by hassount** [comment]
> Seems that the CI broke after merging this PR

it's appveyor that hit the limit, this PR can no break ci as it is just renaming the api calls.

**Pull request merged**
