### PR TITLE
Update eb_av1_jnt_convolve_2d_avx2()

### PR DESCRIPTION
**Pull request by lzhangnj**
Speed comparision is between 1.09x and 2.24x.

    Blk Size | Tap 2    4    6    8
        4x 4 |  1.38  1.42 N/A  N/A
        4x 8 |  1.32  N/A  N/A  N/A
        8x 4 |  1.33  N/A  N/A  N/A
        8x 8 |  1.26  N/A  1.26 1.09
       8x 16 |  1.24  N/A  1.39 1.16
       16x 8 |  1.52  N/A  1.41 1.17
      16x 16 |  1.50  N/A  1.51 1.23
      16x 32 |  1.55  N/A  1.59 1.29
      32x 16 |  2.00  N/A  1.77 1.40
      32x 32 |  1.95  N/A  1.77 1.42
      32x 64 |  1.93  N/A  1.83 1.48
      64x 32 |  2.13  N/A  1.82 1.43
      64x 64 |  1.66  N/A  1.74 1.46
      64x128 |  1.47  N/A  1.56 1.38
     128x 64 |  1.89  N/A  1.73 1.43
     128x128 |  1.86  N/A  1.66 1.40
       4x 16 |  1.34  N/A  N/A  N/A
       16x 4 |  1.63  N/A  N/A  N/A
       8x 32 |  1.25  N/A  1.49 1.24
       32x 8 |  2.03  N/A  1.66 1.31
      16x 64 |  1.62  N/A  1.70 1.38
      64x 16 |  2.24  N/A  1.83 1.41

### CODE REVIEW

**Comment by JackZhouVCD** [comment]
Bitstreams matched for all encode modes after applying the PR, and I'm seeing a ~0.4% speed deviation averaged over M{1,4,8}. lgtm

**Comment by lzhangnj** [comment]
> Bitstreams matched for all encode modes after applying the PR, and I'm seeing a ~0.4% speed deviation averaged over M{1,4,8}. lgtm

Hi Jack, Thanks for your thorough testing!

**Comment by hassount** [comment]
@ttrigui good to go ?

**Comment by ttrigui** [comment]
> @ttrigui good to go ?

yes

**Pull request merged**
