### PR TITLE
Readermock: Add OD_EC_WINDOW_SIZE from EbDecBitstreamUnit.h

### PR DESCRIPTION
**Pull request by 1480c1**

### CODE REVIEW

**Comment by kylophone** [comment]
Can you explain what this is?

**Comment by 1480c1** [comment]
From https://travis-ci.org/OpenVisualCloud/SVT-AV1/jobs/538791595#L672, it seems that OD_EC_WINDOW_SIZE is not defined at all in the header and BitstreamReaderMock.cc, but it exists in EbDecBitstreamUnit.h. I'm assuming that @Cidana-Developers copied part of the code over, but failed to copy over the defs.

**Comment by Cidana-Developers** [comment]
> From https://travis-ci.org/OpenVisualCloud/SVT-AV1/jobs/538791595#L672, it seems that OD_EC_WINDOW_SIZE is not defined at all in the header and BitstreamReaderMock.cc, but it exists in EbDecBitstreamUnit.h. I'm assuming that @Cidana-Developers copied part of the code over, but failed to copy over the defs.

The definition of OC_EC_WINDOW_SIZE has been moved to EbDecBitstreamUnit.h since c7b108ad518b2f223fa7d56c3fdbd482086bc261, which will break the build. #282 will fix this issue.

**Comment by 1480c1** [comment]
Okay, will close

**Pull request closed without merging**
