### PR TITLE
packetization_kernel: pack entire temproal unit for a output buffer

### PR DESCRIPTION
**Pull request by xuguangxin**
Currently, we output one frame per get ouptut, and the "show existing frame" shares the same pts with the previous frame.
This will introduce jitter to "show existing frame" and the previous frame.
We should output a temporal unit a time.
A temporal unit includes one TD + zero or more undisplay frame + one display frame.
And we need to stamp a different pts for show existing frame since it is a displayable frame.

after apply this patch, ffmpeg will not report error for following test command:
ffmpeg -i 320x240.y4m -c:v libsvt_av1 -vframes 100 test.mkv  -y &&  ffmpeg -c:v libdav1d -i test.mkv -f null /dev/null

and ffmpeg will not insert td for every frame if we use following command:
ffmpeg -i 320x240.y4m -c:v libsvt_av1 -vframes 100 test.ivf  -y

fixes https://github.com/OpenVisualCloud/SVT-AV1/issues/129, fixes https://github.com/OpenVisualCloud/SVT-AV1/issues/33

### CODE REVIEW

**Comment by xuguangxin** [comment]
@Cidana-Developers please help check unit test part.
thanks

**Comment by Cidana-Developers** [comment]
> @Cidana-Developers please help check unit test part.
> thanks

The changes are OK, thank you!

**Comment by kylophone** [comment]
LGTM. Please squash before merging.

**Comment by hassount** [comment]
@xuguangxin thank you very much for this PR as it addressed multiple issues. 
we ran several tests and have noticed that in regular encodes, there's no difference between the bitstreams with your changes and without. 
however, when using tiles, we notice an extra TD and Frame header that gets sent at the very end of the bitstream as compared to the master base of your branch using tiles too. 
the command line parameters is as follows:
-i in.yuv -w 176 -h 144 -b out.ivf -tile-rows 1 -tile-columns 1

Can you explain why we have the extra overhead ?

**Comment by oddstone** [comment]
Hi @hassount ,
Could you share more details? Use your comandline, with or without the patch,  I can get bit matched result.
thanks

[bits.zip](https://github.com/OpenVisualCloud/SVT-AV1/files/4243023/bits.zip)

**Comment by hassount** [comment]
> Hi @hassount ,
> Could you share more details? Use your comandline, with or without the patch, I can get bit matched result.
> thanks
> 
> [bits.zip](https://github.com/OpenVisualCloud/SVT-AV1/files/4243023/bits.zip)

It seems like one of the bitstreams I got was missing 6 bytes at the end of the stream. I was not able to reproduce the mismatch. sorry about the false alarm.

**Comment by xuguangxin** [comment]
It's ok。  :)

**Comment by hassount** [comment]
@xuguangxin 
found a way to reproduce the issue that I was seeing. 

-i blue_sky_360p_60f.yuv -o rec.yuv -intra-period 200 -enc-mode 8 -n 25  -q 40  -lp 1 -lad 0 -b 1.ivf  -w 640 -h 360

the encoder will encode only 24 frames. @xuguangxin could you please take a look at this, seems like an overlay header is missing

**Comment by xuguangxin** [comment]
sure I will check this.
thanks for the comandline

**Comment by xuguangxin** [comment]
@hassount 
It will fix by https://github.com/OpenVisualCloud/SVT-AV1/pull/1092.

**Pull request merged**
