### PR TITLE
Signal(s) clean-up

### PR DESCRIPTION
**Pull request by hguermaz**
## Description

- Removed enable_trellis, nx4_4xn_parent_mv_inject, rdoq_quantize_fp, is_nsq_table_used, md_intra_open_loop_flag, limit_intra, do_recon, do_mc, do_mvpred.

- Renamed md_fast_cost_cand_prune_th, md_fast_cost_class_prune_th, md_full_cost_cand_prune_th , md_full_cost_class_prune_th to md_stage_1_cand_prune_th, md_stage_1_class_prune_th, md_stage_2_3_cand_prune_th, md_stage_2_3_class_prune_th.

- Removed NN/ML files.
 
## Testing and Performance

Identical streams in M0.  ~0% speed deviation and no memory footprint deviation.

### CODE REVIEW

**Comment by hassount** [comment]
@hguermaz thank you for the cleanup, 

can you please update the users guide and the configuration files accordingly ?

**Comment by hguermaz** [comment]
@hassount done

**Comment by hguermaz** [comment]
@ttrigui  @hassount please make sure to apply same clean-up to the 16BIT path

**Comment by hguermaz** [comment]
@mafonsoN  is this good to go ?

**Pull request merged**
