### PR TITLE
Speed optimization

### LINKED ISSUE #593: m0-test faster than master
Not all speed optimization(s) ported from m0-test to master

### PR DESCRIPTION
**Pull request by hguermaz**
## Description
Added the following lossy speed optimizations:
- Opt 0: Use the top 4 ME candidates only @ 3x3 Unipred and 3x3 Bipred.
- Opt 1: Skip ATB if parent block does not have coeff.
- Opt 2: Use edge detection to bypass some angular modes.
- Opt 3: Bipred candidates reduction @ ME.
- Opt 4: MD candidates reduction @ MD.

Closes #593  

## Author

@NaderMahdi 
@chkngit  
@hguermaz 

## Type of change

New feature/Tool

## Tests and performance
* BD-Rate to aom cpu0-2pass on the full list: Opt 0: 0.020% loss, Opt 1: 0.023%, Opt 2: 0.029%, Opt 3: M1 & higher tool , Opt 4: M1 & higher too.l 
* Speed on a 4-core machine:  Opt 0: 30% faster, Opt 1: 0.9% faster, Opt 2: 1.5% faster, Opt 3: M1 & higher tool , Opt 4: M1 & higher too.l 
* Memory footprint on a 4-core machine: negligible

### CODE REVIEW

**Comment by mafonsoN** [comment]
@hguermaz Opt 0 is 30% faster for M0 on a 4-core machine?

**Comment by hguermaz** [comment]
Correct. Opt 0 is 30% faster for M0 on a 4-core machine, and 0.020% BD-Rate loss on the full list. Adopted for all presets (even for MR_MODE)

**Comment by hguermaz** [comment]
@mafonsoN. If no concerns,  can we go ahead and merge this PR.

**Comment by mafonsoN** [comment]
> @mafonsoN. If no concerns, can we go ahead and merge this PR.

@hguermaz We are planning to do some internal tests and then we can go ahead and merge it.

**Comment by kylophone** [comment]
It would nice if there was a test to check for equivalence between C and AVX2 functions.

**Comment by mafonsoN** [comment]
@hguermaz Can you please fix this warning I got on linux using gcc 5.4.0? 

```
/home/mafonso/SVT-AV1/Source/Lib/Decoder/Codec/EbDecParseBlock.c: In function ‘parse_residual’:
/home/mafonso/SVT-AV1/Source/Lib/Decoder/Codec/EbDecParseBlock.c:2534:41: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                     assert(total_num_tu ==
                                         ^
```

**Comment by hguermaz** [comment]
Linux gcc 5.4. build warning fixed

**Comment by EwoutH** [comment]
@hguermaz Could you rebase your branch on the current master?

**Comment by hguermaz** [comment]
@mafonsoN
1. For PA operation(s) that depend on ENC_MODE (PA multi-mode-feature(s) = PA mm-feature(s)),  the settings could not be derived @ EncDec Process (a close loop Process). The settings for PA operation(s) that depend on ENC_MODE are now derived @ Picture Decision Process () (an early PA process and where picture type is known), then stored under the parent PCS to be seen by all PA processes (e.g.  Motion Estimation Process). 

This particular PR adds 4 mm-signals; 2 derived @ EncDec Process, and 2 derived @ Picture decision Process. Regarding the 2 derived @ Picture decision Process; 1 is used @ Motion Estimation Process, and the 2nd is actually not used by PA and could be derived @ the EncDec Process.

2. I agree, and actually we might use a variable instead of a macro definition in future (i.e. make it = f(ENC_MODE).

**Comment by mafonsoN** [comment]
> @mafonsoN
> 
> 1. For PA operation(s) that depend on ENC_MODE (PA multi-mode-feature(s) = PA mm-feature(s)),  the settings could not be derived @ EncDec Process (a close loop Process). The settings for PA operation(s) that depend on ENC_MODE are now derived @ Picture Decision Process () (an early PA process and where picture type is known), then stored under the parent PCS to be seen by all PA processes (e.g.  Motion Estimation Process).
> 
> This particular PR adds 4 mm-signals; 2 derived @ EncDec Process, and 2 derived @ Picture decision Process. Regarding the 2 derived @ Picture decision Process; 1 is used @ Motion Estimation Process (prune_unipred_at_me), and the 2nd is actually not used by PA and could be derived @ the EncDec Process (prune_ref_frame_for_rec_partitions).
> 
> 1. I agree, and actually we might use a variable instead of a macro definition in future (i.e. make it = f(ENC_MODE).

@hguermaz thanks for the reply. So, can you update it before we merge?

**Comment by hguermaz** [comment]
fixxed; moved prune_ref_frame_for_rec_partitions from parent PCS to EncDec context

**Pull request merged**
