### PR TITLE
Add Unit tests nightly runs

### PR DESCRIPTION
**Pull request by ePirat**
This adds unit tests to Github Actions to run each night at midnight (UTC).

Currently some tests fail and the tests take waaaay too long (over 6 hours).

### CODE REVIEW

**Comment by ePirat** [comment]
I've renamed the CI yml file, this was needed to get the schedule cron to actually work, apparently there is some quirk in Github Actions…

**Comment by ePirat** [comment]
(Marked as draft due to the issues mentioned in the entry post about tests taking too long, as this causes them to time out after 6 hours, which is the maximum limit a job can run on Github actions)

**Comment by EwoutH** [comment]
From the [GitHub Actions](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources) documentation:

> Each virtual machine has the same hardware resources available.
> - 2-core CPU
> - 7 GB of RAM memory
> - 14 GB of SSD disk space

If the Unit tests are scaling well over multiple tests, we should consider [hosting a runner ourselves](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/hosting-your-own-runners). That would be useful for gathering BDR metrics with the CI as well.

@kylophone or @hassount could you check if you have a machine available at this time and could hook it up? For now something with 8+ cores and 16+ GB RAM would suffice I think.

Part of #873.

**Comment by 1480c1** [comment]
Perhaps it might be better to separate out the cron based jobs into another file like `unit-test.yml`? That way anyone currently modifying the same file wont have a lot of conflicts

**Comment by ePirat** [comment]
@1480c1 of course possible but means we would need to copy paste the build instructions and have them duplicated in several files, which might be a bit annoying to maintain, but I have no strong preference. So whatever works best for you is fine for me.

**Comment by luigi311** [comment]
This is now easier to do and maintain with the ci script once that gets merged.

**Comment by ePirat** [comment]
This is already done in a different PR

**Pull request closed without merging**
