### PR TITLE
fix encoding for non multiple-of-8 pictures

### PR DESCRIPTION
**Pull request by kylophone**
Cherry-picked and rebased from the `cs2` branch. 

Co-authored-by: Jing Li <jing.b.li@intel.com>
Co-authored-by: chkngit <42250551+chkngit@users.noreply.github.com>
Signed-off-by: Jing Li <jing.b.li@intel.com>

### CODE REVIEW

**Comment by joelsole** [comment]
I did a couple of fast encodes and compared the SVT-AV1 reconstructed, SVT-AV1 decoded, and libaom decoded yuvs:
 - For 1 frame, the three outputs match
 - For 2 frames, SVT-AV1 recon & decoded match, but not libaom decoded
 - For 12 frames: the three outputs are different. 
This happened with the first two sequences picked, so I guess it is not a corner case.

Do you observe the same at your end?

**Comment by hassount** [comment]
> I did a couple of fast encodes and compared the SVT-AV1 reconstructed, SVT-AV1 decoded, and libaom decoded yuvs:
> 
> * For 1 frame, the three outputs match
> * For 2 frames, SVT-AV1 recon & decoded match, but not libaom decoded
> * For 12 frames: the three outputs are different.
>   This happened with the first two sequences picked, so I guess it is not a corner case.
> 
> Do you observe the same at your end?

I did an encode and the reconstructed vs the decoded (through ffmpeg / libaom decoder) have matched fully for 60 frames

**Comment by joelsole** [comment]
We can note that this PR is fixing the 8-bit case, merge it, and make an issue for fixing the 10-bit case.

**Comment by hassount** [comment]
Added #1225

**Pull request merged**
