### PR TITLE
travis: Fix Werror, set os and compiler for BinIden

### PR DESCRIPTION
**Pull request by 1480c1**
Defaults build_type to release and generator to Unix Makefiles
Sets OS and compiler for BinIden job to always use the same compiler and os

Forgot to export CFLAGS

Original PR was #428, can't push to Werror anymore even when deleting it everywhere

### CODE REVIEW

**Comment by kylophone** [comment]
Alright. So this adds `-Werror` to everything that's not MacOS? Looks like there are some warnings still in the Travis build. I guess we would have expected it to have failed, right?

**Comment by 1480c1** [comment]
> `Source/Lib/Common/ASM_SSE2/highbd_intrapred_sse2_.asm` should not be part of this diff.

Accidental save by vscode 

> Alright. So this adds `-Werror` to everything that's not MacOS? Looks like there are some warnings still in the Travis build. I guess we would have expected it to have failed, right?

Yea, mainly because for some reason, when `-Werror` is applied for macOS, one of the asm file gives an error https://travis-ci.com/1480c1/SVT-AV1/jobs/213675006#L1366

Seems there are still array bounds stuff from clang, but they are excluded for now

**Comment by kylophone** [comment]
> > `Source/Lib/Common/ASM_SSE2/highbd_intrapred_sse2_.asm` should not be part of this diff.
> 
> Accidental save by vscode
> 
> > Alright. So this adds `-Werror` to everything that's not MacOS? Looks like there are some warnings still in the Travis build. I guess we would have expected it to have failed, right?
> 
> Yea, mainly because for some reason, when `-Werror` is applied for macOS, one of the asm file gives an error https://travis-ci.com/1480c1/SVT-AV1/jobs/213675006#L1366
> 
> Seems there are still array bounds stuff from clang, but they are excluded for now

Ah, ok. Cool. I guess this can be merged once you remove the extraneous file from the diff.

**Comment by 1480c1** [comment]
Done

**Comment by kylophone** [comment]
Merged. Thanks.

**Pull request merged**
