### PR TITLE
Add aom_highbd_paeth_predictor kernel in AVX2.

### PR DESCRIPTION
**Pull request by spawlows**
Average speed up of all highbd_paeth_predictor: ~12 times.

### CODE REVIEW

**Comment by hassount** [comment]
@spawlows 
Could you please fix the conflicts on this ?

**Comment by EwoutH** [comment]
@spawlows Could you rebase?

**Comment by spawlows** [comment]
@EwoutH Done.

**Comment by EwoutH** [comment]
@hassount Any more reviews needed?

**Pull request merged**
