### PR TITLE
CI: Create initial GitHub Actions workflow

### PR DESCRIPTION
**Pull request by EwoutH**
GitHub Actions is weird. But it looks quite powerful, so here's an initial setup for a GitHub Actions Workflow.

This Action (I don't even know what it's called anymore) does nothing more than build SVT-AV1 on Ubuntu 18.04 LTS with GCC 9. This is an initial setup, the fact that this passes or not means nothing for now.

@kylophone @1480c1 Feel free to build out from here! I will probably try to port a lot of stuff over from Travis around Christmas.

Part of #4.

### CODE REVIEW

**Comment by EwoutH** [comment]
It doesn't seem to run yet. Maybe it needs to be merged first and/or be activated on https://github.com/OpenVisualCloud/SVT-AV1/actions

Here's an example on my fork: https://github.com/EwoutH/SVT-AV1/commit/3026050b527feda6e3f1fe9777912bd9fa7dc94f/checks?check_suite_id=348693980

**Comment by grill05** [comment]
@EwoutH This looks quite interesting. Could "github actions" be used to automate adding new data points for graphs at videocodectracker.dev ?

**Comment by EwoutH** [comment]
@grill05 Excellent question. At the moment, I don't know. We could maybe output artifacts that we load into videocodectracker.dev or an other database.

**Comment by ultrawide** [comment]
Hey, thanks for this. I'd love to contribute and experiment with github-actions as well. If there's anything  I can work on, let me know.

**Comment by EwoutH** [comment]
@ultrawide Thanks! Have your pick :) (see linked issue above)

**Comment by EwoutH** [comment]
Could this PR be merged today? Then others can build out from it.

**Comment by kylophone** [comment]
I wonder if it would make sense to try Github Actions for the Windows CI as a first step. Currently, our Appveyor account is full (see log below), afaict there's no way to set an expiration or manually delete old artifacts. You have to create a to support account and ask someone to give you more space. We've already done that once, iirc. @hassount may know about that. If my recollection is incorrect, somebody please correct me.

https://help.appveyor.com/discussions/problems/23644-maximum-allowed-artifact-storage-size-of-50000-mb-will-be-exceeded

```
Discovering tests...OK
Collecting artifacts...
Found artifact 'Bin\Release\Release\SvtAv1Dec.dll' matching 'bin\**\SvtAv1Dec.dll' path
Found artifact 'Bin\Release\Release\SvtAv1DecApp.exe' matching 'bin\**\SvtAv1DecApp.exe' path
Found artifact 'Bin\Release\Release\SvtAv1Enc.dll' matching 'bin\**\SvtAv1Enc.dll' path
Found artifact 'Bin\Release\Release\SvtAv1EncApp.exe' matching 'bin\**\SvtAv1EncApp.exe' path
Uploading artifacts...
Maximum allowed artifact storage size of 50000 Mb will be exceeded.
```

**Comment by EwoutH** [comment]
@kylophone We most likely can, just have to figure out artifacts and deployment. It's in #873, but this needs to be merged first.

Then we can run AppVeyor only on the master branch for example. For now I [requested](https://help.appveyor.com/discussions/problems/25635-maximum-allowed-artifact-storage-size-of-50000-mb-will-be-exceeded) our storage limit to be increased.

**Comment by hassount** [comment]
do we need a license header on these files ?

**Comment by 1480c1** [comment]
I don't think so since similar to the Travis and appveyor yaml files, it doesn't contain anything really worthy of licensing and it's more like writing bash snippets

**Comment by hassount** [comment]
> I don't think so since similar to the Travis and appveyor yaml files, it doesn't contain anything really worthy of licensing and it's more like writing bash snippets

yeah, I have a feeling that legal might disagree on this :) anyways, I ll follow up on the license for all of the files

**Comment by 1480c1** [comment]
> > I don't think so since similar to the Travis and appveyor yaml files, it doesn't contain anything really worthy of licensing and it's more like writing bash snippets
> 
> yeah, I have a feeling that legal might disagree on this :) anyways, I ll follow up on the license for all of the files

Please do, I personally have no clue on how to do proper licensing yet other than adding a top-level `LICENSE` file, which I'm not sure how much that affects anything

**Comment by EwoutH** [comment]
Can we merge?

**Pull request merged**
