### PR TITLE
Remove unnecessary memset when allocating YUV buffer

### LINKED ISSUE #1088: Does YUV buffer need to be CALLOC?
With PR #314, y,u,v buffer is calloced, which bring some regression to init time. 
Pictures show 4k input. With 8k input(tested with hevc), it is more obvious.
av1-bottomup

Before this PR:
av1-old-bottomup

### PR DESCRIPTION
**Pull request by tianjunwork**
Reduce init time the more the higher resolution.

Signed-off-by: Jun Tian <jun.tian@intel.com>

closes #1088

### CODE REVIEW

**Comment by tianjunwork** [comment]
Remove memset for YUV buffer in `eb_picture_buffer_desc_ctor, eb_recon_picture_buffer_desc_ctor`. Reduced ~2.1% CPU time for init with this PR:
av1-fix-topdown


HEAD:
av1-head-topdown

**Comment by tianjunwork** [comment]
```
/home/runner/work/SVT-AV1/SVT-AV1/test/NoiseExtractTest.cc:147: Failure
Expected equality of these values:
  0
  mismatch_samples_cb
    Which is: 2
2 cb samples are different.
/home/runner/work/SVT-AV1/SVT-AV1/test/NoiseExtractTest.cc:149: Failure
Expected equality of these values:
  0
```
If remove memset is the right thing to do, could some one help fix unit test? I am not familiar with av1 unit test yet.

**Comment by kylophone** [comment]
Were the previous buffers memset to 0?

**Comment by tianjunwork** [comment]
@kylophone yes,` EB_CALLOC_ALIGNED_ARRAY` calls memset to 0.

**Comment by silverbacknet** [comment]
Is it that one of the functions, like noise_extract_chroma_strong_c, is incorrectly using stray pixels from outside the frame, or is it that the test is incorrectly checking pixels outside the frame? There should be no reason to calloc/memset when the data is just being overwritten anyway. On a cursory check of the function loops, they seem correct, but something must be looking out-of-bounds somewhere. 

I'm wondering if the bugfixes in #1084 will fix this.

**Comment by Cidana-Developers** [comment]
> /home/runner/work/SVT-AV1/SVT-AV1/test/NoiseExtractTest.cc:147: Failure
> Expected equality of these values:
>   0
>   mismatch_samples_cb
>     Which is: 2
> 2 cb samples are different.
> /home/runner/work/SVT-AV1/SVT-AV1/test/NoiseExtractTest.cc:149: Failure
> Expected equality of these values:
>   0
> 
> If removing memset is the right thing to do, could some one help fix unit test? I am not familiar with av1 unit test yet.

Thank you for reminding, we deliver a hot fix for this failed in #1096

**Comment by tianjunwork** [comment]
@Cidana-Developers , thank you for helping on the unit test.
Hi @hassount , could you merge #1096 first, so that I can rerun CI/Unit Tests for this PR?

**Comment by tianjunwork** [comment]
CI: `Git checkout failed with exit code: 128`. So rebased and force-pushed. Thx @1480c1 for the hint.
PR is ready to validate and review.

**Comment by hassount** [comment]
before merging this, can we rebase and run a valgrind test to make sure that we're not producing any valgrind issues?

**Comment by tianjunwork** [comment]
Rebased and force pushed.

**Comment by tianjunwork** [comment]
Hi @hassount , CI passed. Pls let me know if anything else is needed for this PR.

**Comment by hassount** [comment]
> Hi @hassount , CI passed. Pls let me know if anything else is needed for this PR.

@tianjunwork I believe @OmranAbdelkafi has found some valgrind issues when removing the Calloc. It seems that the encoder assumes such initialization which I would think it used in the padding samples.

**Comment by tianjunwork** [comment]
From the logic vise, these buffers don't need to be memset/initialized. Unit test also passed with the fix in #1096.

**Comment by tianjunwork** [comment]
Valgrind reports `uninitilised value warning` for padding. Close this PR.

**Pull request closed without merging**
