### PR TITLE
Fix a regression which increases init time

### PR DESCRIPTION
**Pull request by tianjunwork**
Signed-off-by: Jun Tian <jun.tian@intel.com>

### CODE REVIEW

**Comment by tianjunwork** [comment]
Using open() costs about 1s. This patch reduce it to 1.5ms.

**Comment by EwoutH** [comment]
@hassount @kylophone What's blocking this?

**Comment by hassount** [comment]
@joelsole @kylophone @mafonsoN 
Any issues moving forward with this ?

**Comment by EwoutH** [comment]
@tianjunwork Could you rebase?

**Comment by tianjunwork** [comment]
> @tianjunwork Could you rebase?

Hi @EwoutH, this branch has no conflicts with master. Which branch you want this PR rebased onto?

**Comment by EwoutH** [comment]
Just the latest commit from the master branch (it's currently 13 commits behind OpenVisualCloud:master).

**Comment by tianjunwork** [comment]
> Just the latest commit from the master branch (it's currently 13 commits behind OpenVisualCloud:master).

There is no conflict with master tip. No need to rebase. Github will handle the merge automatically.

**Comment by 1480c1** [comment]
I think he wants to be able to do a comparison before merge and after merge to see how much this affects the speed.

**Comment by tianjunwork** [comment]
> I think he wants to be able to do a comparison before merge and after merge to see how much this affects the speed.

Thank you😊. I will do.

**Comment by tianjunwork** [comment]
Hi, @EwoutH please use below command, this patch will be applied on top of master if you want to validate the affects. Thank you.
git checkout -b tianjunwork-regression_fix master
git pull https://github.com/tianjunwork/SVT-AV1.git regression_fix

**Comment by EwoutH** [comment]
Fair point, it makes automated benchmarks a lot more complicated though.

Anyway, @hassount, why isn't this merged yet?

**Comment by hassount** [comment]
we need an additional maintainer to approve @kylophone @andrey-norkin @mafonsoN @joelsole ?

**Comment by kylophone** [comment]
LGTM

**Pull request merged**
