### PR TITLE
Harmonized Decoder and Encoder Functions, Added Blend unit Test bench

### PR DESCRIPTION
**Pull request by nijilk**
Harmonized functions, structures and tables between decoder and encoder.
Added unit test bench for Blend functions.
Fixed issue in convolve AVX2 path specific to OBMC.

### CODE REVIEW

**Comment by hassount** [comment]
@joelsole is this good to go ?

**Comment by hassount** [comment]
@nijilk 
can you please rebase and squash your commits for a more concise set of commits ?

**Comment by nijilk** [comment]
> 
> 
> @nijilk
> can you please rebase and squash your commits for a more concise set of commits ?

@hassount 
Sure. Will do that.

**Comment by hassount** [comment]
Hi Joel,

Seems like we need to revert this one as it’s breaking the build:

https://ci.appveyor.com/project/tianjunwork/svt-av1/builds/28275931

Cheers,
Hassene

**Comment by joelsole** [comment]
ok - go ahead

**Pull request merged**
