### PR TITLE
Document TargetBitRate

### PR DESCRIPTION
**Pull request by dprestegard**
The default is crazy high!

### CODE REVIEW

**Comment by hassount** [comment]
> The default is crazy high!

would you like to suggest a different value ? might need to be done per resolution because 7Mbps is not too high for 4k

**Comment by 1480c1** [comment]
> > The default is crazy high!
> 
> would you like to suggest a different value ? might need to be done per resolution because 7Mbps is not too high for 4k

Perhaps he thinks it's 700 mbps

**Comment by dprestegard** [comment]
Indeed, I did think it's 700 Mbps. Looks like I need to update the parameter description then.

**Comment by dprestegard** [comment]
7 Mbps is a reasonable default.

**Comment by hassount** [comment]
> Indeed, I did think it's 700 Mbps. Looks like I need to update the parameter description then.

Bringing a good point here though, too many zeros, we might need to go to kbps instead of bps

**Comment by dprestegard** [comment]
I do personally prefer Kbps, it improves readability and is what x264 and x265 CLIs do :)

**Comment by dprestegard** [comment]
I'm a git newbie unfortunately. Sorry for the mess.

**Pull request merged**
