### PR TITLE
dr prediction AVX performance improvement

### PR DESCRIPTION
**Pull request by Zvictoria**
Performance improving changes for AVX dr prediction functions done for AOM initially and replicated for SVT

### CODE REVIEW

**Comment by 1480c1** [comment]
R.I.P. Commit too large to be able to view on github web

**Comment by kylophone** [comment]
> R.I.P. Commit too large to be able to view on github web

Yeah, wow, this is a huge diff.

**Comment by kylophone** [comment]
Please also add an entry to the changelog

**Comment by hassount** [comment]
@Zvictoria 
is there a way to break this into a few commits so that we can at lease review it ?

**Comment by EwoutH** [comment]
A way to view it quickly is by adding .patch to the PR url, so https://github.com/OpenVisualCloud/SVT-AV1/pull/289.patch

**Comment by kodabb** [comment]
I was going to troll with "inb4 there are 10000 cosmetic changes", but then I opened the patch and there were actually 10000 cosmetic changes :-(

**Comment by hassount** [comment]
@kodabb 
yes it seems like there's an editor mismatch here causing the many changes. 
@Zvictoria 
is there a way you can re-build this PR by only pushing the code changes. If you believe there are spacing fixes that would need to be done, please suggest such to PR #248

**Comment by kylophone** [comment]
Make sure you check the diff locally before sending a PR. Use `git diff` or `git diff --cached`. This is indecipherable as-is.

**Comment by Zvictoria** [comment]
Question from a pull request nub - am I supposed to remove wrong first commit from this PR and leave the second one only?

**Comment by EwoutH** [comment]
@Zvictoria Yes, easiest way is probably to commit the changes to a new branch and open a pull request from that branch.

**Comment by Zvictoria** [comment]
> @Zvictoria Yes, easiest way is probably to commit the changes to a new branch and open a pull request from that branch.

But it will be a new PR then? And what if I leave the current one as is? i

**Comment by EwoutH** [comment]
1. Close this PR
2. Create a new branch --> Add function changes --> Open PR
3. Create another new branch --> Add cosmic changes --> Open another PR

**Comment by kodabb** [comment]
alternatively you can do `git commit -a --amend` and `git push -f` rather than opening a new branch

@Zvictoria please link the new PR here too for continuity

**Comment by 1480c1** [comment]
You could also do `git reset master`, `git add --patch` and split etc, `git commit` and then finally `git push -f` as an alternative to ensure you can split the commits effectively

**Comment by kylophone** [comment]
Replaced by #304

**Pull request closed without merging**
