### PR TITLE
[WIP] CI: Add coding style check to Travis, cleanup

### PR DESCRIPTION
**Pull request by EwoutH**
- [x] Add coding style check (Borrowed from dav1d's [.gitlab-ci.yml](https://code.videolan.org/videolan/dav1d/blob/master/.gitlab-ci.yml))
 - [x] Fixes coding style error (trailing white space) in "name: unittest"

For now the Style check is allowed to fail (waiting on #248), but that should be reversed as soon as possible.

**Todo:**
 - [ ] Select files and directories to exclude
 - [ ] Remove those from dav1d

### CODE REVIEW

**Comment by kylophone** [comment]
> * Add coding style check (Borrowed from dav1d's [.gitlab-ci.yml](https://code.videolan.org/videolan/dav1d/blob/master/.gitlab-ci.yml))
> * Fixes coding style error (trailing white space) in "name: unittest"
> 
> For now the Style check is allowed to fail (waiting on #248), but that should be reversed as soon as possible.

Yeah, I love this. The current state of the code does not match the style guide in the least bit. For the time being, I think we should at least checking the PR diffs. That would cut down on the noise and manual effort involved when it comes to patch review. Will let others chime in as well.

**Comment by EwoutH** [comment]
We should probably exclude the third_party libraries (googletest and aom) from the style check.

**Comment by kylophone** [comment]
> We should probably exclude the third_party libraries (googletest and aom) from the style check.

Yes, that would be preferable.

**Comment by EwoutH** [comment]
Any other files we want to exclude except from `third_party`?

**Pull request merged**
