### PR TITLE
distribute unit tests in GitHub CI

### PR DESCRIPTION
**Pull request by Cidana-Developers**
1. discributes unit tests in shards based on PR: https://github.com/OpenVisualCloud/SVT-AV1/pull/958
2. disabled some failure unit test cases:
   a) Convolve/HBDVariace fixed in PR: https://github.com/OpenVisualCloud/SVT-AV1/pull/954
   b) sad_Calculation fixed in PR: https://github.com/OpenVisualCloud/SVT-AV1/pull/969
3. fixed transform crash in PR: https://github.com/OpenVisualCloud/SVT-AV1/pull/944, to avoid being interrupted during testing.

### CODE REVIEW

**Comment by hassount** [comment]
@ePirat Hope this helps ?

**Comment by ePirat** [comment]
Looks good!

**Comment by hassount** [comment]
@Cidana-Developers 
Can this be rebased now and account for the PRs that have been merged?

**Comment by spawlows** [comment]
Fix for is_txfm_allowed merged in #944

**Comment by spawlows** [comment]
I propose to separate the job "Unit Tests" on travis-ci for 3 separate jobs.
```
      cd $ TRAVIS_BUILD_DIR / Build / linux / $ {build_type: -Release}
           make TestVectors
           cd $ TRAVIS_BUILD_DIR
           SvtAv1UnitTests
           SvtAv1ApiTests
           SvtAv1E2ETests
```

Run separate:
 -SvtAv1UnitTests
 -SvtAv1ApiTests
 -SvtAv1E2ETests


Because when SvtAv1UnitTests not failing fast, then SvtAv1ApiTests
SvtAv1E2ETests will be omitted by limiting the duration of the job on travis.

**Comment by ePirat** [comment]
@spawlows Maybe I'm missing something but currently this does not run `SvtAv1ApiTests` and `SvtAv1E2ETests` at all?

**Comment by ePirat** [comment]
@spawlows Oh sorry missed you were talking about travis. Maybe file an issue for that instead of in this PR which is about the Github Actions CI?

**Comment by hassount** [comment]
@Cidana-Developers #954 #944 and #969 are all merged, can we change this PR to reflect so after rebasing

**Comment by ePirat** [comment]
Any update on this? Should I do the rebase instead or do you plan to do it soon, as it seems this is the only blocker to merge?

**Comment by hassount** [comment]
> Any update on this? Should I do the rebase instead or do you plan to do it soon, as it seems this is the only blocker to merge?

@ePirat would be great if you can do that yes, we can merge it as soon as it's done

**Pull request merged**
