### PR TITLE
Add AVX512 code for Smooth Predictors

### PR DESCRIPTION
**Pull request by agopikrishna13**
This PR has AVX512 code for aom_highbd_smooth_predictor, aom_highbd_smooth_v_predictor,  and aom_highbd_smooth_h_predictor and corresponding Unit tests. The performance numbers are attached with the commit message.

### CODE REVIEW

**Comment by JackZhouVCD** [comment]
I ran a speed test and found that there is a 0.09% speed gain averaged over M{1,4,8}, but I am also that the bitstreams do not match for all encode modes. Can you please look into this?

**Comment by agopikrishna13** [comment]
> I ran a speed test and found that there is a 0.09% speed gain averaged over M{1,4,8}, but I am also seeing that the bitstreams do not match for all encode modes when I apply this PR and turn on the added AVX512 kernels. Can you please look into this?

Are you seeing bitstream mismatch for specific set of cli's or for all the cli's??. Can you share your test cases here, so that we can reproduce the issue at our end.

**Comment by JackZhouVCD** [comment]
> > I ran a speed test and found that there is a 0.09% speed gain averaged over M{1,4,8}, but I am also seeing that the bitstreams do not match for all encode modes when I apply this PR and turn on the added AVX512 kernels. Can you please look into this?
> 
> Are you seeing bitstream mismatch for specific set of cli's or for all the cli's??. Can you share your test cases here, so that we can reproduce the issue at our end.

The command I issued for encoding is the following:
```bash
SvtAv1EncApp.exe -i thaloundeskmtg360p_60f.yuv -w 640 -h 360  -n 60 -fps 60 -q 32 -enc-mode <any encode mode here>
```

I compared the tip of your branch against the base of your branch, which is commit 304250f on master. The encoder crashes on that revision, so I manually applied #499 which addressed the crash and allowed me to test if bitstreams matched

**Comment by JackZhouVCD** [comment]
@agopikrishna13 were you able to replicate and look into the bitstream mismatch? Any updates?

**Comment by agopikrishna13** [comment]
> @agopikrishna13 were you able to replicate and look into the bitstream mismatch? Any updates?

Hi, can you share the clip or online resource from where I can get this clip thaloundeskmtg360p_60f.yuv??

**Comment by hassount** [comment]
@agopikrishna13 
you can find it in https://media.xiph.org/video/derf/objective-1-fast.tar.gz

**Comment by agopikrishna13** [comment]
> @agopikrishna13
> you can find it in https://media.xiph.org/video/derf/objective-1-fast.tar.gz

Thanks @hassount. Got the videos. I have merged the latest master branch into my branch and tried building the repo. When I enable AVX512 support, I get the following error from pickrst_avx512.c file while building, 
"pickrst_avx512.obj : error LNK2019: unresolved external symbol _mm_storeh_epi64 referenced in function compute_stats_win3_avx512"

Am I missing something??

**Comment by ttrigui** [comment]
> > @agopikrishna13
> > you can find it in https://media.xiph.org/video/derf/objective-1-fast.tar.gz
> 
> Thanks @hassount. Got the videos. I have merged the latest master branch into my branch and tried building the repo. When I enable AVX512 support, I get the following error from pickrst_avx512.c file while building,
> "pickrst_avx512.obj : error LNK2019: unresolved external symbol _mm_storeh_epi64 referenced in function compute_stats_win3_avx512"
> 
> Am I missing something??

@agopikrishna13 yes we just encountered the same issue yesterday. synonyms.h should be included in  pickrst_avx512.c . I'll create a PR for it.

**Comment by hassount** [comment]
@agopikrishna13 #670 is now merged to Master, could you please rebase and address whatever is not working properly, it's long overdue, but I really want this PR in asap

**Comment by agopikrishna13** [comment]
> @agopikrishna13 #670 is now merged to Master, could you please rebase and address whatever is not working properly, it's long overdue, but I really want this PR in asap

Thanks. I will rebase the branch and start working on fixing the issue.

**Comment by agopikrishna13** [comment]
@JackZhouVCD I ran the following cli on the master branch and found that the output is inconsistent. I have not turned on AVX512 support also,
SvtAv1EncApp.exe -i X:\svt_test_videos\thaloundeskmtg360p_60f.y4m -n 60 -fps 60 -q 32 -enc-mode 1
is there any issue with my cli or the master branch is inconsistent with this input clip??
[console_log.txt](https://github.com/OpenVisualCloud/SVT-AV1/files/3728560/console_log.txt)

**Comment by lzhangnj** [comment]
> is there any issue with my cli or the master branch is inconsistent with this input clip??
I observed master branch inconsistency also.

**Comment by JackZhouVCD** [comment]
> @JackZhouVCD I ran the following cli on the master branch and found that the output is inconsistent. I have not turned on AVX512 support also,
> SvtAv1EncApp.exe -i X:\svt_test_videos\thaloundeskmtg360p_60f.y4m -n 60 -fps 60 -q 32 -enc-mode 1
> is there any issue with my cli or the master branch is inconsistent with this input clip??
> [console_log.txt](https://github.com/OpenVisualCloud/SVT-AV1/files/3728560/console_log.txt)

Yes, The current master is inconsistent at the M1 level. I believe that the `RollerCoaster` clip from the test set does not have inconsistent bitstream yields in the context of M1. Can you try again with that clip?

**Comment by agopikrishna13** [comment]
> @JackZhouVCD I ran the following cli on the master branch and found that the output is inconsistent. I have not turned on AVX512 support also,
> SvtAv1EncApp.exe -i X:\svt_test_videos\thaloundeskmtg360p_60f.y4m -n 60 -fps 60 -q 32 -enc-mode 1
> is there any issue with my cli or the master branch is inconsistent with this input clip??
> console_log.txt
> 
> Yes, The current master is inconsistent at the M1 level. I believe that the RollerCoaster clip from the test set does not have inconsistent bitstream yields in the context of M1. Can you try again with that clip?

@JackZhouVCD I have tried with RollerCoaster clip with enc modes 1, 4, 8 and thaloundeskmtg360p_60f.y4m clip with enc modes 4, 8 (since M1 is inconsistent with thaloundeskmtg360p_60f.y4m) and found that there is no bitstream mismatch between this pull request(AVX512 enabled) and the master branch. Can you please check.

**Comment by JackZhouVCD** [comment]
> > @JackZhouVCD I ran the following cli on the master branch and found that the output is inconsistent. I have not turned on AVX512 support also,
> > SvtAv1EncApp.exe -i X:\svt_test_videos\thaloundeskmtg360p_60f.y4m -n 60 -fps 60 -q 32 -enc-mode 1
> > is there any issue with my cli or the master branch is inconsistent with this input clip??
> > console_log.txt
> > Yes, The current master is inconsistent at the M1 level. I believe that the RollerCoaster clip from the test set does not have inconsistent bitstream yields in the context of M1. Can you try again with that clip?
> 
> @JackZhouVCD I have tried with RollerCoaster clip with enc modes 1, 4, 8 and thaloundeskmtg360p_60f.y4m clip with enc modes 4, 8 (since M1 is inconsistent with thaloundeskmtg360p_60f.y4m) and found that there is no bitstream mismatch between this pull request(AVX512 enabled) and the master branch. Can you please check.

Thanks for addressing this! I took a look but I am still finding a mismatch in the context of M0 with the following commandline. 

```
SvtAv1EncApp.exe -i akiyo_cif.y4m -n 60 -fps 60 -q 32 -b __M0.ivf -enc-mode 0
```

I'm seeing a r2r issue in the context of M0 on the base encoder built from 27a82987 as well, so I think your changes in this PR should be fine. @hassount thoughts?

**Comment by mafonsoN** [comment]
@agopikrishna13 can you please rebase this PR?

**Comment by agopikrishna13** [comment]
> @agopikrishna13 can you please rebase this PR?

ok. Will rebase and update the PR

**Comment by hassount** [comment]
@agopikrishna13 
Thank you very much for rebasing, Unfortunately, one more rebase is needed. you're up next to be merged. 

Also, would you be able to squash the commits into 3 or 4 at most as we're following a linear commit history in the master and we'd like  all commits to build and run properly.

**Pull request merged**
