### PR TITLE
 Tune Preset 8

### PR DESCRIPTION
**Pull request by OmranAbdelkafi**
Speed-up Preset 8 by 16% for a BD-rate cost of 1.7%

### CODE REVIEW

**Comment by EwoutH** [comment]
Measured a 7,6% increase in performance.

_Config_

- **Build:** eaf50c8 (2019-05-23)
- **Video:** Morocco (1080p 8-bit 4:2:0)
- **System:** Intel (28c/56t, AVX2), 128GB DDR4, Linux Mint
- **Settings:** `-n 240 -enc-mode 8`

**Comment by hassount** [comment]
@EwoutH, thank you for the test, whenever you have a chance, would you be able to test a longer encoder (~1000 frames or so)
@OmranAbdelkafi assuming that the data reported is on 72 vCPUs, could you please run a quick test on a 28 core 8180 to see if you you would get similar to what @EwoutH got ?

**Comment by EwoutH** [comment]
@hassount 960 frames, same settings. Average of two runs: From 48,96 to 54,21 fps (+10,7%).

**Comment by EwoutH** [comment]
I added an [AWCY job](https://beta.arewecompressedyet.com/?job=%402019-05-24_-%20Master%20(enc-mode%208)&job=%402019-05-24_-%20Tune%20Preset%208%20(%23271)) for this PR to closer examine the impact on encoding quality.

**Comment by hassount** [comment]
@EwoutH, thank you for the confirmation, with bitrate / machines differences the difference make sense.

**Comment by EwoutH** [comment]
Since the last AWCY runs failed for some reason, I added two [new ones](https://beta.arewecompressedyet.com/?job=SVT-AV1-enc-mode-3-old%402019-05-28&job=SVT-AV1-enc-mode-3-new%402019-05-28).

**Pull request merged**
