### PR TITLE
Travis: Add Werror CFLAG when building SVT-AV1

### LINKED ISSUE #419: Make Travis fail on warnings
After fixing #417 we would like to impose that checks do not pass if there are warnings in the build.

We need to add such to travis only where the build fails on any warning and rebase all PRs to make sure we don't introduce any warnings in the master anymore.

### PR DESCRIPTION
**Pull request by 1480c1**
Closes #419
Relies on #417

### CODE REVIEW

**Comment by hassount** [comment]
Thank you very much @1480c1 it seems that it's working. Can we restrict this to gcc and one of the xcode that does not have warnings?

**Comment by 1480c1** [comment]
Do you mean clang?

**Comment by 1480c1** [comment]
Or do you mean macOS?

**Comment by joelsole** [comment]
clang MacOs has no warnings => https://travis-ci.com/OpenVisualCloud/SVT-AV1/jobs/211980307

**Comment by kylophone** [comment]
LGTM, will merge today.

**Pull request merged**
