### PR TITLE
Remove ImproveSharpness Feature

### LINKED ISSUE #632: Divide by zero in initial_rate_control_kernel
In the file under Source/Lib/Common/Codec/EbInitialRateControlProcess.c:

- at line 1273 picture_control_set_ptr->processed_leaf_count[cu_depth] is initialized with 0

- is it then immediately used in a division at line 1285, resulting in a division by 0

The code responsible of updating this variable has been removed by commit 4f180cce01c74a91e2f5c9f95a31eac5a315c0f2

The bugged code is reached when setting `-sharp 1` in the cmdline.

### PR DESCRIPTION
**Pull request by JackZhouVCD**
## Description
This PR removes ImproveSharpness feature which is not supported in SVT-AV1. No impact on BD-Rate(lossless)/speed/memory footprint.

fixes #632

### CODE REVIEW

**Comment by hassount** [comment]
@JackZhouVCD can you please add the issue that this PR addressed to in the description ?

**Comment by JackZhouVCD** [comment]
> @JackZhouVCD can you please add the issue that this PR addressed to in the description ?

yes, that is done 👍

**Comment by ultrawide** [comment]
Hi, there were no memory deviations on Linux and the speed deviation tested on an i7 Windows machine was 0.06% averaged over m{1,4,8}.

**Comment by JackZhouVCD** [comment]
> Hi, there were no memory deviations on Linux and the speed deviation tested on an i7 Windows machine was 0.06% averaged over m{1,4,8}.

Thanks for the tests!

**Pull request merged**
