### PR TITLE
Actions: Move style check job over to gh actions

### PR DESCRIPTION
**Pull request by 1480c1**
Runs in 6 seconds instead of 26 it seems. Idk how trustable those numbers are.

Frees up travis a bit to not have so many stages

@EwoutH and @kylophone, please check

### CODE REVIEW

**Comment by 1480c1** [comment]
I am looking up to see how to work with a feedback of where the issue are, but in so far, it seems it may be restricted to javascript based actions for now

**Comment by EwoutH** [comment]
Looks good overall. My only concern is Travis now running the full stack while there are styling errors, I don't know if that's desired behavior.

**Comment by 1480c1** [comment]
I think that may be fine since gh actions will fail the pr, but we can still test if the code compiles and runs correctly in travis. That way the author can test if their code if fine, and then fixup style issues afterwards once the PR is finally ready

**Comment by hassount** [comment]
are we good to go with this ?

**Comment by 1480c1** [comment]
I have no more plans to add to this, so this is good from my side

**Pull request merged**
