### PR TITLE
[SIMD] Add convolve AVX512 code

### PR DESCRIPTION
**Pull request by lzhangnj**
Rewrote eb_av1_jnt_convolve_2d_copy_avx2(), and the speed comparison with original one is between 2.1x to 3.3x.

Speed Comparison of AVX512 vs AVX2 (Size 32xN to 128xN) with filter tap 6.
```
SR
x:    1.21x - 1.58x
y:    1.06x - 1.33x
2d:   1.08x - 1.34x
copy: Even slower. Don't call AVX512.

JNT
x:    1.23x - 1.57x
y:    1.29x - 1.55x
2d:   1.05x - 1.37x
copy: 1.00x - 1.20x
```

### CODE REVIEW

**Comment by JackZhouVCD** [comment]
I'm seeing these build warnings when building on MSVC
```
svt-av1-ovc\source\lib\common\asm_avx512\convolve_avx512.h(81): warning C4305: 'function': truncation from 'int' to '__mmask8' (compiling source file C:\Users\zhoujack\repos\SVT-AV1-OVC\Source\Lib\Common\ASM_AVX512\convolve_avx512.c)
svt-av1-ovc\source\lib\common\asm_avx512\convolve_avx512.h(105): warning C4305: 'function': truncation from 'int' to '__mmask8' (compiling source file C:\Users\zhoujack\repos\SVT-AV1-OVC\Source\Lib\Common\ASM_AVX512\convolve_avx512.c)
svt-av1-ovc\source\lib\common\asm_avx512\convolve_avx512.h(131): warning C4305: 'function': truncation from 'int' to '__mmask8' (compiling source file C:\Users\zhoujack\repos\SVT-AV1-OVC\Source\Lib\Common\ASM_AVX512\convolve_avx512.c)
svt-av1-ovc\source\lib\common\asm_avx512\convolve_avx512.h(173): warning C4305: 'function': truncation from 'int' to '__mmask8' (compiling source file C:\Users\zhoujack\repos\SVT-AV1-OVC\Source\Lib\Common\ASM_AVX512\convolve_avx512.c)
svt-av1-ovc\source\lib\common\asm_avx512\convolve_avx512.h(187): warning C4305: 'function': truncation from 'int' to '__mmask8' (compiling source file C:\Users\zhoujack\repos\SVT-AV1-OVC\Source\Lib\Common\ASM_AVX512\convolve_avx512.c)
svt-av1-ovc\source\lib\common\asm_avx512\convolve_avx512.h(204): warning C4305: 'function': truncation from 'int' to '__mmask8' (compiling source file C:\Users\zhoujack\repos\SVT-AV1-OVC\Source\Lib\Common\ASM_AVX512\convolve_avx512.c)
svt-av1-ovc\source\lib\common\asm_avx512\convolve_avx512.h(81): warning C4305: 'function': truncation from 'int' to '__mmask8' (compiling source file C:\Users\zhoujack\repos\SVT-AV1-OVC\Source\Lib\Common\ASM_AVX512\convolve_2d_avx512.c)
svt-av1-ovc\source\lib\common\asm_avx512\convolve_avx512.h(105): warning C4305: 'function': truncation from 'int' to '__mmask8' (compiling source file C:\Users\zhoujack\repos\SVT-AV1-OVC\Source\Lib\Common\ASM_AVX512\convolve_2d_avx512.c)
svt-av1-ovc\source\lib\common\asm_avx512\convolve_avx512.h(131): warning C4305: 'function': truncation from 'int' to '__mmask8' (compiling source file C:\Users\zhoujack\repos\SVT-AV1-OVC\Source\Lib\Common\ASM_AVX512\convolve_2d_avx512.c)
svt-av1-ovc\source\lib\common\asm_avx512\convolve_avx512.h(173): warning C4305: 'function': truncation from 'int' to '__mmask8' (compiling source file C:\Users\zhoujack\repos\SVT-AV1-OVC\Source\Lib\Common\ASM_AVX512\convolve_2d_avx512.c)
svt-av1-ovc\source\lib\common\asm_avx512\convolve_avx512.h(187): warning C4305: 'function': truncation from 'int' to '__mmask8' (compiling source file C:\Users\zhoujack\repos\SVT-AV1-OVC\Source\Lib\Common\ASM_AVX512\convolve_2d_avx512.c)
svt-av1-ovc\source\lib\common\asm_avx512\convolve_avx512.h(204): warning C4305: 'function': truncation from 'int' to '__mmask8' (compiling source file C:\Users\zhoujack\repos\SVT-AV1-OVC\Source\Lib\Common\ASM_AVX512\convolve_2d_avx512.c)
svt-av1-ovc\source\lib\common\asm_avx512\convolve_avx512.h(81): warning C4305: 'function': truncation from 'int' to '__mmask8' (compiling source file C:\Users\zhoujack\repos\SVT-AV1-OVC\Source\Lib\Common\ASM_AVX512\jnt_convolve_avx512.c)
svt-av1-ovc\source\lib\common\asm_avx512\convolve_avx512.h(105): warning C4305: 'function': truncation from 'int' to '__mmask8' (compiling source file C:\Users\zhoujack\repos\SVT-AV1-OVC\Source\Lib\Common\ASM_AVX512\jnt_convolve_avx512.c)
svt-av1-ovc\source\lib\common\asm_avx512\convolve_avx512.h(131): warning C4305: 'function': truncation from 'int' to '__mmask8' (compiling source file C:\Users\zhoujack\repos\SVT-AV1-OVC\Source\Lib\Common\ASM_AVX512\jnt_convolve_avx512.c)
svt-av1-ovc\source\lib\common\asm_avx512\convolve_avx512.h(173): warning C4305: 'function': truncation from 'int' to '__mmask8' (compiling source file C:\Users\zhoujack\repos\SVT-AV1-OVC\Source\Lib\Common\ASM_AVX512\jnt_convolve_avx512.c)
svt-av1-ovc\source\lib\common\asm_avx512\convolve_avx512.h(187): warning C4305: 'function': truncation from 'int' to '__mmask8' (compiling source file C:\Users\zhoujack\repos\SVT-AV1-OVC\Source\Lib\Common\ASM_AVX512\jnt_convolve_avx512.c)
svt-av1-ovc\source\lib\common\asm_avx512\convolve_avx512.h(204): warning C4305: 'function': truncation from 'int' to '__mmask8' (compiling source file C:\Users\zhoujack\repos\SVT-AV1-OVC\Source\Lib\Common\ASM_AVX512\jnt_convolve_avx512.c)
svt-av1-ovc\source\lib\common\asm_avx512\convolve_avx512.h(81): warning C4305: 'function': truncation from 'int' to '__mmask8' (compiling source file C:\Users\zhoujack\repos\SVT-AV1-OVC\Source\Lib\Common\ASM_AVX512\jnt_convolve_2d_avx512.c)
svt-av1-ovc\source\lib\common\asm_avx512\convolve_avx512.h(105): warning C4305: 'function': truncation from 'int' to '__mmask8' (compiling source file C:\Users\zhoujack\repos\SVT-AV1-OVC\Source\Lib\Common\ASM_AVX512\jnt_convolve_2d_avx512.c)
svt-av1-ovc\source\lib\common\asm_avx512\convolve_avx512.h(131): warning C4305: 'function': truncation from 'int' to '__mmask8' (compiling source file C:\Users\zhoujack\repos\SVT-AV1-OVC\Source\Lib\Common\ASM_AVX512\jnt_convolve_2d_avx512.c)
svt-av1-ovc\source\lib\common\asm_avx512\convolve_avx512.h(173): warning C4305: 'function': truncation from 'int' to '__mmask8' (compiling source file C:\Users\zhoujack\repos\SVT-AV1-OVC\Source\Lib\Common\ASM_AVX512\jnt_convolve_2d_avx512.c)
svt-av1-ovc\source\lib\common\asm_avx512\convolve_avx512.h(187): warning C4305: 'function': truncation from 'int' to '__mmask8' (compiling source file C:\Users\zhoujack\repos\SVT-AV1-OVC\Source\Lib\Common\ASM_AVX512\jnt_convolve_2d_avx512.c)
svt-av1-ovc\source\lib\common\asm_avx512\convolve_avx512.h(204): warning C4305: 'function': truncation from 'int' to '__mmask8' (compiling source file C:\Users\zhoujack\repos\SVT-AV1-OVC\Source\Lib\Common\ASM_AVX512\jnt_convolve_2d_avx512.c)
```

**Comment by lzhangnj** [comment]
> I'm seeing these build warnings when building on MSVC
Thanks! It's a flaw in Visual Studio system header file. Fixed.

**Comment by JackZhouVCD** [comment]
> BTW, Travis CI etc. buildings all failed with "11738 Segmentation fault". I'm not sure if it's caused by non AVX512 machines. I don't have a Linux AVX512 machine, could you please help me verify? Thanks a lot!

I just checked and I am indeed getting a segfault on an AVX512 enabled machine. The command line I used was this:

```bash
./SvtAv1EncApp -i red_kayak_360p_60f.yuv -w 640 -h 360
```
I ran this same command through gdb and saw this output, if it helps you debug
```c
Thread 179 "SvtAv1EncApp" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffeabd96700 (LWP 46189)]
0x00007fffebf4fa1b in _mm512_load_si512 (__P=0x7ffeabd595e0)
    at /usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h:490
490       return *(__m512i *) __P;
```

The master right now with AVX512 enabled does not have this issue, neither do your changes with AVX512 disabled.

**Comment by lzhangnj** [comment]
> I ran this same command through gdb and saw this output, maybe it will help you debug
> 
> ```c
> Thread 179 "SvtAv1EncApp" received signal SIGSEGV, Segmentation fault.
> [Switching to Thread 0x7ffeabd96700 (LWP 46189)]
> 0x00007fffebf4fa1b in _mm512_load_si512 (__P=0x7ffeabd595e0)
>     at /usr/lib/gcc/x86_64-linux-gnu/7/include/avx512fintrin.h:490
> 490       return *(__m512i *) __P;
> ```

@JackZhouVCD 
Really appreciate the helpful details you provided! Looks like my first fix isn't enough. I'll keep digging. Thanks.

**Comment by lzhangnj** [comment]
@JackZhouVCD Thanks for helping me fix the bugs!

I tested Mode 0 speed in Windows, and observed 1.6% gain when using AVX2 vs master code base, but 6.1% loss when using AVX512 vs AVX2 (i.e., 4.5% loss vs master). Could you please help test on Linux? Thanks!

**Comment by JackZhouVCD** [comment]
> @JackZhouVCD Thanks for helping me fix the bugs!
> 
> I tested Mode 0 speed in Windows, and observed 1.6% gain when using AVX2 vs master code base, but 6.1% loss when using AVX512 vs AVX2 (i.e., 4.5% loss vs master). Could you please help test on Linux? Thanks!

For sure! On Linux I tested the base of your changes 9a321eb and the tip of your changes e757f65  (both with AVX512 turned on so we can see the speed impact your added AVX512 optimizations adds). Here is what I found in 360p:

| enc-mode | Speed Impact |
|-|-|
|0|0.575%|
|1|2.531%|
|4|1.222%|
|8|0.575%|
|  |**1.226%**|

I'll update you when I get results for higher resolutions!

**Comment by JackZhouVCD** [comment]
I also applied this PR and found that the resulting bitstreams matched for all encmodes

**Comment by JackZhouVCD** [comment]
> > @JackZhouVCD Thanks for helping me fix the bugs!
> > I tested Mode 0 speed in Windows, and observed 1.6% gain when using AVX2 vs master code base, but 6.1% loss when using AVX512 vs AVX2 (i.e., 4.5% loss vs master). Could you please help test on Linux? Thanks!
> 
> For sure! On Linux I tested the base of your changes [9a321eb](https://github.com/OpenVisualCloud/SVT-AV1/commit/9a321eb5f1233c46ac44472b30db8efb953fffd3) and the tip of your changes [e757f65](https://github.com/OpenVisualCloud/SVT-AV1/commit/e757f65e06d42a7c3cb05f999f3f587bf3ff0be4) (both with AVX512 turned on so we can see the speed impact your added AVX512 optimizations adds). Here is what I found in 360p:
> 
> enc-mode	Speed Impact
> 0	0.575%
> 1	2.531%
> 4	1.222%
> 8	0.575%
> **1.226%**
> I'll update you when I get results for higher resolutions!

I have the 720p data ready:

| enc-mode | Speed Impact |
|-|-|
|0|-1.205%|
|1|2.359%|
|4|1.425%|
|8|0.804%|
|  |**0.846%**|

**Comment by lzhangnj** [comment]
> > > @JackZhouVCD Thanks for helping me fix the bugs!
> > > I tested Mode 0 speed in Windows, and observed 1.6% gain when using AVX2 vs master code base, but 6.1% loss when using AVX512 vs AVX2 (i.e., 4.5% loss vs master). Could you please help test on Linux? Thanks!
> > 
> > 
> > For sure! On Linux I tested the base of your changes [9a321eb](https://github.com/OpenVisualCloud/SVT-AV1/commit/9a321eb5f1233c46ac44472b30db8efb953fffd3) and the tip of your changes [e757f65](https://github.com/OpenVisualCloud/SVT-AV1/commit/e757f65e06d42a7c3cb05f999f3f587bf3ff0be4) (both with AVX512 turned on so we can see the speed impact your added AVX512 optimizations adds). Here is what I found in 360p:
> > enc-mode	Speed Impact
> > 0	0.575%
> > 1	2.531%
> > 4	1.222%
> > 8	0.575%
> > **1.226%**
> > I'll update you when I get results for higher resolutions!
> 
> I have the 720p data ready:
> 
> enc-mode	Speed Impact
> 0	-1.205%
> 1	2.359%
> 4	1.425%
> 8	0.804%
> **0.846%**

@JackZhouVCD Thanks for your thorough testing!

I redid my test today, and could not repeat my previous results that shows AVX512 is even slower. Great that in most cases, we could get some gains from this PR.

**Comment by mafonsoN** [comment]
@lzhangnj is this PR ready? @ttrigui any concerns about merging this?

**Comment by ttrigui** [comment]
> @lzhangnj is this PR ready? @ttrigui any concerns about merging this?

lgtm

**Comment by JackZhouVCD** [comment]
lgtm, although I think it would be better to squash some of the commits together (for ex e37bcff, ab50e8b, and all of the bugfixing commits) so the commit log after merging is cleaner. 

Also, remember to restore [NON_AVX512_SUPPORT](https://github.com/OpenVisualCloud/SVT-AV1/pull/824/files#diff-da2060f0c21771d83ff10fed74f8423dR83)

**Comment by ttrigui** [comment]
@lzhangnj can you please fix the conflicts as well.

**Comment by lzhangnj** [comment]
> @lzhangnj please address the comments from @JackZhouVCD and we can go ahead and merge this PR.

Done. Thanks.

**Pull request merged**
