### PR TITLE
Quantization AVX2 intinsics code improvement: performance,code size &maintainability

### PR DESCRIPTION
**Pull request by Zvictoria**
# Description
Code changes decrease the number of instructions used and the code size itself. Slight performance improvement is expected.
The change makes quantization code much more refactoring friendly.
- [x] speed
- [x] 8 bit
- [x] 10 bit

# Issue

# Author(s)

# Performance impact

- [ ] quality
- [ ] memory
- [x] speed
- [x] 8 bit
- [x] 10 bit
- [ ] N/A

# Test set
- [ ] obj-1-fast can be found [here](https://media.xiph.org/video/derf/objective-1-fast.tar.gz)
- [ ] other
- [ ] N/A

# Merge method
- [x] Allow the maintainer to squash and merge when PR is ready to create a 1-commit to the master branch. The maintainer will be able to fix typos / combine commit messages to create a more readable 1-commit message or use whatever is stated in the 'Description' section
- [ ] I will clean up my commits and the maintainer shall use 'rebase and merge' to the master branch

### CODE REVIEW

**Comment by hassount** [comment]
@Zvictoria thank you for the PR. In the PR template quality is usually referring to video compression quality, is this PR changing the output bitstream ?

**Comment by Zvictoria** [comment]
@hassount , sorry for confusion, removed quality from the PR template. It is about code quality itself, not bitstream.

**Comment by EricLamVCD** [comment]
Tested obj-1 8bit and 10bit clips: 
  | Speed Deviation  | BD-Rate   Deviation | Memory   Deviation
-- | -- | -- | --
M0 - 8bit | 0.71% | 0.00% | -0.01%
M2 - 8bit | 0.91% | 0.00% | 0.01%
M4 - 8bit | 0.61% | 0.00% | 0.01%
M0 - 10bit | 4.00% | 0.00% | 0.01%
M2 - 10bit | 3.94% | 0.00% | -0.01%
M4 - 10bit | 3.76% | 0.00% | -0.01%

**Comment by EricLamVCD** [comment]
I retested with obj-1 8bit and 10bit clips on the same machines and got the following results: 
  | Speed Deviation  | BD-Rate   Deviation | Memory   Deviation
-- | -- | -- | --
M0 - 8bit | 0.01% | 0.00% | 0.14%
M4 - 8bit | -0.16% | 0.00% | 0.15%
M8 - 8bit | -0.03% | 0.00% | 0.11%
M0 - 10bit | 0.04% | 0.00% | 0.13%
M4 - 10bit | -0.05% | 0.00% | 0.02%
M8 - 10bit | 0.07% | 0.00% | 0.09%

**Comment by Zvictoria** [comment]
@EricLamVCD could you please do me a favor and test an updated patch? I've done more optimizations  and code eliminations there

**Comment by EricLamVCD** [comment]
@Zvictoria yeah I can do that. I'll run the tests now.

**Comment by Zvictoria** [comment]
@EricLamVCD mega thanks! And by chance - probably you know what's wrong with MacOS build for my PR? It looks like SVT-AV1 build system problem not my PR one...probably you've seen it before on other PRs?

**Comment by 1480c1** [comment]
I'm right now looking into that

**Comment by EricLamVCD** [comment]
I re-tested obj-1 8bit and 10bit clips on the same machine again. Here are the results: 
  | Speed Deviation  | BD-Rate   Deviation | Memory   Deviation
-- | -- | -- | --
M0 - 8bit | 0.01% | 0.00% | 0.10%
M4 - 8bit | 0.01% | 0.00% | 0.07%
M8 - 8bit | -0.05% | 0.00% | 0.19%
M0 - 10bit | 0.36% | 0.00% | 0.04%
M4 - 10bit | 0.37% | 0.00% | 0.06%
M8 - 10bit | 0.33% | 0.00% | 0.08%

**Comment by Zvictoria** [comment]
@EricLamVCD I believe it is the final version. So if you do me a final favor of measuring it, I'd be very grateful.

**Comment by EricLamVCD** [comment]
Hi @Zvictoria, could you possibly send me a sample command of what you used to test the PR? I want to make sure that we're on the same page when testing the commands. 

Here's a sample of my command that I've been running: 
`(/usr/bin/time --verbose   ./SvtAv1EncApp -enc-mode 8 -w 640 -h 360 -bit-depth 8 -fps-num 30000 -fps-denom 1001  -n  60 -q 63  -intra-period  119    -lad 0 -lp 1  -i  /home/ubuntu/stream/8bit/red_kayak_360p_60f.yuv  -b  bitstreams/svt_M8_red_kayak_360p_60f_Q63.bin )  > bitstreams/svt_M8_red_kayak_360p_60f_Q63.txt 2>&1 `

**Comment by Zvictoria** [comment]
@EricLamVCD, here it is - I use default params typically for each encoding mode and bit depth. Namely for 8 bit: 
svtav1encapp.exe -enc-mode 8 -w 1920 -h 1080  -b c:\video\video_out5 -i c:\video\video_1920x1080_5frames.yuv -bit-depth 8  -fps 60
and for high bit depth lower resolution input sequence svtav1encapp.exe  -enc-mode 8 -w 360 -h 240  -b c:\video\video_out5_10 -i c:\video\crowd_10.yuv -bit-depth 10

**Comment by EricLamVCD** [comment]
Hi @Zvictoria, I ran two tests that have similar commands. 

For the first test, I used the default commands that I used before. 
Tested obj-1 8bit and 10bit clips: 
  | Speed Deviation  | BD-Rate   Deviation | Memory   Deviation
-- | -- | -- | --
M0 - 8bit | 0.61% | 0.00% | 0.01%
M4 - 8bit | 0.71% | 0.00% | 0.01%
M8 - 8bit | 0.62% | 0.00% | -0.03%
M0 - 10bit | 0.28% | 0.00% | 0.00%
M4 - 10bit | 0.41% | 0.00% | 0.00%
M8 - 10bit | 0.13% | 0.00% | -0.02%

For the second test, I ran exactly the same parameters from your commands for 1 clip of 5 runs of 5 encodings. 

Tested Netflix_Aerial 1080p for 5 runs of 5 encodings for 500 frames and 60 fps: 
Run  | Speed Deviation  
-- | -- 
Run 1 | -0.029%
Run 2 | -0.049%
Run 3 | 0.284%
Run 4 | 0.475%
Run 5 | 0.422%
All Runs | 0.220%

**Comment by Zvictoria** [comment]
@EricLamVCD , thanks a lot! It meets my expectations.

**Comment by hassount** [comment]
@andrey-norkin merging this assuming no issues

**Pull request merged**
