### PR TITLE
More cppcheck warning fixes

### PR DESCRIPTION
**Pull request by ePirat**
This supersedes PR #1236

### CODE REVIEW

**Comment by tianjunwork** [comment]
Hi @ePirat , could you close #1236? It is ready to review, right?

**Comment by ePirat** [comment]
@tianjunwork I can not, I don't have the rights to do that.

**Comment by tianjunwork** [comment]
@ePirat Oh, sorry, that one is from Hassene. I will close it:) Thx.

**Comment by tianjunwork** [comment]
Hi @ePirat , let me know when it is done and ready to review.

**Comment by ePirat** [comment]
@tianjunwork Thanks for closing the other PR. This is ready for review now. It does not fix all issues but I did not want to make too many changes in one PR. And some warnings are hard to fix without understanding the code well.

**Comment by ePirat** [comment]
Rebased on top of current master.

**Comment by tianjunwork** [comment]
Hi @ePirat , could you solve the conflicts so that we can run validation today? thanks.

**Comment by EricLamVCD** [comment]
Tested with Obj-1 fast 8bit and 10bit test set : 
  | Speed Deviation  | BD-Rate   Deviation
-- | -- | --
M0 - 8 bit | -0.65% | 0.00%
M0 - 10 bit | 0.47% | 0.00%

**Comment by ePirat** [comment]
@tianjunwork Rebased

**Pull request merged**
