### PR TITLE
support hierarchical prediction structure level 5.

### PR DESCRIPTION
**Pull request by jerrymiao-tencent**

### CODE REVIEW

**Comment by jerrymiao-tencent** [comment]
AppVeyor build failed.  Details tell us:  Maximum allowed artifact storage size of 80000 Mb will be exceeded,  but I don't figure out how to fix it.    Could you please help me?  
@hassount hassount

**Comment by hassount** [comment]
> AppVeyor build failed. Details tell us: Maximum allowed artifact storage size of 80000 Mb will be exceeded, but I don't figure out how to fix it. Could you please help me?
> @hassount hassount

we hit the limit again, I ll submit a ticket to get it resolved

**Comment by jerrymiao-tencent** [comment]
> > AppVeyor build failed. Details tell us: Maximum allowed artifact storage size of 80000 Mb will be exceeded, but I don't figure out how to fix it. Could you please help me?
> > @hassount hassount
> 
> we hit the limit again, I ll submit a ticket to get it resolved

ok,  thanks.

**Comment by lijing0010** [comment]
@jerrymiao-tencent , I have some questions.
- level5 only support 1 forward and 1 backward refs, right?
- will it work fine with M0 which use multiple refs
- Did you test different intra-period, not 32/16/8 aligned?(eg: from 33 to 64)
- If intra-period not 32 aligned, for the trailing frames, will use low delay P refs? or will try to use mini-gop16, minigop-8?

**Comment by jerrymiao-tencent** [comment]
@lijing0010 
level5 only support 1 forward and 1 backward refs, right?  YES
will it work fine with M0 which use multiple refs?    I will check it,  I tested it's ok with M7.
Did you test different intra-period, not 32/16/8 aligned?(eg: from 33 to 64)?  Yes, I tested it's ok in different intra period from 1 to 50.
If intra-period not 32 aligned, for the trailing frames, will use low delay P refs? or will try to use mini-gop16, minigop-8?     Just like level 4 or 3.  I tested  low delay P refs  really were used for the trailing frames.

**Comment by lijing0010** [comment]
@jerrymiao-tencent , M0 is using multi-ref, so it may cause differences. but you are using only 1 ref, so should be find, but still it's safer to do a test.
And for intra-period, since you are using minigop32, so you probably should cover intra-period from 33 to 63.
And for minigop16 case, when the trailing frames is 15, we will still use a minigop8 with CRA, then use low_delay_p for the rest 7 frames, this will help on the quality.
For minigop 32, I guess this is more complicated

**Comment by jerrymiao-tencent** [comment]
@lijing0010 ，
for minigop32 case,  when the trailing frames is 31, I will still use a minigop16 、minigop8 with CRA,  then use low_delay_p for the rest 7 frames, the same as minigop16,  I tested it‘s ok, including intra period from 33 to 63.
it will cause crash, when running with M0,  the same as issue #885.

**Comment by anaghdin** [comment]
> @lijing0010 ，
> for minigop32 case, when the trailing frames is 31, I will still use a minigop16 、minigop8 with CRA, then use low_delay_p for the rest 7 frames, the same as minigop16, I tested it‘s ok, including intra period from 33 to 63.
> it will cause crash, when running with M0, the same as issue #885.

@jerrymiao-tencent Do you still get the problem?. Also do you have any performance results compared minigop 32 vs minigop 16?

**Comment by jerrymiao-tencent** [comment]
> > @lijing0010 ，
> > for minigop32 case, when the trailing frames is 31, I will still use a minigop16 、minigop8 with CRA, then use low_delay_p for the rest 7 frames, the same as minigop16, I tested it‘s ok, including intra period from 33 to 63.
> > it will cause crash, when running with M0, the same as issue #885.
> 
> @jerrymiao-tencent Do you still get the problem?. Also do you have any performance results compared minigop 32 vs minigop 16?

It's ok with M0 after solving the issue #885.  The performance results compared minigop 32 vs minigop16  and corresponding test commands are show below:  
Y | U | V
-- | -- | --
1.63% | -2.58% | -5.10%
.\bin\SvtAv1EncApp.exe -c .\SVT-AV1\Config\sample.cfg -i D:\test\seq\av1_test\1080p\BasketballDrive_1920x1080_50.yuv -b BasketballDrive_1920x1080.ivf -w 1920 -h 1080 -rc 0 -n 200 -fps 30 -intra-period -1 -enc-mode 7 -hierarchical-levels 5  -q 50

**Comment by jerrymiao-tencent** [comment]
default CQP mode(**enable_qp_scaling_flag 1**)
 Bdrate(miniGop32 vs   miniGop16)
  | Y | U | V
Flowervase_832x480_30.yuv | 4.01% | -9.22% | -9.75%
Vidyo3_1280x720_60.yuv | 1.96% | -2.49% | -7.51%
BasketballDrive_1920x1080_50.yuv | -1.09% | 3.97% | 1.96%
  | Bdrate(miniGop16 vs miniGop8)
  | Y | U | V
Flowervase_832x480_30.yuv | -1.06% | -12.65% | -13.64%
Vidyo3_1280x720_60.yuv | -10.20% | -13.64% | -14.81%
BasketballDrive_1920x1080_50.yuv | -4.59% | -1.10% | -1.93%

From the above results, the RC optimization for different layers of level 5 needs to be done later.

**Pull request merged**
