### PR TITLE
Appveyor: Port changes from SVT-HEVC and fix Bin/*/*/ folder

### PR DESCRIPTION
**Pull request by 1480c1**
@hassount, should appveyor produce static lib+exe or dll+exe?

I personally prefer static lib and exe due to dependency issues with windows, but I've also heard that some people like dll+exe since they prefer to just only replace the dll instead of caring about changes to the exe.

Adds a ffmpeg integration build on windows too

### CODE REVIEW

**Comment by hassount** [comment]
@1480c1 
sure static builds are good. Would you be able to add an ffmpeg build check on Appveyor ?

**Comment by 1480c1** [comment]
Already added

**Comment by 1480c1** [comment]
I am planning to work conflicts with libaom to be able to re-enable tests and so ffmpeg won't conflict starting tomorrow

**Comment by hassount** [comment]
@1480c1 thank you for the PR, it's great to see that we can have some testing for windows, a few questions:
- It seems that the test projects are not being built anymore, would we be able to add them back? 
- it seems that the decoder builds are not running anymore, would we be able to add them back?

**Comment by 1480c1** [comment]
> * It seems that the test projects are not being built anymore, would we be able to add them back?

Currently, it's being blocked by the symbol conflicts with libaom, right now working on fixing that, but I can switch to dynamic libs and re-enable testing for now



> * it seems that the decoder builds are not running anymore, would we be able to add them back?

I forgot to add the decoder lib and exec, going to now

**Comment by hassount** [comment]
@1480c1 
Thnx for addressing these items, would you be able to rebase it to make sure it works well with the current master after #917

**Comment by 1480c1** [comment]
image

**Comment by 1480c1** [comment]
Right now updating Visual Studio to try to debug

**Comment by 1480c1** [comment]
Planning to move most of this to Github action later

**Comment by hassount** [comment]
ready to go ? if so can you please rebase to make sure the new Appveyor storage limit has been increased ?

**Comment by 1480c1** [comment]
It seems the appveyor limit's been raised, ready from my side

**Comment by 1480c1** [comment]
@hassount, should I make it so that artifacts are only uploaded on master branch or zip up the files into one zip then send as archive?

**Comment by hassount** [comment]
> @hassount, should I make it so that artifacts are only uploaded on master branch or zip up the files into one zip then send as archive?
> 
> Alternatively, I can make it so that for all builds other than tagged releases, the artifacts will be zip files, with releases containing the regular files instead

we probably only need them for the master branch and tags, so might be best to keep it at that. trying to get an increase of storage from Appveyor in the meantime

**Comment by 1480c1** [comment]
Done

**Comment by 1480c1** [comment]
Crap, I left a fixup commit

**Comment by hassount** [comment]
> Crap, I left a fixup commit

they're both building it's ok

**Pull request merged**
