### PR TITLE
pkg-config: set version to 0.6.0 instead of 1.3.0

### PR DESCRIPTION
**Pull request by 1480c1**
Fix a copy over from SVT-HEVC

### CODE REVIEW

**Comment by kylophone** [comment]
Is there a way to templatize this with CMake?

**Comment by 1480c1** [comment]
Yes, there is. Do you want me to do so?

**Comment by 1480c1** [comment]
> Is there a way to templatize this with CMake?

It is possible to do so with #364 with https://github.com/eclipseo/SVT-AV1/pull/1

**Comment by hassount** [comment]
@andrey-norkin @joelsole @kylophone @mafonsoN 
is 0.5.0 ok for the decoder ? or should we go a little out of phase ? with a 0.1.0 ?

**Comment by hassount** [comment]
@kylophone would it make sense to merge this too ?

**Comment by 1480c1** [comment]
Need to clean up commits

**Comment by hassount** [comment]
@kylophone, OK with this ?

**Comment by kylophone** [comment]
> @kylophone, OK with this ?

LGTM. Feel free to merge whenever.

**Comment by hassount** [comment]
thnx @kylophone 
@1480c1 good to go ?

**Comment by 1480c1** [comment]
Yes

**Pull request merged**
