### PR TITLE
Travis maintenance: Update build environments, FFmpeg

### PR DESCRIPTION
**Pull request by EwoutH**
- Updates Linux build environment to Ubuntu Bionic 18.04
 - Updates macOS build environment to macOS 10.14 with Xcode 11.0
 - Update FFmpeg to 4.2 branch

@1480c1 Could you review?

### CODE REVIEW

**Comment by 1480c1** [comment]
Have you confirmed that the apt addon works in bionic? I remember when I tried to upgrade before but apt never ran

**Comment by 1480c1** [comment]
Seems to work now

**Comment by EwoutH** [comment]
It looks like the apt addon functions well. SVT-AV1 does have a problem compiling on Bionic though, probably because of the upgrade to GCC 7.4 (Xenial used 5.4.0): https://travis-ci.org/OpenVisualCloud/SVT-AV1/jobs/585753358#L659

**Comment by 1480c1** [comment]
Yeah, that's one thing I noticed previously, however I didn't want to touch that code since I'm not sure if they should be bracketed based on indention or how it actually parses.

**Comment by EwoutH** [comment]
Thanks to the fixed in #511, Travis now runs without warnings or errors!

**Comment by kylophone** [comment]
Thanks. Will merge when the appveyor build is complete.

**Comment by EwoutH** [comment]
> Will merge when the appveyor build is complete.

I haven't changed anything in the AppVeyor config, so that shouldn't be necessary.

**Pull request merged**
